src/world/area_arn/arn_02/events.c File Reference - Paper Mario Documentation
events.c File Reference
Functions
Script N (Exit1)
Script N (Exit2)
Script N (BindExits)
Script N (Main)
s32 N (padding2)[]
Script N (MakeEntities)
NpcAISettings N (goombaAISettings)
Script N (GoombaAI)
NpcSettings N (goombaNpcSettings)
NpcAISettings N (cleftAISettings)
Script N (CleftAI)
NpcSettings N (cleftNpcSettings)
StaticNpc N (CleftNPC1)
StaticNpc N (CleftNPC2)
StaticNpc N (GoombaNPC)
NpcGroupList N (npcGroupList)
s32 func_80240000_BDD1B0 (ScriptInstance *script, NpcAISettings *aiSettings, EnemyTerritoryThing *shape)
void func_802401D4_BDD384 (ScriptInstance *script, NpcAISettings *aiSettings, EnemyTerritoryThing *shape)
void func_802404D0_BDD680 (ScriptInstance *script, NpcAISettings *aiSettings, EnemyTerritoryThing *shape)
void func_80240694_BDD844 (ScriptInstance *script, NpcAISettings *aiSettings, EnemyTerritoryThing *shape)
void func_80240834_BDD9E4 (ScriptInstance *script, NpcAISettings *aiSettings, EnemyTerritoryThing *shape)
void func_80240984_BDDB34 (ScriptInstance *script, NpcAISettings *aiSettings, EnemyTerritoryThing *shape)
void func_80240A30_BDDBE0 (ScriptInstance *script, NpcAISettings *aiSettings, EnemyTerritoryThing *shape)
s32 func_80240C90_BDDE40 (ScriptInstance *script, NpcAISettings *aiSettings)
Function Documentation
N() [1/16]
Script N (Exit1)
Referenced by func_80240C90_BDDE40(), and N().
N() [2/16]
Script N (Exit2)
N() [3/16]
Script N (BindExits)
N() [4/16]
Script N (Main)
N() [5/16]
s32 N (padding2)
N() [6/16]
Script N (MakeEntities)
N() [7/16]
NpcAISettings N (goombaAISettings)
N() [8/16]
Script N (GoombaAI)
N() [9/16]
NpcSettings N (goombaNpcSettings)
N() [10/16]
NpcAISettings N (cleftAISettings)
N() [11/16]
Script N (CleftAI)
N() [12/16]
NpcSettings N (cleftNpcSettings)
N() [13/16]
StaticNpc N (CleftNPC1)
N() [14/16]
StaticNpc N (CleftNPC2)
N() [15/16]
StaticNpc N (GoombaNPC)
N() [16/16]
NpcGroupList N (npcGroupList)
func_80240000_BDD1B0()
s32 func_80240000_BDD1B0 (ScriptInstance * script, NpcAISettings * aiSettings, EnemyTerritoryThing * shape)
Definition at line 233 of file events.c.
Referenced by func_80240C90_BDDE40().
func_802401D4_BDD384()
void func_802401D4_BDD384 (ScriptInstance * script, NpcAISettings * aiSettings, EnemyTerritoryThing * shape)
Definition at line 269 of file events.c.
Referenced by func_80240C90_BDDE40().
func_802404D0_BDD680()
void func_802404D0_BDD680 (ScriptInstance * script, NpcAISettings * aiSettings, EnemyTerritoryThing * shape)
Definition at line 294 of file events.c.
Referenced by func_80240C90_BDDE40().
func_80240694_BDD844()
void func_80240694_BDD844 (ScriptInstance * script, NpcAISettings * aiSettings, EnemyTerritoryThing * shape)
Definition at line 322 of file events.c.
Referenced by func_80240C90_BDDE40().
func_80240834_BDD9E4()
void func_80240834_BDD9E4 (ScriptInstance * script, NpcAISettings * aiSettings, EnemyTerritoryThing * shape)
Definition at line 349 of file events.c.
Referenced by func_80240C90_BDDE40().
func_80240984_BDDB34()
void func_80240984_BDDB34 (ScriptInstance * script, NpcAISettings * aiSettings, EnemyTerritoryThing * shape)
Definition at line 385 of file events.c.
Referenced by func_80240C90_BDDE40().
func_80240A30_BDDBE0()
void func_80240A30_BDDBE0 (ScriptInstance * script, NpcAISettings * aiSettings, EnemyTerritoryThing * shape)
Definition at line 401 of file events.c.
Referenced by func_80240C90_BDDE40().
func_80240C90_BDDE40()
s32 func_80240C90_BDDE40 (ScriptInstance * script, NpcAISettings * aiSettings)
Definition at line 424 of file events.c.
Referenced by N().