src/audio.h File Reference - Paper Mario Documentation
audio.h File Reference
Data Structures
union UnkField
union X16
struct UnkAl1
struct InstrumentCFG
struct UnkLen18
struct UnkAl7C
struct UnkAl0
struct SoundSFXEntry
struct SoundPlayer
struct SoundSefHeader
struct SoundManager
struct UnkAlC
struct Instrument
struct UnkAl48
struct SBNFileEntry
struct InitSongEntry
struct UnkAl19E0Sub
struct UnkAl19E0Sub2
struct UnkAl19E0Sub3
struct SoundBank
struct UnkAl19E0
struct BGMPlayerTrack
struct UnkAl24
struct Fade
struct BGMPlayer
union Q32
struct UnkAl8
struct UnkAl1E4
struct UnkAl834
Typedefs
typedef void(* UnkFuncAl) ()
typedef Instrument * Instruments[16]
Functions
void snd_load_BK_headers (UnkAl19E0 *arg0, ALHeap *arg1)
void func_8004B440 (SoundManager *, u8, u8, UnkAl19E0 *, u8)
void snd_load_sfx_groups_from_SEF (SoundManager *)
void snd_clear_sfx_queue (SoundManager *)
void snd_enqueue_sfx_event (SoundManager *, s32, s16, s16, u8)
void func_8004B748 (SoundManager *)
s32 func_8004B9E4 (SoundManager *, s32)
void func_8004BA54 (SoundManager *, s32)
s16 func_8004C444 (SoundManager *)
void func_8004D510 (BGMPlayer *)
BGMPlayer * snd_get_player_with_song_name (s32)
s32 func_8004DA0C (s32)
void func_8004DAA8 (BGMPlayer *)
void func_8004DFD4 (UnkAl19E0 *)
void func_8004E158 (BGMPlayer *, s32, s32, UnkAl19E0 *)
void snd_update_bgm_fade (BGMPlayer *)
void func_8004E444 (BGMPlayer *)
s16 func_8004E4B8 (BGMPlayer *)
void snd_BGMCmd_E0_MasterTempo (BGMPlayer *, BGMPlayerTrack *)
s32 snd_bpm_to_tempo (BGMPlayer *, u32)
void snd_BGMCmd_E1_MasterVolume (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_E2_MasterTranspose (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_E3 (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_E6_MasterEffect (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_E4_MasterTempoFade (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_E5_MasterVolumeFade (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_E8_TrackOverridePatch (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_E9_SubTrackVolume (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_F6_TrackVolumeFade (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_EA_SubTrackPan (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_EB_SubTrackReverb (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_EC_SegTrackVolume (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_ED_SubTrackCoarseTune (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_EE_SubTrackFineTune (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_EF_SegTrackTune (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_F0_TrackTremolo (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_F1_TrackTremoloSpeed (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_F2_TrackTremoloTime (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_F3_TrackTremoloStop (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_F4 (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_F5_TrackVoice (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_F7_SubTrackReverbType (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_FD (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_FE (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_FC_Jump (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_FF (BGMPlayer *, BGMPlayerTrack *)
void snd_BGMCmd_NOP (BGMPlayer *, BGMPlayerTrack *)
s32 func_80056068 (s32, u8)
s32 func_800506C8 (s32, s32)
s32 func_80050C30 (u32)
void func_80050D50 (UnkAl1E4 *)
void func_800511BC (UnkAl834 *)
void func_80051334 (UnkAl834 *, UnkAl1E4 *)
void func_80051434 (UnkAl834 *, UnkAl1E4 *)
void func_800521E8 (UnkAl834 *, UnkAl1E4 *)
void func_800522A8 (UnkAl834 *, UnkAl1E4 *)
void func_8005232C (UnkAl834 *, UnkAl1E4 *)
void func_800525A0 (UnkAl19E0 *)
void func_80052614 (UnkAl19E0 *)
void func_80052660 (UnkAl19E0 *)
void func_80052B44 (UnkAl48 *)
void func_80052BF8 (UnkAl48 *, s32 *)
void snd_reset_instrument (Instrument *)
void func_80053370 (UnkAlC *)
void func_800533A8 (InstrumentCFG *)
void func_80053654 (UnkAl19E0 *)
void func_80053A18 (UnkAl1 *)
void func_80053A28 (UnkAl1 *)
void func_80053A98 (u8, u16, s32)
void func_80053AEC (UnkAl1 *, s16)
void func_80053BA8 (UnkAl1 *)
s32 func_80053BE8 (UnkAl19E0 *, s32, s32, s32 *)
void func_80054CE0 (s32, s32)
void func_8005610C (void)
void func_80055110 (BGMPlayer *)
s32 func_80055FF0 (s32, s32)
s32 func_8005600C (s32, s32)
s32 func_80056028 (s32, u8)
s32 func_80056044 (s32, u8)
void func_8005608C (s32 *, s32 *)
void func_800560A8 (void)
void func_80056144 (UnkFuncAl, s32)
void func_8005615C (void)
void func_80056180 (void)
void func_800561A4 (s32)
void func_800561C4 (s32)
void func_800561E4 (s32)
void func_80056204 (void)
void func_80056228 (void)
void func_80056D44 (s16)
s16 func_80056D50 (void)
void func_80056D78 (u8, u16)
void func_80056DCC (u8, u8)
void func_80056EC0 (u8, s8)
void func_80056EE8 (u8)
void func_80056FA4 (u8, u8, s32, f32, s16, u8, u8, s32)
void func_80057224 (u8, Instrument *)
void func_80057344 (u8, f32)
void func_8005736C (u8, s16, s32, u8, u8)
void func_80057548 (u8, u8, u8)
void func_800576EC (u8, s32, s32)
void func_80057DC8 (s32)
void func_80057E08 (u8)
void func_80057E5C (u8)
void func_80057EB0 (void)
void func_80057ED0 (s16)
void snd_load_INIT (UnkAl19E0 *, s32, ALHeap *)
s32 snd_fetch_SBN_file (u16, s32, s32 *)
void snd_load_PER (UnkAl19E0 *, s32 *)
void snd_load_PRG (UnkAl19E0 *, s32 *)
void snd_read_rom (s32, s32 *, s32)
void * alHeapAlloc (ALHeap *heap, s32 arg1, s32 size)
Variables
u8 D_80078181
s32 D_80078190
s32 D_800781D0
s32 D_80078290
s32 D_800782F8
s32 D_80078348
s32 D_80078320
s32 D_80078544
s32 D_800785A0
s32 D_80078DB0
u16 D_80078DB6
UnkAl0 * D_80078E50
UnkAl0 * D_80078E54
s8 D_80078E58
s16 D_80078E5A
s8 D_80078E5C
s32 * D_8007F1F8
UnkAl19E0 * D_8009A5C0
BGMPlayer * D_8009A5CC
BGMPlayer * D_8009A5FC
UnkFuncAl D_8009A5E8
UnkAl834 * D_8009A628
SoundManager * D_8009A640
BGMPlayer * D_8009A664
u16 D_800A0F50
s32 * D_800A3FE0
s32 * D_800A3FE4
s32 D_800A3FE8
s8 D_800A3FEC
s16 D_800A3FEE
s32 D_800A3FF0
Typedef Documentation
UnkFuncAl
typedef void(* UnkFuncAl) ()
Definition at line 9 of file audio.h.
Instruments
typedef Instrument* Instruments[16]
Definition at line 213 of file audio.h.
Function Documentation
snd_load_BK_headers()
void snd_load_BK_headers (UnkAl19E0 * arg0, ALHeap * arg1)
Definition at line 4 of file code_303c0_len_3e10.c.
Referenced by snd_load_audio_data().
func_8004B440()
void func_8004B440 (SoundManager * manager, u8 arg1, u8 arg2, UnkAl19E0 * arg3, u8 arg4)
Definition at line 4 of file code_26840_len_20d0.c.
Referenced by snd_load_audio_data().
snd_load_sfx_groups_from_SEF()
void snd_load_sfx_groups_from_SEF (SoundManager * manager)
Definition at line 86 of file code_26840_len_20d0.c.
Referenced by snd_load_audio_data().
snd_clear_sfx_queue()
void snd_clear_sfx_queue (SoundManager * manager)
Definition at line 88 of file code_26840_len_20d0.c.
Referenced by func_8004B440().
snd_enqueue_sfx_event()
void snd_enqueue_sfx_event (SoundManager * manager, s32 soundID, s16 volume, s16 pitchShift, u8 pan)
Definition at line 105 of file code_26840_len_20d0.c.
Referenced by snd_adjust_sound(), snd_adjust_sound_with_shift(), snd_start_sound(), snd_start_sound_raw(), snd_start_sound_with_shift(), and snd_stop_sound().
func_8004B748()
void func_8004B748 (SoundManager * manager)
Definition at line 131 of file code_26840_len_20d0.c.
Referenced by func_800535C0().
func_8004B9E4()
s32 func_8004B9E4 (SoundManager * manager, s32 arg1)
Definition at line 133 of file code_26840_len_20d0.c.
Referenced by func_8004B440(), and func_80054D74().
func_8004BA54()
void func_8004BA54 (SoundManager * manager, s32 arg1)
Definition at line 153 of file code_26840_len_20d0.c.
Referenced by func_8004B440(), func_80056204(), and func_80056228().
func_8004C444()
s16 func_8004C444 (SoundManager * manager)
Definition at line 175 of file code_26840_len_20d0.c.
Referenced by snd_update_sequence_players().
func_8004D510()
void func_8004D510 (BGMPlayer * arg0)
Definition at line 3 of file code_28910_len_5090.c.
Referenced by func_800535C0().
snd_get_player_with_song_name()
BGMPlayer* snd_get_player_with_song_name (s32 songString)
Definition at line 8 of file code_28910_len_5090.c.
Referenced by func_8004DA0C().
func_8004DA0C()
s32 func_8004DA0C (s32 arg0)
Definition at line 25 of file code_28910_len_5090.c.
Referenced by func_800559C4().
func_8004DAA8()
void func_8004DAA8 (BGMPlayer * arg0)
Definition at line 52 of file code_28910_len_5090.c.
Referenced by func_8004DA0C(), and snd_update_bgm_fade().
func_8004DFD4()
void func_8004DFD4 (UnkAl19E0 * arg0)
Definition at line 73 of file code_28910_len_5090.c.
Referenced by snd_update_sequence_players().
func_8004E158()
void func_8004E158 (BGMPlayer * arg0, s32 arg1, s32 arg2, UnkAl19E0 * arg3)
Definition at line 77 of file code_28910_len_5090.c.
Referenced by snd_load_audio_data().
snd_update_bgm_fade()
void snd_update_bgm_fade (BGMPlayer * player)
Definition at line 158 of file code_28910_len_5090.c.
Referenced by snd_update_sequence_players().
func_8004E444()
void func_8004E444 (BGMPlayer * arg0)
Definition at line 179 of file code_28910_len_5090.c.
Referenced by snd_update_bgm_fade(), and snd_update_sequence_players().
func_8004E4B8()
s16 func_8004E4B8 (BGMPlayer * player)
Definition at line 193 of file code_28910_len_5090.c.
Referenced by snd_update_sequence_players().
snd_BGMCmd_E0_MasterTempo()
void snd_BGMCmd_E0_MasterTempo (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 211 of file code_28910_len_5090.c.
snd_bpm_to_tempo()
s32 snd_bpm_to_tempo (BGMPlayer * player, u32 tempo)
Definition at line 224 of file code_28910_len_5090.c.
Referenced by snd_BGMCmd_E0_MasterTempo(), and snd_BGMCmd_E4_MasterTempoFade().
snd_BGMCmd_E1_MasterVolume()
void snd_BGMCmd_E1_MasterVolume (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 239 of file code_28910_len_5090.c.
snd_BGMCmd_E2_MasterTranspose()
void snd_BGMCmd_E2_MasterTranspose (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 254 of file code_28910_len_5090.c.
snd_BGMCmd_E3()
void snd_BGMCmd_E3 (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 258 of file code_28910_len_5090.c.
snd_BGMCmd_E6_MasterEffect()
void snd_BGMCmd_E6_MasterEffect (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 263 of file code_28910_len_5090.c.
snd_BGMCmd_E4_MasterTempoFade()
void snd_BGMCmd_E4_MasterTempoFade (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 276 of file code_28910_len_5090.c.
snd_BGMCmd_E5_MasterVolumeFade()
void snd_BGMCmd_E5_MasterVolumeFade (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 291 of file code_28910_len_5090.c.
snd_BGMCmd_E8_TrackOverridePatch()
void snd_BGMCmd_E8_TrackOverridePatch (BGMPlayer * , BGMPlayerTrack *)
snd_BGMCmd_E9_SubTrackVolume()
void snd_BGMCmd_E9_SubTrackVolume (BGMPlayer * arg0, BGMPlayerTrack * track)
Definition at line 323 of file code_28910_len_5090.c.
snd_BGMCmd_F6_TrackVolumeFade()
void snd_BGMCmd_F6_TrackVolumeFade (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 336 of file code_28910_len_5090.c.
Referenced by func_8005083C().
snd_BGMCmd_EA_SubTrackPan()
void snd_BGMCmd_EA_SubTrackPan (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 362 of file code_28910_len_5090.c.
snd_BGMCmd_EB_SubTrackReverb()
void snd_BGMCmd_EB_SubTrackReverb (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 368 of file code_28910_len_5090.c.
snd_BGMCmd_EC_SegTrackVolume()
void snd_BGMCmd_EC_SegTrackVolume (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 373 of file code_28910_len_5090.c.
snd_BGMCmd_ED_SubTrackCoarseTune()
void snd_BGMCmd_ED_SubTrackCoarseTune (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 378 of file code_28910_len_5090.c.
snd_BGMCmd_EE_SubTrackFineTune()
void snd_BGMCmd_EE_SubTrackFineTune (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 382 of file code_28910_len_5090.c.
snd_BGMCmd_EF_SegTrackTune()
void snd_BGMCmd_EF_SegTrackTune (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 386 of file code_28910_len_5090.c.
snd_BGMCmd_F0_TrackTremolo()
void snd_BGMCmd_F0_TrackTremolo (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 391 of file code_28910_len_5090.c.
snd_BGMCmd_F1_TrackTremoloSpeed()
void snd_BGMCmd_F1_TrackTremoloSpeed (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 397 of file code_28910_len_5090.c.
snd_BGMCmd_F2_TrackTremoloTime()
void snd_BGMCmd_F2_TrackTremoloTime (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 401 of file code_28910_len_5090.c.
snd_BGMCmd_F3_TrackTremoloStop()
void snd_BGMCmd_F3_TrackTremoloStop (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 405 of file code_28910_len_5090.c.
snd_BGMCmd_F4()
void snd_BGMCmd_F4 (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 409 of file code_28910_len_5090.c.
snd_BGMCmd_F5_TrackVoice()
void snd_BGMCmd_F5_TrackVoice (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 414 of file code_28910_len_5090.c.
snd_BGMCmd_F7_SubTrackReverbType()
void snd_BGMCmd_F7_SubTrackReverbType (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 416 of file code_28910_len_5090.c.
snd_BGMCmd_FD()
void snd_BGMCmd_FD (BGMPlayer * , BGMPlayerTrack *)
snd_BGMCmd_FE()
void snd_BGMCmd_FE (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 436 of file code_28910_len_5090.c.
snd_BGMCmd_FC_Jump()
void snd_BGMCmd_FC_Jump (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 444 of file code_28910_len_5090.c.
snd_BGMCmd_FF()
void snd_BGMCmd_FF (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 446 of file code_28910_len_5090.c.
snd_BGMCmd_NOP()
void snd_BGMCmd_NOP (BGMPlayer * player, BGMPlayerTrack * track)
Definition at line 448 of file code_28910_len_5090.c.
func_80056068()
s32 func_80056068 (s32 arg0, u8 arg1)
Definition at line 408 of file code_30450.c.
Referenced by func_8014AA54().
func_800506C8()
s32 func_800506C8 (s32 arg0, s32 arg1)
Definition at line 459 of file code_28910_len_5090.c.
Referenced by func_80056028(), func_80056044(), and func_80056068().
func_80050C30()
s32 func_80050C30 (u32 arg0)
Definition at line 5 of file code_2BF90.c.
Referenced by func_80055464(), func_800554A4(), func_800554E8(), func_8005553C(), func_80055590(), func_800555E4(), func_80055618(), func_8005566C(), func_800556D0(), and func_80055718().
func_80050D50()
void func_80050D50 (UnkAl1E4 * arg0)
Definition at line 21 of file code_2BF90.c.
Referenced by func_800511BC().
func_800511BC()
void func_800511BC (UnkAl834 * arg0)
Definition at line 37 of file code_2BF90.c.
Referenced by snd_update_sequence_players().
func_80051334()
void func_80051334 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 88 of file code_2BF90.c.
Referenced by func_800511BC().
func_80051434()
void func_80051434 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 90 of file code_2BF90.c.
Referenced by func_800511BC().
func_800521E8()
void func_800521E8 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 94 of file code_2BF90.c.
Referenced by func_800511BC().
func_800522A8()
void func_800522A8 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 96 of file code_2BF90.c.
Referenced by func_800511BC().
func_8005232C()
void func_8005232C (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 98 of file code_2BF90.c.
Referenced by func_800511BC().
func_800525A0()
void func_800525A0 (UnkAl19E0 * arg0)
Definition at line 4 of file code_2d9a0_len_890.c.
func_80052614()
void func_80052614 (UnkAl19E0 * arg0)
Definition at line 19 of file code_2d9a0_len_890.c.
Referenced by snd_load_audio_data().
func_80052660()
void func_80052660 (UnkAl19E0 * arg0)
Definition at line 37 of file code_2d9a0_len_890.c.
Referenced by snd_update_sequence_players().
func_80052B44()
void func_80052B44 (UnkAl48 * arg0)
Definition at line 39 of file code_2d9a0_len_890.c.
func_80052BF8()
void func_80052BF8 (UnkAl48 * arg0, s32 * arg1)
Definition at line 52 of file code_2d9a0_len_890.c.
Referenced by func_80053654().
snd_reset_instrument()
void snd_reset_instrument (Instrument * instrument)
Definition at line 143 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
func_80053370()
void func_80053370 (UnkAlC * arg0)
Definition at line 165 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
func_800533A8()
void func_800533A8 (InstrumentCFG * arg0)
Definition at line 177 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
func_80053654()
void func_80053654 (UnkAl19E0 * arg0)
Definition at line 278 of file code_2e230_len_2190.c.
Referenced by snd_update_sequence_players().
func_80053A18()
void func_80053A18 (UnkAl1 * arg0)
Definition at line 385 of file code_2e230_len_2190.c.
Referenced by func_8004DAA8().
func_80053A28()
void func_80053A28 (UnkAl1 * arg0)
Definition at line 391 of file code_2e230_len_2190.c.
Referenced by snd_update_sequence_players().
func_80053A98()
void func_80053A98 (u8 arg0, u16 arg1, s32 arg2)
Definition at line 406 of file code_2e230_len_2190.c.
Referenced by func_8004B440(), func_8004E444(), and snd_update_sequence_players().
func_80053AEC()
void func_80053AEC (UnkAl1 * arg0, s16 arg1)
Definition at line 418 of file code_2e230_len_2190.c.
Referenced by func_8004E158().
func_80053BA8()
void func_80053BA8 (UnkAl1 * arg0)
Definition at line 442 of file code_2e230_len_2190.c.
Referenced by snd_update_sequence_players().
func_80053BE8()
s32 func_80053BE8 (UnkAl19E0 * arg0, s32 arg1, s32 arg2, s32 * arg3)
Definition at line 453 of file code_2e230_len_2190.c.
Referenced by snd_BGMCmd_E8_TrackOverridePatch().
func_80054CE0()
void func_80054CE0 (s32 arg0, s32 arg1)
Definition at line 611 of file code_2e230_len_2190.c.
Referenced by func_800561A4(), and func_800561C4().
func_8005610C()
void func_8005610C (void)
Definition at line 425 of file code_30450.c.
Referenced by func_800535C0(), and snd_load_audio_data().
func_80055110()
void func_80055110 (BGMPlayer * arg0)
Definition at line 25 of file code_30450.c.
Referenced by func_8004E158().
func_80055FF0()
s32 func_80055FF0 (s32 arg0, s32 arg1)
Definition at line 392 of file code_30450.c.
func_8005600C()
s32 func_8005600C (s32 arg0, s32 arg1)
Definition at line 396 of file code_30450.c.
func_80056028()
s32 func_80056028 (s32 arg0, u8 arg1)
Definition at line 400 of file code_30450.c.
Referenced by func_8014AA54().
func_80056044()
s32 func_80056044 (s32 arg0, u8 arg1)
Definition at line 404 of file code_30450.c.
Referenced by func_8014AA54().
func_8005608C()
void func_8005608C (s32 * arg0, s32 * arg1)
Definition at line 412 of file code_30450.c.
func_800560A8()
void func_800560A8 (void)
Definition at line 419 of file code_30450.c.
func_80056144()
void func_80056144 (UnkFuncAl arg0, s32 arg1)
Definition at line 427 of file code_30450.c.
func_8005615C()
void func_8005615C (void)
Definition at line 431 of file code_30450.c.
Referenced by step_init_state().
func_80056180()
void func_80056180 (void)
Definition at line 436 of file code_30450.c.
Referenced by step_init_state().
func_800561A4()
void func_800561A4 (s32 arg0)
Definition at line 441 of file code_30450.c.
Referenced by bgm_reset_sequence_players(), and bgm_update_volume().
func_800561C4()
void func_800561C4 (s32 arg0)
Definition at line 445 of file code_30450.c.
func_800561E4()
void func_800561E4 (s32 arg0)
Definition at line 449 of file code_30450.c.
Referenced by func_801497FC().
func_80056204()
void func_80056204 (void)
Definition at line 453 of file code_30450.c.
func_80056228()
void func_80056228 (void)
Definition at line 457 of file code_30450.c.
Referenced by init_demo_data().
func_80056D44()
void func_80056D44 (s16 arg0)
Definition at line 32 of file code_31650.c.
Referenced by func_8004B328().
func_80056D50()
s16 func_80056D50 (void)
Definition at line 36 of file code_31650.c.
Referenced by func_8004B328().
func_80056D78()
void func_80056D78 (u8 arg0, u16 arg1)
Definition at line 49 of file code_31650.c.
Referenced by func_80053A98().
func_80056DCC()
void func_80056DCC (u8 arg0, u8 arg1)
Definition at line 61 of file code_31650.c.
Referenced by func_80053654().
func_80056EC0()
void func_80056EC0 (u8 arg0, s8 arg1)
Definition at line 71 of file code_31650.c.
Referenced by snd_load_audio_data().
func_80056EE8()
void func_80056EE8 (u8 arg0)
Definition at line 77 of file code_31650.c.
Referenced by func_800525A0(), and func_80053654().
func_80056FA4()
void func_80056FA4 (u8 arg0, u8 arg1, s32 arg2, f32 arg3, s16 arg4, u8 arg5, u8 arg6, s32 arg7)
Definition at line 86 of file code_31650.c.
Referenced by func_80053654().
func_80057224()
void func_80057224 (u8 arg0, Instrument * arg1)
Definition at line 88 of file code_31650.c.
Referenced by snd_load_audio_data().
func_80057344()
void func_80057344 (u8 arg0, f32 arg1)
Definition at line 90 of file code_31650.c.
Referenced by func_80053654().
func_8005736C()
void func_8005736C (u8 arg0, s16 arg1, s32 arg2, u8 arg3, u8 arg4)
Definition at line 96 of file code_31650.c.
Referenced by func_80053654().
func_80057548()
void func_80057548 (u8 arg0, u8 arg1, u8 arg2)
Definition at line 98 of file code_31650.c.
Referenced by func_80053654().
func_800576EC()
void func_800576EC (u8 arg0, s32 arg1, s32 arg2)
Definition at line 100 of file code_31650.c.
Referenced by func_80053888(), and func_800538C4().
func_80057DC8()
void func_80057DC8 (s32 arg0)
Definition at line 146 of file code_31650.c.
Referenced by func_80053654().
func_80057E08()
void func_80057E08 (u8 arg0)
Definition at line 160 of file code_31650.c.
Referenced by func_80053654().
func_80057E5C()
void func_80057E5C (u8 arg0)
Definition at line 175 of file code_31650.c.
Referenced by func_80053654().
func_80057EB0()
void func_80057EB0 (void)
Definition at line 190 of file code_31650.c.
Referenced by func_80053654().
func_80057ED0()
void func_80057ED0 (s16 arg0)
Definition at line 196 of file code_31650.c.
Referenced by snd_load_audio_data().
snd_load_INIT()
void snd_load_INIT (UnkAl19E0 * arg0, s32 arg1, ALHeap * arg2)
Definition at line 519 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
snd_fetch_SBN_file()
s32 snd_fetch_SBN_file (u16 arg0, s32 arg1, s32 * arg2)
Definition at line 521 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
snd_load_PER()
void snd_load_PER (UnkAl19E0 * arg0, s32 * arg1)
Definition at line 523 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
snd_load_PRG()
void snd_load_PRG (UnkAl19E0 * arg0, s32 * arg1)
Definition at line 525 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
snd_read_rom()
void snd_read_rom (s32 arg0, s32 * arg1, s32 arg2)
Definition at line 622 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
alHeapAlloc()
void* alHeapAlloc (ALHeap * heap, s32 arg1, s32 size)
Definition at line 213 of file code_31650.c.
Referenced by snd_load_audio_data().
Variable Documentation
D_80078181
u8 D_80078181 extern
Definition at line 13 of file code_25f00_len_940.c.
Referenced by func_80056D5C().
D_80078190
s32 D_80078190 extern
Referenced by snd_reset_instrument().
D_800781D0
s32 D_800781D0 extern
Referenced by snd_reset_instrument().
D_80078290
s32 D_80078290 extern
Referenced by func_8004B440().
D_800782F8
s32 D_800782F8 extern
Referenced by func_8004B440().
D_80078348
s32 D_80078348 extern
Referenced by func_8004B440().
D_80078320
s32 D_80078320 extern
Referenced by func_8004B440().
D_80078544
s32 D_80078544 extern
Referenced by snd_reset_instrument().
D_800785A0
s32 D_800785A0 extern
D_80078DB0
s32 D_80078DB0 extern
Definition at line 4 of file code_30450.c.
Referenced by func_80055050(), and snd_update_sequence_players().
D_80078DB6
u16 D_80078DB6 extern
Definition at line 6 of file code_30450.c.
Referenced by func_80055760(), func_800557CC(), and func_80055848().
D_80078E50
UnkAl0* D_80078E50 extern
Definition at line 4 of file code_31650.c.
Referenced by func_800565A4().
D_80078E54
UnkAl0* D_80078E54 extern
Definition at line 5 of file code_31650.c.
Referenced by func_80056D78(), func_80056DA4(), func_80056DCC(), func_80056EC0(), func_80056F78(), func_80057344(), func_80057B64(), func_80057B8C(), func_80057BB4(), func_80057BDC(), func_80057C04(), func_80057C2C(), and snd_load_audio_data().
D_80078E58
s8 D_80078E58 extern
Definition at line 6 of file code_31650.c.
Referenced by func_80056D34().
D_80078E5A
s16 D_80078E5A extern
Definition at line 7 of file code_31650.c.
Referenced by func_80056D44(), and func_80056D50().
D_80078E5C
s8 D_80078E5C extern
Definition at line 8 of file code_31650.c.
Referenced by func_80056D5C().
D_8007F1F8
s32* D_8007F1F8 extern
Referenced by func_8004B9E4().
D_8009A5C0
UnkAl19E0* D_8009A5C0 extern
Referenced by func_80052E30(), func_800535C0(), func_80053F64(), func_8005608C(), func_800560A8(), func_80056144(), snd_get_BK_instruments(), snd_get_sequence_player_and_track(), snd_load_audio_data(), snd_load_BK(), snd_swizzle_BK_instruments(), and snd_update_sequence_players().
D_8009A5CC
BGMPlayer* D_8009A5CC extern
Referenced by snd_load_audio_data().
D_8009A5FC
BGMPlayer* D_8009A5FC extern
Referenced by func_800535C0(), func_80054248(), snd_get_player_with_song_name(), snd_get_sequence_player(), snd_get_sequence_player_and_track(), snd_load_audio_data(), and snd_update_sequence_players().
D_8009A5E8
UnkFuncAl D_8009A5E8 extern
Referenced by func_800535C0().
D_8009A628
UnkAl834* D_8009A628 extern
Referenced by func_80050C30(), func_80050C54(), snd_load_audio_data(), and snd_update_sequence_players().
D_8009A640
SoundManager* D_8009A640 extern
Referenced by func_800535C0(), func_80054248(), func_80054D74(), func_800553F4(), func_80056204(), func_80056228(), snd_adjust_sound(), snd_adjust_sound_with_shift(), snd_load_audio_data(), snd_start_sound(), snd_start_sound_raw(), snd_start_sound_with_shift(), snd_stop_sound(), and snd_update_sequence_players().
D_8009A664
BGMPlayer* D_8009A664 extern
Referenced by func_800535C0(), func_80054248(), snd_get_player_with_song_name(), snd_get_sequence_player(), snd_get_sequence_player_and_track(), snd_load_audio_data(), and snd_update_sequence_players().
D_800A0F50
u16 D_800A0F50 extern
Referenced by func_8004B328().
D_800A3FE0
s32* D_800A3FE0 extern
Referenced by func_80057E08(), func_80057E5C(), and func_80057ED0().
D_800A3FE4
s32* D_800A3FE4 extern
Referenced by func_80057E08(), func_80057E5C(), and func_80057ED0().
D_800A3FE8
s32 D_800A3FE8 extern
Referenced by func_80057E08(), func_80057E5C(), func_80057EB0(), and func_80057ED0().
D_800A3FEC
s8 D_800A3FEC extern
Referenced by func_80057E08(), func_80057E5C(), func_80057EB0(), and func_80057ED0().
D_800A3FEE
s16 D_800A3FEE extern
Referenced by func_80057DC8(), func_80057E08(), func_80057E5C(), func_80057EB0(), and func_80057ED0().
D_800A3FF0
s32 D_800A3FF0 extern
Referenced by func_80057DC8().