src/code_303c0_len_3e10.c File Reference - Paper Mario Documentation
code_303c0_len_3e10.c File Reference
Functions
s32 al_LoadBKHeaders ()
void func_80055050 (void)
void func_80055068 (u32 arg0)
s32 func_80055110 ()
s32 func_8005513C ()
s32 func_800551E0 ()
s32 func_80055240 ()
s32 func_800552D0 ()
s32 func_80055330 ()
s32 func_800553C0 ()
s32 func_800553F4 ()
s32 func_80055408 ()
s32 func_80055448 (s32 arg0)
s32 func_80055464 (s32 arg0, s32 arg1)
s32 func_800554A4 (s32 arg0, s32 arg1)
s32 func_800554E8 (s32 arg0, s32 arg1)
s32 func_8005553C ()
s32 func_80055590 ()
s32 func_800555E4 (s32 arg0)
s32 func_80055618 ()
s32 func_8005566C ()
s32 func_800556D0 ()
s32 func_80055718 ()
s32 func_80055760 ()
s32 func_800557CC ()
s32 func_80055848 ()
s32 func_800558D4 ()
s32 func_8005591C ()
s32 func_80055970 ()
s32 func_800559C4 (s32 arg0)
s32 func_800559E0 ()
s32 func_800559FC ()
s32 func_80055A18 ()
s32 func_80055A6C ()
s32 func_80055ABC ()
s32 func_80055AF0 ()
s32 func_80055B28 ()
s32 func_80055B80 ()
s32 func_80055BB8 ()
s32 func_80055BF0 ()
s32 func_80055C2C ()
s32 func_80055C64 ()
s32 func_80055C94 ()
s32 func_80055CC4 ()
s32 func_80055CE8 ()
s32 func_80055D38 ()
s32 func_80055D8C ()
s32 func_80055DDC ()
s32 func_80055E48 ()
s32 func_80055EB4 ()
s32 func_80055F58 ()
s32 func_80055FD4 ()
s32 func_80055FF0 ()
s32 func_8005600C ()
s32 func_80056028 ()
s32 func_80056044 ()
s32 func_80056068 ()
s32 func_8005608C ()
s32 func_800560A8 ()
s32 func_800560BC ()
s32 func_8005610C ()
s32 func_80056144 ()
s32 func_8005615C ()
s32 func_80056180 ()
s32 func_800561A4 ()
s32 func_800561C4 ()
s32 func_800561E4 ()
s32 func_80056204 ()
s32 func_80056228 ()
s32 func_80056250 ()
s32 func_800565A4 ()
Acmd * alAudioFrame (Acmd *cmdList, s32 *cmdLen, s16 *outBuf, s32 outLen)
s32 func_80056D34 ()
s32 func_80056D44 ()
s32 func_80056D50 ()
s32 func_80056D5C ()
s32 func_80056D78 ()
s32 func_80056DA4 ()
s32 func_80056DCC ()
s32 func_80056E34 ()
s32 func_80056EC0 ()
s32 func_80056EE8 ()
s32 func_80056F78 ()
s32 func_80056FA4 ()
s32 func_80057224 ()
s32 func_80057344 ()
s32 func_8005736C ()
s32 func_80057548 ()
s32 func_800576EC ()
s32 func_80057874 ()
s32 func_800579D8 ()
s32 func_80057B64 ()
s32 func_80057B8C ()
s32 func_80057BB4 ()
s32 func_80057BDC ()
s32 func_80057C04 ()
s32 func_80057C2C ()
s32 func_80057C54 ()
s32 func_80057D0C ()
s32 func_80057DC8 ()
s32 func_80057E08 ()
s32 func_80057E5C ()
s32 func_80057EB0 ()
s32 func_80057ED0 ()
s32 func_80057F20 ()
void alHeapAlloc (u8 *file, s32 line, ALHeap *hp, s32 num, s32 size)
s32 func_80057FD8 ()
s32 func_80058004 ()
s32 func_80058050 ()
s32 func_80058B20 ()
s32 func_80058C6C ()
Variables
s32 D_80078DB0
u16 D_80078DB4
Function Documentation
al_LoadBKHeaders()
s32 al_LoadBKHeaders ()
Definition at line 7 of file code_303c0_len_3e10.c.
func_80055050()
void func_80055050 (void)
Definition at line 11 of file code_303c0_len_3e10.c.
func_80055068()
void func_80055068 (u32 arg0)
Definition at line 19 of file code_303c0_len_3e10.c.
func_80055110()
s32 func_80055110 ()
Definition at line 21 of file code_303c0_len_3e10.c.
func_8005513C()
s32 func_8005513C ()
Definition at line 23 of file code_303c0_len_3e10.c.
func_800551E0()
s32 func_800551E0 ()
Definition at line 25 of file code_303c0_len_3e10.c.
func_80055240()
s32 func_80055240 ()
Definition at line 27 of file code_303c0_len_3e10.c.
func_800552D0()
s32 func_800552D0 ()
Definition at line 29 of file code_303c0_len_3e10.c.
func_80055330()
s32 func_80055330 ()
Definition at line 31 of file code_303c0_len_3e10.c.
func_800553C0()
s32 func_800553C0 ()
Definition at line 33 of file code_303c0_len_3e10.c.
func_800553F4()
s32 func_800553F4 ()
Definition at line 35 of file code_303c0_len_3e10.c.
func_80055408()
s32 func_80055408 ()
Definition at line 37 of file code_303c0_len_3e10.c.
func_80055448()
s32 func_80055448 (s32 arg0)
Definition at line 39 of file code_303c0_len_3e10.c.
Referenced by func_80147264().
func_80055464()
s32 func_80055464 (s32 arg0, s32 arg1)
Definition at line 41 of file code_303c0_len_3e10.c.
Referenced by func_80147264().
func_800554A4()
s32 func_800554A4 (s32 arg0, s32 arg1)
Definition at line 43 of file code_303c0_len_3e10.c.
Referenced by func_80147264(), and play_ambient_sounds().
func_800554E8()
s32 func_800554E8 (s32 arg0, s32 arg1)
Definition at line 45 of file code_303c0_len_3e10.c.
Referenced by func_80147264(), and func_802405CC_8AC55C().
func_8005553C()
s32 func_8005553C ()
Definition at line 47 of file code_303c0_len_3e10.c.
Referenced by func_80240584_8AC514().
func_80055590()
s32 func_80055590 ()
Definition at line 49 of file code_303c0_len_3e10.c.
Referenced by func_802405A8_8AC538().
func_800555E4()
s32 func_800555E4 (s32 arg0)
Definition at line 51 of file code_303c0_len_3e10.c.
Referenced by func_80147264().
func_80055618()
s32 func_80055618 ()
Definition at line 53 of file code_303c0_len_3e10.c.
func_8005566C()
s32 func_8005566C ()
Definition at line 55 of file code_303c0_len_3e10.c.
func_800556D0()
s32 func_800556D0 ()
Definition at line 57 of file code_303c0_len_3e10.c.
func_80055718()
s32 func_80055718 ()
Definition at line 59 of file code_303c0_len_3e10.c.
func_80055760()
s32 func_80055760 ()
Definition at line 61 of file code_303c0_len_3e10.c.
func_800557CC()
s32 func_800557CC ()
Definition at line 63 of file code_303c0_len_3e10.c.
func_80055848()
s32 func_80055848 ()
Definition at line 65 of file code_303c0_len_3e10.c.
func_800558D4()
s32 func_800558D4 ()
Definition at line 67 of file code_303c0_len_3e10.c.
func_8005591C()
s32 func_8005591C ()
Definition at line 69 of file code_303c0_len_3e10.c.
func_80055970()
s32 func_80055970 ()
Definition at line 71 of file code_303c0_len_3e10.c.
func_800559C4()
s32 func_800559C4 (s32 arg0)
Definition at line 73 of file code_303c0_len_3e10.c.
Referenced by _set_music_track(), and func_8014A964().
func_800559E0()
s32 func_800559E0 ()
Definition at line 77 of file code_303c0_len_3e10.c.
func_800559FC()
s32 func_800559FC ()
Definition at line 79 of file code_303c0_len_3e10.c.
func_80055A18()
s32 func_80055A18 ()
Definition at line 81 of file code_303c0_len_3e10.c.
func_80055A6C()
s32 func_80055A6C ()
Definition at line 83 of file code_303c0_len_3e10.c.
func_80055ABC()
s32 func_80055ABC ()
Definition at line 85 of file code_303c0_len_3e10.c.
func_80055AF0()
s32 func_80055AF0 ()
Definition at line 87 of file code_303c0_len_3e10.c.
func_80055B28()
s32 func_80055B28 ()
Definition at line 89 of file code_303c0_len_3e10.c.
func_80055B80()
s32 func_80055B80 ()
Definition at line 91 of file code_303c0_len_3e10.c.
Referenced by _set_music_track().
func_80055BB8()
s32 func_80055BB8 ()
Definition at line 93 of file code_303c0_len_3e10.c.
func_80055BF0()
s32 func_80055BF0 ()
Definition at line 95 of file code_303c0_len_3e10.c.
func_80055C2C()
s32 func_80055C2C ()
Definition at line 97 of file code_303c0_len_3e10.c.
func_80055C64()
s32 func_80055C64 ()
Definition at line 99 of file code_303c0_len_3e10.c.
func_80055C94()
s32 func_80055C94 ()
Definition at line 101 of file code_303c0_len_3e10.c.
func_80055CC4()
s32 func_80055CC4 ()
Definition at line 103 of file code_303c0_len_3e10.c.
Referenced by func_8014ABB4().
func_80055CE8()
s32 func_80055CE8 ()
Definition at line 105 of file code_303c0_len_3e10.c.
func_80055D38()
s32 func_80055D38 ()
Definition at line 107 of file code_303c0_len_3e10.c.
func_80055D8C()
s32 func_80055D8C ()
Definition at line 109 of file code_303c0_len_3e10.c.
func_80055DDC()
s32 func_80055DDC ()
Definition at line 111 of file code_303c0_len_3e10.c.
Referenced by func_8014AB0C().
func_80055E48()
s32 func_80055E48 ()
Definition at line 113 of file code_303c0_len_3e10.c.
Referenced by func_8014AB60().
func_80055EB4()
s32 func_80055EB4 ()
Definition at line 115 of file code_303c0_len_3e10.c.
func_80055F58()
s32 func_80055F58 ()
Definition at line 117 of file code_303c0_len_3e10.c.
func_80055FD4()
s32 func_80055FD4 ()
Definition at line 119 of file code_303c0_len_3e10.c.
func_80055FF0()
s32 func_80055FF0 ()
Definition at line 121 of file code_303c0_len_3e10.c.
func_8005600C()
s32 func_8005600C ()
Definition at line 123 of file code_303c0_len_3e10.c.
func_80056028()
s32 func_80056028 ()
Definition at line 125 of file code_303c0_len_3e10.c.
Referenced by func_8014AA54().
func_80056044()
s32 func_80056044 ()
Definition at line 127 of file code_303c0_len_3e10.c.
Referenced by func_8014AA54().
func_80056068()
s32 func_80056068 ()
Definition at line 129 of file code_303c0_len_3e10.c.
Referenced by func_8014AA54().
func_8005608C()
s32 func_8005608C ()
Definition at line 131 of file code_303c0_len_3e10.c.
func_800560A8()
s32 func_800560A8 ()
Definition at line 133 of file code_303c0_len_3e10.c.
func_800560BC()
s32 func_800560BC ()
Definition at line 135 of file code_303c0_len_3e10.c.
func_8005610C()
s32 func_8005610C ()
Definition at line 137 of file code_303c0_len_3e10.c.
func_80056144()
s32 func_80056144 ()
Definition at line 139 of file code_303c0_len_3e10.c.
func_8005615C()
s32 func_8005615C ()
Definition at line 141 of file code_303c0_len_3e10.c.
Referenced by step_init_state().
func_80056180()
s32 func_80056180 ()
Definition at line 143 of file code_303c0_len_3e10.c.
Referenced by step_init_state().
func_800561A4()
s32 func_800561A4 ()
Definition at line 145 of file code_303c0_len_3e10.c.
Referenced by func_8014A498().
func_800561C4()
s32 func_800561C4 ()
Definition at line 147 of file code_303c0_len_3e10.c.
func_800561E4()
s32 func_800561E4 ()
Definition at line 149 of file code_303c0_len_3e10.c.
func_80056204()
s32 func_80056204 ()
Definition at line 151 of file code_303c0_len_3e10.c.
func_80056228()
s32 func_80056228 ()
Definition at line 153 of file code_303c0_len_3e10.c.
Referenced by init_demo_data().
func_80056250()
s32 func_80056250 ()
Definition at line 155 of file code_303c0_len_3e10.c.
func_800565A4()
s32 func_800565A4 ()
Definition at line 157 of file code_303c0_len_3e10.c.
alAudioFrame()
Acmd* alAudioFrame (Acmd * cmdList, s32 * cmdLen, s16 * outBuf, s32 outLen)
Definition at line 159 of file code_303c0_len_3e10.c.
func_80056D34()
s32 func_80056D34 ()
Definition at line 161 of file code_303c0_len_3e10.c.
func_80056D44()
s32 func_80056D44 ()
Definition at line 163 of file code_303c0_len_3e10.c.
func_80056D50()
s32 func_80056D50 ()
Definition at line 165 of file code_303c0_len_3e10.c.
func_80056D5C()
s32 func_80056D5C ()
Definition at line 167 of file code_303c0_len_3e10.c.
func_80056D78()
s32 func_80056D78 ()
Definition at line 169 of file code_303c0_len_3e10.c.
func_80056DA4()
s32 func_80056DA4 ()
Definition at line 171 of file code_303c0_len_3e10.c.
func_80056DCC()
s32 func_80056DCC ()
Definition at line 173 of file code_303c0_len_3e10.c.
func_80056E34()
s32 func_80056E34 ()
Definition at line 175 of file code_303c0_len_3e10.c.
func_80056EC0()
s32 func_80056EC0 ()
Definition at line 177 of file code_303c0_len_3e10.c.
func_80056EE8()
s32 func_80056EE8 ()
Definition at line 179 of file code_303c0_len_3e10.c.
func_80056F78()
s32 func_80056F78 ()
Definition at line 181 of file code_303c0_len_3e10.c.
func_80056FA4()
s32 func_80056FA4 ()
Definition at line 183 of file code_303c0_len_3e10.c.
func_80057224()
s32 func_80057224 ()
Definition at line 185 of file code_303c0_len_3e10.c.
func_80057344()
s32 func_80057344 ()
Definition at line 187 of file code_303c0_len_3e10.c.
func_8005736C()
s32 func_8005736C ()
Definition at line 189 of file code_303c0_len_3e10.c.
func_80057548()
s32 func_80057548 ()
Definition at line 191 of file code_303c0_len_3e10.c.
func_800576EC()
s32 func_800576EC ()
Definition at line 193 of file code_303c0_len_3e10.c.
func_80057874()
s32 func_80057874 ()
Definition at line 195 of file code_303c0_len_3e10.c.
func_800579D8()
s32 func_800579D8 ()
Definition at line 197 of file code_303c0_len_3e10.c.
func_80057B64()
s32 func_80057B64 ()
Definition at line 199 of file code_303c0_len_3e10.c.
func_80057B8C()
s32 func_80057B8C ()
Definition at line 201 of file code_303c0_len_3e10.c.
func_80057BB4()
s32 func_80057BB4 ()
Definition at line 203 of file code_303c0_len_3e10.c.
func_80057BDC()
s32 func_80057BDC ()
Definition at line 205 of file code_303c0_len_3e10.c.
func_80057C04()
s32 func_80057C04 ()
Definition at line 207 of file code_303c0_len_3e10.c.
func_80057C2C()
s32 func_80057C2C ()
Definition at line 209 of file code_303c0_len_3e10.c.
func_80057C54()
s32 func_80057C54 ()
Definition at line 211 of file code_303c0_len_3e10.c.
func_80057D0C()
s32 func_80057D0C ()
Definition at line 213 of file code_303c0_len_3e10.c.
func_80057DC8()
s32 func_80057DC8 ()
Definition at line 215 of file code_303c0_len_3e10.c.
func_80057E08()
s32 func_80057E08 ()
Definition at line 217 of file code_303c0_len_3e10.c.
func_80057E5C()
s32 func_80057E5C ()
Definition at line 219 of file code_303c0_len_3e10.c.
func_80057EB0()
s32 func_80057EB0 ()
Definition at line 221 of file code_303c0_len_3e10.c.
func_80057ED0()
s32 func_80057ED0 ()
Definition at line 223 of file code_303c0_len_3e10.c.
func_80057F20()
s32 func_80057F20 ()
Definition at line 225 of file code_303c0_len_3e10.c.
alHeapAlloc()
void alHeapAlloc (u8 * file, s32 line, ALHeap * hp, s32 num, s32 size)
Definition at line 228 of file code_303c0_len_3e10.c.
func_80057FD8()
s32 func_80057FD8 ()
Definition at line 230 of file code_303c0_len_3e10.c.
func_80058004()
s32 func_80058004 ()
Definition at line 232 of file code_303c0_len_3e10.c.
func_80058050()
s32 func_80058050 ()
Definition at line 234 of file code_303c0_len_3e10.c.
func_80058B20()
s32 func_80058B20 ()
Definition at line 236 of file code_303c0_len_3e10.c.
func_80058C6C()
s32 func_80058C6C ()
Definition at line 238 of file code_303c0_len_3e10.c.
Variable Documentation
D_80078DB0
s32 D_80078DB0 extern
Referenced by func_80055050().
D_80078DB4
u16 D_80078DB4 extern
Referenced by func_80055050().