src/code_362a0_len_2f70.c File Reference - Paper Mario Documentation
code_362a0_len_2f70.c File Reference
Functions
s32 allocate_hit_tables ()
void func_8005AF84 (void)
void func_8005AF8C (void)
void initialize_collision (void)
s32 load_hit_asset ()
s32 load_collision ()
s32 load_stage_collision ()
s32 load_hit_data ()
void parent_collider_to_model (s32 colliderID, s16 modelIndex)
s32 _add_hit_vert_to_buffer ()
s32 _get_hit_vert_index_from_buffer (f32 **buffer, f32 *vert, s32 *bufferSize)
void update_collider_transform (s16 colliderID)
s32 get_collider_type_by_id (s32 colliderID)
s32 get_flat_collider_normal ()
void get_collider_center (s32 colliderID, f32 *x, f32 *y, f32 *z)
s32 test_ray_triangle_general ()
s32 test_down_ray_triangle ()
s32 test_up_ray_triangle ()
s32 test_ray_colliders ()
s32 test_ray_zones ()
s32 test_up_ray_collider ()
s32 test_ray_entities ()
s32 func_8005DB00 ()
s32 func_8005DD54 ()
s32 func_8005DDF0 (void)
Variables
s16 D_800D91DC
Function Documentation
allocate_hit_tables()
s32 allocate_hit_tables ()
Definition at line 5 of file code_362a0_len_2f70.c.
func_8005AF84()
void func_8005AF84 (void)
Definition at line 7 of file code_362a0_len_2f70.c.
func_8005AF8C()
void func_8005AF8C (void)
Definition at line 10 of file code_362a0_len_2f70.c.
initialize_collision()
void initialize_collision (void)
Definition at line 13 of file code_362a0_len_2f70.c.
Referenced by step_init_state().
load_hit_asset()
s32 load_hit_asset ()
Definition at line 19 of file code_362a0_len_2f70.c.
load_collision()
s32 load_collision ()
Definition at line 21 of file code_362a0_len_2f70.c.
load_stage_collision()
s32 load_stage_collision ()
Definition at line 23 of file code_362a0_len_2f70.c.
load_hit_data()
s32 load_hit_data ()
Definition at line 25 of file code_362a0_len_2f70.c.
parent_collider_to_model()
void parent_collider_to_model (s32 colliderID, s16 modelIndex)
Definition at line 27 of file code_362a0_len_2f70.c.
Referenced by ParentColliderToModel().
_add_hit_vert_to_buffer()
s32 _add_hit_vert_to_buffer ()
Definition at line 29 of file code_362a0_len_2f70.c.
_get_hit_vert_index_from_buffer()
s32 _get_hit_vert_index_from_buffer (f32 ** buffer, f32 * vert, s32 * bufferSize)
Definition at line 31 of file code_362a0_len_2f70.c.
update_collider_transform()
void update_collider_transform (s16 colliderID)
Definition at line 44 of file code_362a0_len_2f70.c.
Referenced by ParentColliderToModel(), and UpdateColliderTransform().
get_collider_type_by_id()
s32 get_collider_type_by_id (s32 colliderID)
Definition at line 48 of file code_362a0_len_2f70.c.
Referenced by func_800E5098().
get_flat_collider_normal()
s32 get_flat_collider_normal ()
Definition at line 59 of file code_362a0_len_2f70.c.
get_collider_center()
void get_collider_center (s32 colliderID, f32 * x, f32 * y, f32 * z)
Definition at line 61 of file code_362a0_len_2f70.c.
Referenced by func_802405EC_7EB2FC(), GetColliderCenter(), and PlaySoundAtCollider().
test_ray_triangle_general()
s32 test_ray_triangle_general ()
Definition at line 63 of file code_362a0_len_2f70.c.
test_down_ray_triangle()
s32 test_down_ray_triangle ()
Definition at line 65 of file code_362a0_len_2f70.c.
test_up_ray_triangle()
s32 test_up_ray_triangle ()
Definition at line 67 of file code_362a0_len_2f70.c.
test_ray_colliders()
s32 test_ray_colliders ()
Definition at line 69 of file code_362a0_len_2f70.c.
test_ray_zones()
s32 test_ray_zones ()
Definition at line 71 of file code_362a0_len_2f70.c.
test_up_ray_collider()
s32 test_up_ray_collider ()
Definition at line 73 of file code_362a0_len_2f70.c.
test_ray_entities()
s32 test_ray_entities ()
Definition at line 75 of file code_362a0_len_2f70.c.
func_8005DB00()
s32 func_8005DB00 ()
Definition at line 77 of file code_362a0_len_2f70.c.
func_8005DD54()
s32 func_8005DD54 ()
Definition at line 79 of file code_362a0_len_2f70.c.
func_8005DDF0()
s32 func_8005DDF0 (void)
Definition at line 81 of file code_362a0_len_2f70.c.
Variable Documentation
D_800D91DC
s16 D_800D91DC extern
Referenced by initialize_collision().