src/code_cd180_len_38f0.c File Reference - Paper Mario Documentation
code_cd180_len_38f0.c File Reference
Functions
s32 _render_transition_stencil ()
void set_transition_stencil_zoom_0 (s32 arg0, f32 arg1)
void set_transition_stencil_zoom_1 (s32 arg0, f32 arg1)
void func_80137DC0 (s32 arg0, f32 *arg1, f32 *arg2)
s32 set_transition_stencil_color (s32 arg0, u8 arg1, u8 arg2, u8 arg3)
void set_transition_stencil_center (s32 arg0, s32 arg1, s32 arg2, s32 arg3)
s32 set_transition_stencil_center_worldpos ()
s32 set_transition_stencil_alpha ()
s32 clear_transition_stencil ()
s32 func_80138188 ()
void func_80138198 (void)
s32 render_transition_stencil_upper ()
s32 render_transition_stencil_lower ()
s32 set_map_transition_effect ()
s32 func_801382AC ()
s32 func_801385D4 ()
Function Documentation
_render_transition_stencil()
s32 _render_transition_stencil ()
Definition at line 3 of file code_cd180_len_38f0.c.
set_transition_stencil_zoom_0()
void set_transition_stencil_zoom_0 (s32 arg0, f32 arg1)
Definition at line 5 of file code_cd180_len_38f0.c.
Referenced by draw_encounters_post_battle(), func_800355D4(), func_80241AB8(), func_802485FC(), func_80248AA4(), func_80248D78(), func_802D4D14(), func_802D4D88(), init_demo_data(), intro_logos_update_fade(), and state_init_language_select().
set_transition_stencil_zoom_1()
void set_transition_stencil_zoom_1 (s32 arg0, f32 arg1)
Definition at line 7 of file code_cd180_len_38f0.c.
Referenced by begin_state_intro(), func_802405EC_E1EA4C(), func_802A10A4_756824(), func_802D4BDC(), func_802D4C4C(), func_802D4CC4(), func_802D7BA4(), and UnkFunc1().
func_80137DC0()
void func_80137DC0 (s32 arg0, f32 * arg1, f32 * arg2)
Definition at line 9 of file code_cd180_len_38f0.c.
Referenced by func_802537C0(), and func_802D7BA4().
set_transition_stencil_color()
s32 set_transition_stencil_color (s32 arg0, u8 arg1, u8 arg2, u8 arg3)
Definition at line 11 of file code_cd180_len_38f0.c.
Referenced by begin_state_intro(), draw_encounters_post_battle(), func_802405EC_E1EA4C(), func_80241AB8(), func_80248D78(), and intro_logos_update_fade().
set_transition_stencil_center()
void set_transition_stencil_center (s32 arg0, s32 arg1, s32 arg2, s32 arg3)
Definition at line 13 of file code_cd180_len_38f0.c.
Referenced by func_802A10A4_756824(), func_802D4D14(), and func_802D7BA4().
set_transition_stencil_center_worldpos()
s32 set_transition_stencil_center_worldpos ()
Definition at line 15 of file code_cd180_len_38f0.c.
set_transition_stencil_alpha()
s32 set_transition_stencil_alpha ()
Definition at line 17 of file code_cd180_len_38f0.c.
Referenced by func_802405EC_E1EA4C().
clear_transition_stencil()
s32 clear_transition_stencil ()
Definition at line 19 of file code_cd180_len_38f0.c.
Referenced by load_engine_data(), and step_init_state().
func_80138188()
s32 func_80138188 ()
Definition at line 21 of file code_cd180_len_38f0.c.
func_80138198()
void func_80138198 (void)
Definition at line 23 of file code_cd180_len_38f0.c.
Referenced by step_game_loop().
render_transition_stencil_upper()
s32 render_transition_stencil_upper ()
Definition at line 26 of file code_cd180_len_38f0.c.
render_transition_stencil_lower()
s32 render_transition_stencil_lower ()
Definition at line 28 of file code_cd180_len_38f0.c.
set_map_transition_effect()
s32 set_map_transition_effect ()
Definition at line 30 of file code_cd180_len_38f0.c.
Referenced by func_80035660(), func_80035E24(), and init_demo_data().
func_801382AC()
s32 func_801382AC ()
Definition at line 32 of file code_cd180_len_38f0.c.
Referenced by func_80035E54().
func_801385D4()
s32 func_801385D4 ()
Definition at line 34 of file code_cd180_len_38f0.c.