src/code_16c8e0.c File Reference - Paper Mario Documentation
code_16c8e0.c File Reference
Functions
void get_dpad_input_radial (f32 *angle, f32 *magnitude)
void func_8023E104 (void)
void func_8023E11C (void)
s32 initialize_battle ()
void func_8023E3FC (void)
void update_actor_shadows (void)
s32 update_battle_state ()
s32 draw_main_battle_ui ()
s32 func_8023ED5C ()
s32 func_8023F060 ()
s32 func_8023F088 ()
void func_8023FF84 (void)
s32 draw_enemy_health_bars ()
s32 update_starpoints_display ()
s32 func_802409F4 ()
s32 func_80240AA8 ()
void delete_actor (Actor *actor)
void delete_player_actor (Actor *player)
Variables
f32 D_802809F0 = 0.0f
s8 D_802809F4 = 0
s8 D_802809F5 = 0
s16 D_802809F6 = -1
s16 D_802809F8 = 0
u16 D_802809FA = 0
void * D_802809FC []
s32 D_80280A30 = 0xFF
Script BtlPutPartnerAway
Script BtlBringPartnerOut
s8 D_80280CE0 [] = { 0, 0, 0, 0 }
s32 D_80280CE4 = -1
Script D_80280CE8
Script D_80280D04
Script D_80280D20
Script D_80280D3C
Script D_80280D58
Script D_80280D74
Script D_80280D90
Script D_80280DAC
Script D_80280DC8
Script D_80280DE4
Script D_80280E00
Script D_80280E1C
Script D_80280E38
Script D_80280E54
Script D_80280EB8
Function Documentation
get_dpad_input_radial()
void get_dpad_input_radial (f32 * angle, f32 * magnitude)
Definition at line 136 of file code_16c8e0.c.
func_8023E104()
void func_8023E104 (void)
Definition at line 174 of file code_16c8e0.c.
func_8023E11C()
void func_8023E11C (void)
Definition at line 179 of file code_16c8e0.c.
initialize_battle()
s32 initialize_battle ()
Definition at line 184 of file code_16c8e0.c.
Referenced by step_battle().
func_8023E3FC()
void func_8023E3FC (void)
Definition at line 186 of file code_16c8e0.c.
update_actor_shadows()
void update_actor_shadows (void)
Definition at line 189 of file code_16c8e0.c.
update_battle_state()
s32 update_battle_state ()
Definition at line 196 of file code_16c8e0.c.
Referenced by step_battle().
draw_main_battle_ui()
s32 draw_main_battle_ui ()
Definition at line 198 of file code_16c8e0.c.
Referenced by func_80033B54().
func_8023ED5C()
s32 func_8023ED5C ()
Definition at line 200 of file code_16c8e0.c.
func_8023F060()
s32 func_8023F060 ()
Definition at line 202 of file code_16c8e0.c.
func_8023F088()
s32 func_8023F088 ()
Definition at line 204 of file code_16c8e0.c.
func_8023FF84()
void func_8023FF84 (void)
Definition at line 206 of file code_16c8e0.c.
draw_enemy_health_bars()
s32 draw_enemy_health_bars ()
Definition at line 210 of file code_16c8e0.c.
update_starpoints_display()
s32 update_starpoints_display ()
Definition at line 212 of file code_16c8e0.c.
func_802409F4()
s32 func_802409F4 ()
Definition at line 214 of file code_16c8e0.c.
Referenced by step_battle().
func_80240AA8()
s32 func_80240AA8 ()
Definition at line 216 of file code_16c8e0.c.
delete_actor()
void delete_actor (Actor * actor)
Definition at line 218 of file code_16c8e0.c.
Referenced by DeletePartner().
delete_player_actor()
void delete_player_actor (Actor * player)
Definition at line 283 of file code_16c8e0.c.
Variable Documentation
D_802809F0
f32 D_802809F0 = 0.0f
Definition at line 5 of file code_16c8e0.c.
D_802809F4
s8 D_802809F4 = 0
Definition at line 6 of file code_16c8e0.c.
Referenced by func_8023E104(), and func_8023E11C().
D_802809F5
s8 D_802809F5 = 0
Definition at line 7 of file code_16c8e0.c.
Referenced by func_8023E104(), and func_8023E11C().
D_802809F6
s16 D_802809F6 = -1
Definition at line 8 of file code_16c8e0.c.
Referenced by func_80248D78().
D_802809F8
s16 D_802809F8 = 0
Definition at line 9 of file code_16c8e0.c.
Referenced by Set80218630_Var0().
D_802809FA
u16 D_802809FA = 0
Definition at line 10 of file code_16c8e0.c.
D_802809FC
void* D_802809FC[]
Definition at line 12 of file code_16c8e0.c.
D_80280A30
s32 D_80280A30 = 0xFF
Definition at line 16 of file code_16c8e0.c.
Referenced by func_80241AB8(), func_802485FC(), func_80248AA4(), and func_80248D78().
BtlPutPartnerAway
Script BtlPutPartnerAway
Definition at line 18 of file code_16c8e0.c.
BtlBringPartnerOut
Script BtlBringPartnerOut
Definition at line 38 of file code_16c8e0.c.
D_80280CE0
s8 D_80280CE0[] = { 0, 0, 0, 0 }
Definition at line 60 of file code_16c8e0.c.
D_80280CE4
s32 D_80280CE4 = -1
Definition at line 61 of file code_16c8e0.c.
D_80280CE8
Script D_80280CE8
Definition at line 63 of file code_16c8e0.c.
D_80280D04
Script D_80280D04
Definition at line 67 of file code_16c8e0.c.
D_80280D20
Script D_80280D20
Definition at line 71 of file code_16c8e0.c.
D_80280D3C
Script D_80280D3C
Definition at line 75 of file code_16c8e0.c.
D_80280D58
Script D_80280D58
Definition at line 79 of file code_16c8e0.c.
D_80280D74
Script D_80280D74
Definition at line 83 of file code_16c8e0.c.
D_80280D90
Script D_80280D90
Definition at line 87 of file code_16c8e0.c.
D_80280DAC
Script D_80280DAC
Definition at line 91 of file code_16c8e0.c.
D_80280DC8
Script D_80280DC8
Definition at line 95 of file code_16c8e0.c.
D_80280DE4
Script D_80280DE4
Definition at line 99 of file code_16c8e0.c.
D_80280E00
Script D_80280E00
Definition at line 103 of file code_16c8e0.c.
D_80280E1C
Script D_80280E1C
Definition at line 107 of file code_16c8e0.c.
D_80280E38
Script D_80280E38
Definition at line 111 of file code_16c8e0.c.
D_80280E54
Script D_80280E54
Definition at line 115 of file code_16c8e0.c.
D_80280EB8
Script D_80280EB8
Definition at line 122 of file code_16c8e0.c.