src/code_26840_len_20d0.c File Reference - Paper Mario Documentation
code_26840_len_20d0.c File Reference
Functions
void func_8004B440 (SoundManager *manager, u8 arg1, u8 arg2, UnkAl19E0 *arg3, u8 arg4)
void snd_load_sfx_groups_from_SEF (SoundManager *manager)
void snd_clear_sfx_queue (SoundManager *manager)
void snd_enqueue_sfx_event (SoundManager *manager, s32 soundID, s16 volume, s16 pitchShift, u8 pan)
void func_8004B748 (SoundManager *manager)
s32 func_8004B9E4 (SoundManager *manager, s32 arg1)
void func_8004BA54 (SoundManager *manager, s32 arg1)
s32 func_8004BA74 ()
s32 func_8004C0E4 ()
s32 func_8004C268 ()
s32 func_8004C2A4 ()
s32 func_8004C300 ()
void snd_set_modifiers (SoundManager *manager, SoundSFXEntry *sfxEntry)
void snd_set_player_modifiers (SoundManager *manager, SoundSFXEntry *sfxEntry)
s16 func_8004C444 (SoundManager *manager)
s32 func_8004C578 ()
s32 func_8004C844 ()
s32 func_8004C884 ()
s32 func_8004CD94 ()
s32 func_8004CDF8 ()
s32 func_8004CE70 ()
s32 func_8004CEA4 ()
s32 func_8004CEC4 ()
s32 func_8004CF0C ()
s32 func_8004CF3C ()
s32 func_8004D00C ()
s32 func_8004D038 ()
s32 func_8004D050 ()
s32 func_8004D07C ()
s32 func_8004D114 ()
s32 func_8004D130 ()
s32 func_8004D15C ()
s32 func_8004D180 ()
s32 func_8004D1B4 ()
s32 func_8004D23C ()
s32 func_8004D2B0 ()
s32 func_8004D2E4 ()
s32 func_8004D310 ()
void func_8004D31C (void)
s32 func_8004D324 ()
s32 func_8004D33C ()
s32 func_8004D354 ()
s32 func_8004D36C ()
s32 func_8004D3A0 ()
s32 func_8004D3F8 ()
s32 func_8004D428 ()
s32 func_8004D484 ()
s32 func_8004D4BC ()
Function Documentation
func_8004B440()
void func_8004B440 (SoundManager * manager, u8 arg1, u8 arg2, UnkAl19E0 * arg3, u8 arg4)
Definition at line 4 of file code_26840_len_20d0.c.
Referenced by snd_load_audio_data().
snd_load_sfx_groups_from_SEF()
void snd_load_sfx_groups_from_SEF (SoundManager * manager)
Definition at line 86 of file code_26840_len_20d0.c.
Referenced by snd_load_audio_data().
snd_clear_sfx_queue()
void snd_clear_sfx_queue (SoundManager * manager)
Definition at line 88 of file code_26840_len_20d0.c.
Referenced by func_8004B440().
snd_enqueue_sfx_event()
void snd_enqueue_sfx_event (SoundManager * manager, s32 soundID, s16 volume, s16 pitchShift, u8 pan)
Definition at line 105 of file code_26840_len_20d0.c.
Referenced by snd_adjust_sound(), snd_adjust_sound_with_shift(), snd_start_sound(), snd_start_sound_raw(), snd_start_sound_with_shift(), and snd_stop_sound().
func_8004B748()
void func_8004B748 (SoundManager * manager)
Definition at line 131 of file code_26840_len_20d0.c.
Referenced by func_800535C0().
func_8004B9E4()
s32 func_8004B9E4 (SoundManager * manager, s32 arg1)
Definition at line 133 of file code_26840_len_20d0.c.
Referenced by func_8004B440(), and func_80054D74().
func_8004BA54()
void func_8004BA54 (SoundManager * manager, s32 arg1)
Definition at line 153 of file code_26840_len_20d0.c.
Referenced by func_8004B440(), func_80056204(), and func_80056228().
func_8004BA74()
s32 func_8004BA74 ()
Definition at line 161 of file code_26840_len_20d0.c.
func_8004C0E4()
s32 func_8004C0E4 ()
Definition at line 163 of file code_26840_len_20d0.c.
func_8004C268()
s32 func_8004C268 ()
Definition at line 165 of file code_26840_len_20d0.c.
func_8004C2A4()
s32 func_8004C2A4 ()
Definition at line 167 of file code_26840_len_20d0.c.
func_8004C300()
s32 func_8004C300 ()
Definition at line 169 of file code_26840_len_20d0.c.
snd_set_modifiers()
void snd_set_modifiers (SoundManager * manager, SoundSFXEntry * sfxEntry)
Definition at line 171 of file code_26840_len_20d0.c.
snd_set_player_modifiers()
void snd_set_player_modifiers (SoundManager * manager, SoundSFXEntry * sfxEntry)
Definition at line 173 of file code_26840_len_20d0.c.
func_8004C444()
s16 func_8004C444 (SoundManager * manager)
Definition at line 175 of file code_26840_len_20d0.c.
Referenced by snd_update_sequence_players().
func_8004C578()
s32 func_8004C578 ()
Definition at line 177 of file code_26840_len_20d0.c.
func_8004C844()
s32 func_8004C844 ()
Definition at line 179 of file code_26840_len_20d0.c.
func_8004C884()
s32 func_8004C884 ()
Definition at line 181 of file code_26840_len_20d0.c.
func_8004CD94()
s32 func_8004CD94 ()
Definition at line 183 of file code_26840_len_20d0.c.
func_8004CDF8()
s32 func_8004CDF8 ()
Definition at line 185 of file code_26840_len_20d0.c.
func_8004CE70()
s32 func_8004CE70 ()
Definition at line 187 of file code_26840_len_20d0.c.
func_8004CEA4()
s32 func_8004CEA4 ()
Definition at line 189 of file code_26840_len_20d0.c.
func_8004CEC4()
s32 func_8004CEC4 ()
Definition at line 191 of file code_26840_len_20d0.c.
func_8004CF0C()
s32 func_8004CF0C ()
Definition at line 193 of file code_26840_len_20d0.c.
func_8004CF3C()
s32 func_8004CF3C ()
Definition at line 195 of file code_26840_len_20d0.c.
func_8004D00C()
s32 func_8004D00C ()
Definition at line 197 of file code_26840_len_20d0.c.
func_8004D038()
s32 func_8004D038 ()
Definition at line 199 of file code_26840_len_20d0.c.
func_8004D050()
s32 func_8004D050 ()
Definition at line 201 of file code_26840_len_20d0.c.
func_8004D07C()
s32 func_8004D07C ()
Definition at line 203 of file code_26840_len_20d0.c.
func_8004D114()
s32 func_8004D114 ()
Definition at line 205 of file code_26840_len_20d0.c.
func_8004D130()
s32 func_8004D130 ()
Definition at line 207 of file code_26840_len_20d0.c.
func_8004D15C()
s32 func_8004D15C ()
Definition at line 209 of file code_26840_len_20d0.c.
func_8004D180()
s32 func_8004D180 ()
Definition at line 211 of file code_26840_len_20d0.c.
func_8004D1B4()
s32 func_8004D1B4 ()
Definition at line 213 of file code_26840_len_20d0.c.
func_8004D23C()
s32 func_8004D23C ()
Definition at line 215 of file code_26840_len_20d0.c.
func_8004D2B0()
s32 func_8004D2B0 ()
Definition at line 217 of file code_26840_len_20d0.c.
func_8004D2E4()
s32 func_8004D2E4 ()
Definition at line 219 of file code_26840_len_20d0.c.
func_8004D310()
s32 func_8004D310 ()
Definition at line 221 of file code_26840_len_20d0.c.
func_8004D31C()
void func_8004D31C (void)
Definition at line 223 of file code_26840_len_20d0.c.
func_8004D324()
s32 func_8004D324 ()
Definition at line 226 of file code_26840_len_20d0.c.
func_8004D33C()
s32 func_8004D33C ()
Definition at line 228 of file code_26840_len_20d0.c.
func_8004D354()
s32 func_8004D354 ()
Definition at line 230 of file code_26840_len_20d0.c.
func_8004D36C()
s32 func_8004D36C ()
Definition at line 232 of file code_26840_len_20d0.c.
func_8004D3A0()
s32 func_8004D3A0 ()
Definition at line 234 of file code_26840_len_20d0.c.
func_8004D3F8()
s32 func_8004D3F8 ()
Definition at line 236 of file code_26840_len_20d0.c.
func_8004D428()
s32 func_8004D428 ()
Definition at line 238 of file code_26840_len_20d0.c.
func_8004D484()
s32 func_8004D484 ()
Definition at line 240 of file code_26840_len_20d0.c.
func_8004D4BC()
s32 func_8004D4BC ()
Definition at line 242 of file code_26840_len_20d0.c.