src/code_182B30.c File Reference - Paper Mario Documentation
code_182B30.c File Reference
Functions
s32 func_80254250 (void)
void mtx_mirror_y (Matrix4f arg0)
s32 enable_actor_blur ()
s32 disable_actor_blur ()
s32 reset_actor_blur ()
void func_80254610 (Actor *actor)
s32 enable_partner_blur ()
s32 disable_partner_blur ()
s32 reset_partner_blur ()
void func_802546B0 (void)
s32 enable_player_blur ()
void disable_player_blur (void)
void func_80254950 (void)
void func_802549A0 (void)
void func_802549C0 (void)
s32 func_802549F4 ()
s32 func_80254C50 ()
s32 func_802550BC ()
s32 func_802552EC ()
void func_8025593C (s32 arg0)
void func_8025595C (s32 arg0)
void func_8025597C (s32 arg0)
void func_8025599C (s32 arg0)
s32 update_actor_shadow ()
s32 update_enemy_shadows (void)
void update_hero_shadows (void)
void func_80255FD8 (void)
s32 func_80255FE0 ()
s32 func_802571F0 ()
void func_80257B28 (s32 arg0)
void func_80257B48 (s32 arg0)
void func_80257B68 (s32 arg0)
void func_80257B88 (void)
s32 update_player_actor_shadow ()
s32 func_80257DA4 ()
s32 func_80258E14 ()
s32 func_802591EC ()
s32 func_80259494 ()
s32 func_8025950C ()
s32 func_802596C0 ()
s32 func_802597B0 ()
s32 func_8025995C ()
void func_80259A48 (s32 arg0, ActorPart *arg1, s32 arg2, s32 arg3)
s32 func_80259AAC ()
s32 func_80259D9C ()
s32 func_8025A2C4 ()
s32 func_8025A50C ()
s32 func_8025A74C ()
s32 func_8025AA80 ()
s32 func_8025AD90 ()
s32 func_8025B1A8 ()
s32 func_8025B5C0 ()
s32 func_8025BAA0 ()
s32 func_8025C120 ()
s32 func_8025C840 (s32 arg0, ActorPart *arg1)
s32 func_8025C8A0 (s32 arg0, ActorPart *arg1)
s32 func_8025C918 ()
s32 func_8025CCC8 (s32 arg0, ActorPart *arg1)
void func_8025CD28 (s32 arg0, ActorPart *arg1)
s32 func_8025CD40 ()
s32 func_8025CEC8 ()
s32 _remove_part_decoration ()
void func_8025D150 (void)
void func_8025D158 (void)
s32 func_8025D160 ()
s32 func_8025D290 ()
s32 func_8025D2B0 ()
void func_8025D3C4 (void)
s32 func_8025D3CC ()
s32 func_8025D4A0 ()
s32 func_8025D4C8 ()
s32 func_8025D620 ()
s32 func_8025D640 ()
s32 func_8025D6FC ()
s32 func_8025D71C ()
s32 func_8025D810 ()
s32 func_8025D830 ()
s32 func_8025D8EC ()
s32 func_8025D90C ()
void func_8025DA60 (void)
s32 func_8025DA68 ()
void func_8025DBC8 (void)
s32 func_8025DBD0 ()
s32 func_8025DD40 ()
s32 func_8025DD60 ()
s32 func_8025DE88 ()
Function Documentation
func_80254250()
s32 func_80254250 (void)
Definition at line 3 of file code_182B30.c.
mtx_mirror_y()
void mtx_mirror_y (Matrix4f arg0)
Definition at line 19 of file code_182B30.c.
enable_actor_blur()
s32 enable_actor_blur ()
Definition at line 28 of file code_182B30.c.
Referenced by EnableActorBlur().
disable_actor_blur()
s32 disable_actor_blur ()
Definition at line 30 of file code_182B30.c.
Referenced by EnableActorBlur().
reset_actor_blur()
s32 reset_actor_blur ()
Definition at line 32 of file code_182B30.c.
Referenced by EnableActorBlur().
func_80254610()
void func_80254610 (Actor * actor)
Definition at line 34 of file code_182B30.c.
Referenced by func_802546B0(), and func_8027D628().
enable_partner_blur()
s32 enable_partner_blur ()
Definition at line 45 of file code_182B30.c.
Referenced by EnablePartnerBlur().
disable_partner_blur()
s32 disable_partner_blur ()
Definition at line 47 of file code_182B30.c.
Referenced by DisablePartnerBlur().
reset_partner_blur()
s32 reset_partner_blur ()
Definition at line 49 of file code_182B30.c.
func_802546B0()
void func_802546B0 (void)
Definition at line 51 of file code_182B30.c.
enable_player_blur()
s32 enable_player_blur ()
Definition at line 55 of file code_182B30.c.
Referenced by LoadMoveScript().
disable_player_blur()
void disable_player_blur (void)
Definition at line 57 of file code_182B30.c.
func_80254950()
void func_80254950 (void)
Definition at line 68 of file code_182B30.c.
func_802549A0()
void func_802549A0 (void)
Definition at line 81 of file code_182B30.c.
Referenced by func_802749D8().
func_802549C0()
void func_802549C0 (void)
Definition at line 88 of file code_182B30.c.
Referenced by func_802749F8().
func_802549F4()
s32 func_802549F4 ()
Definition at line 97 of file code_182B30.c.
func_80254C50()
s32 func_80254C50 ()
Definition at line 99 of file code_182B30.c.
func_802550BC()
s32 func_802550BC ()
Definition at line 101 of file code_182B30.c.
Referenced by func_8025593C(), and func_8025597C().
func_802552EC()
s32 func_802552EC ()
Definition at line 103 of file code_182B30.c.
Referenced by func_8025595C(), and func_8025599C().
func_8025593C()
void func_8025593C (s32 arg0)
Definition at line 105 of file code_182B30.c.
func_8025595C()
void func_8025595C (s32 arg0)
Definition at line 109 of file code_182B30.c.
func_8025597C()
void func_8025597C (s32 arg0)
Definition at line 113 of file code_182B30.c.
func_8025599C()
void func_8025599C (s32 arg0)
Definition at line 117 of file code_182B30.c.
update_actor_shadow()
s32 update_actor_shadow ()
Definition at line 121 of file code_182B30.c.
Referenced by update_enemy_shadows(), and update_hero_shadows().
update_enemy_shadows()
s32 update_enemy_shadows (void)
Definition at line 123 of file code_182B30.c.
Referenced by update_actor_shadows().
update_hero_shadows()
void update_hero_shadows (void)
Definition at line 132 of file code_182B30.c.
Referenced by update_actor_shadows().
func_80255FD8()
void func_80255FD8 (void)
Definition at line 137 of file code_182B30.c.
func_80255FE0()
s32 func_80255FE0 ()
Definition at line 140 of file code_182B30.c.
Referenced by func_80257B28(), and func_80257B48().
func_802571F0()
s32 func_802571F0 ()
Definition at line 142 of file code_182B30.c.
Referenced by func_80257B68(), and func_80257B88().
func_80257B28()
void func_80257B28 (s32 arg0)
Definition at line 144 of file code_182B30.c.
func_80257B48()
void func_80257B48 (s32 arg0)
Definition at line 148 of file code_182B30.c.
func_80257B68()
void func_80257B68 (s32 arg0)
Definition at line 152 of file code_182B30.c.
func_80257B88()
void func_80257B88 (void)
Definition at line 156 of file code_182B30.c.
update_player_actor_shadow()
s32 update_player_actor_shadow ()
Definition at line 160 of file code_182B30.c.
Referenced by update_hero_shadows().
func_80257DA4()
s32 func_80257DA4 ()
Definition at line 162 of file code_182B30.c.
func_80258E14()
s32 func_80258E14 ()
Definition at line 164 of file code_182B30.c.
func_802591EC()
s32 func_802591EC ()
Definition at line 166 of file code_182B30.c.
func_80259494()
s32 func_80259494 ()
Definition at line 168 of file code_182B30.c.
func_8025950C()
s32 func_8025950C ()
Definition at line 170 of file code_182B30.c.
Referenced by func_80259A48().
func_802596C0()
s32 func_802596C0 ()
Definition at line 172 of file code_182B30.c.
func_802597B0()
s32 func_802597B0 ()
Definition at line 174 of file code_182B30.c.
Referenced by func_80259A48().
func_8025995C()
s32 func_8025995C ()
Definition at line 176 of file code_182B30.c.
func_80259A48()
void func_80259A48 (s32 arg0, ActorPart * arg1, s32 arg2, s32 arg3)
Definition at line 178 of file code_182B30.c.
func_80259AAC()
s32 func_80259AAC ()
Definition at line 194 of file code_182B30.c.
func_80259D9C()
s32 func_80259D9C ()
Definition at line 196 of file code_182B30.c.
func_8025A2C4()
s32 func_8025A2C4 ()
Definition at line 198 of file code_182B30.c.
func_8025A50C()
s32 func_8025A50C ()
Definition at line 200 of file code_182B30.c.
func_8025A74C()
s32 func_8025A74C ()
Definition at line 202 of file code_182B30.c.
func_8025AA80()
s32 func_8025AA80 ()
Definition at line 204 of file code_182B30.c.
func_8025AD90()
s32 func_8025AD90 ()
Definition at line 206 of file code_182B30.c.
func_8025B1A8()
s32 func_8025B1A8 ()
Definition at line 208 of file code_182B30.c.
func_8025B5C0()
s32 func_8025B5C0 ()
Definition at line 210 of file code_182B30.c.
func_8025BAA0()
s32 func_8025BAA0 ()
Definition at line 212 of file code_182B30.c.
func_8025C120()
s32 func_8025C120 ()
Definition at line 214 of file code_182B30.c.
func_8025C840()
s32 func_8025C840 (s32 arg0, ActorPart * arg1)
Definition at line 216 of file code_182B30.c.
func_8025C8A0()
s32 func_8025C8A0 (s32 arg0, ActorPart * arg1)
Definition at line 231 of file code_182B30.c.
Referenced by func_8025C840().
func_8025C918()
s32 func_8025C918 ()
Definition at line 242 of file code_182B30.c.
Referenced by func_8025C840().
func_8025CCC8()
s32 func_8025CCC8 (s32 arg0, ActorPart * arg1)
Definition at line 244 of file code_182B30.c.
func_8025CD28()
void func_8025CD28 (s32 arg0, ActorPart * arg1)
Definition at line 259 of file code_182B30.c.
Referenced by func_8025CCC8().
func_8025CD40()
s32 func_8025CD40 ()
Definition at line 268 of file code_182B30.c.
Referenced by func_8025CCC8().
func_8025CEC8()
s32 func_8025CEC8 ()
Definition at line 270 of file code_182B30.c.
Referenced by add_part_decoration().
_remove_part_decoration()
s32 _remove_part_decoration ()
Definition at line 272 of file code_182B30.c.
Referenced by add_part_decoration(), and remove_part_decoration().
func_8025D150()
void func_8025D150 (void)
Definition at line 274 of file code_182B30.c.
func_8025D158()
void func_8025D158 (void)
Definition at line 277 of file code_182B30.c.
func_8025D160()
s32 func_8025D160 ()
Definition at line 280 of file code_182B30.c.
func_8025D290()
s32 func_8025D290 ()
Definition at line 282 of file code_182B30.c.
func_8025D2B0()
s32 func_8025D2B0 ()
Definition at line 284 of file code_182B30.c.
func_8025D3C4()
void func_8025D3C4 (void)
Definition at line 286 of file code_182B30.c.
func_8025D3CC()
s32 func_8025D3CC ()
Definition at line 289 of file code_182B30.c.
func_8025D4A0()
s32 func_8025D4A0 ()
Definition at line 291 of file code_182B30.c.
func_8025D4C8()
s32 func_8025D4C8 ()
Definition at line 293 of file code_182B30.c.
func_8025D620()
s32 func_8025D620 ()
Definition at line 295 of file code_182B30.c.
func_8025D640()
s32 func_8025D640 ()
Definition at line 297 of file code_182B30.c.
func_8025D6FC()
s32 func_8025D6FC ()
Definition at line 299 of file code_182B30.c.
func_8025D71C()
s32 func_8025D71C ()
Definition at line 301 of file code_182B30.c.
func_8025D810()
s32 func_8025D810 ()
Definition at line 303 of file code_182B30.c.
func_8025D830()
s32 func_8025D830 ()
Definition at line 305 of file code_182B30.c.
func_8025D8EC()
s32 func_8025D8EC ()
Definition at line 307 of file code_182B30.c.
func_8025D90C()
s32 func_8025D90C ()
Definition at line 309 of file code_182B30.c.
func_8025DA60()
void func_8025DA60 (void)
Definition at line 311 of file code_182B30.c.
func_8025DA68()
s32 func_8025DA68 ()
Definition at line 314 of file code_182B30.c.
func_8025DBC8()
void func_8025DBC8 (void)
Definition at line 316 of file code_182B30.c.
func_8025DBD0()
s32 func_8025DBD0 ()
Definition at line 319 of file code_182B30.c.
func_8025DD40()
s32 func_8025DD40 ()
Definition at line 321 of file code_182B30.c.
func_8025DD60()
s32 func_8025DD60 ()
Definition at line 323 of file code_182B30.c.
func_8025DE88()
s32 func_8025DE88 ()
Definition at line 325 of file code_182B30.c.