src/code_1a1f0_len_5390.c File Reference - Paper Mario Documentation
code_1a1f0_len_5390.c File Reference
Functions
s32 get_defeated (s32 mapID, s32 encounterID)
void set_defeated (s32 mapID, s32 encounterID)
ApiStatus ShowMerleeCoinMessage (ScriptInstance *script, s32 isInitialCall)
ApiStatus ShowMerleeRanOutMessage (ScriptInstance *script, s32 isInitialCall)
ApiStatus FadeBackgroundToBlack (ScriptInstance *script, s32 isInitialCall)
ApiStatus UnfadeBackgroundFromBlack (ScriptInstance *script, s32 isInitialCall)
ApiStatus FadeInMerlee (ScriptInstance *script, s32 isInitialCall)
ApiStatus FadeOutMerlee (ScriptInstance *script, s32 isInitialCall)
s32 MerleeUpdateFX ()
ApiStatus MerleeStopFX (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamLookAtObjVector (ScriptInstance *script, s32 isInitialCall)
ApiStatus HasMerleeCasts (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlayMerleeGatherFX (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlayMerleeOrbFX (ScriptInstance *script, s32 isInitialCall)
ApiStatus OnDefeatEnemy (ScriptInstance *script, s32 isInitialCall)
ApiStatus OnFleeBattleDrops (ScriptInstance *script, s32 isInitialCall)
s32 update_encounters_neutral ()
Default/neutral state during world gameplay; checks for player-enemy collisions and initiates battles when they occur.
void draw_encounters_neutral ()
s32 update_encounters_pre_battle ()
s32 draw_encounters_pre_battle ()
s32 show_first_strike_message ()
s32 update_encounters_post_battle ()
s32 draw_encounters_post_battle (void)
void update_encounters_conversation (void)
void draw_encounters_conversation ()
s32 check_conversation_trigger ()
s32 create_encounters ()
void init_encounters_ui ()
s32 is_starting_conversation (void)
Function Documentation
get_defeated()
s32 get_defeated (s32 mapID, s32 encounterID)
Definition at line 4 of file code_1a1f0_len_5390.c.
set_defeated()
void set_defeated (s32 mapID, s32 encounterID)
Definition at line 12 of file code_1a1f0_len_5390.c.
ShowMerleeCoinMessage()
ApiStatus ShowMerleeCoinMessage (ScriptInstance * script, s32 isInitialCall)
Definition at line 31 of file code_1a1f0_len_5390.c.
ShowMerleeRanOutMessage()
ApiStatus ShowMerleeRanOutMessage (ScriptInstance * script, s32 isInitialCall)
Definition at line 38 of file code_1a1f0_len_5390.c.
FadeBackgroundToBlack()
ApiStatus FadeBackgroundToBlack (ScriptInstance * script, s32 isInitialCall)
Definition at line 45 of file code_1a1f0_len_5390.c.
UnfadeBackgroundFromBlack()
ApiStatus UnfadeBackgroundFromBlack (ScriptInstance * script, s32 isInitialCall)
Definition at line 59 of file code_1a1f0_len_5390.c.
FadeInMerlee()
ApiStatus FadeInMerlee (ScriptInstance * script, s32 isInitialCall)
Definition at line 75 of file code_1a1f0_len_5390.c.
FadeOutMerlee()
ApiStatus FadeOutMerlee (ScriptInstance * script, s32 isInitialCall)
Definition at line 92 of file code_1a1f0_len_5390.c.
MerleeUpdateFX()
s32 MerleeUpdateFX ()
Definition at line 104 of file code_1a1f0_len_5390.c.
MerleeStopFX()
ApiStatus MerleeStopFX (ScriptInstance * script, s32 isInitialCall)
Definition at line 106 of file code_1a1f0_len_5390.c.
GetCamLookAtObjVector()
ApiStatus GetCamLookAtObjVector (ScriptInstance * script, s32 isInitialCall)
Definition at line 111 of file code_1a1f0_len_5390.c.
HasMerleeCasts()
ApiStatus HasMerleeCasts (ScriptInstance * script, s32 isInitialCall)
Definition at line 119 of file code_1a1f0_len_5390.c.
PlayMerleeGatherFX()
ApiStatus PlayMerleeGatherFX (ScriptInstance * script, s32 isInitialCall)
Definition at line 128 of file code_1a1f0_len_5390.c.
PlayMerleeOrbFX()
ApiStatus PlayMerleeOrbFX (ScriptInstance * script, s32 isInitialCall)
Definition at line 138 of file code_1a1f0_len_5390.c.
OnDefeatEnemy()
ApiStatus OnDefeatEnemy (ScriptInstance * script, s32 isInitialCall)
Definition at line 148 of file code_1a1f0_len_5390.c.
OnFleeBattleDrops()
ApiStatus OnFleeBattleDrops (ScriptInstance * script, s32 isInitialCall)
Definition at line 187 of file code_1a1f0_len_5390.c.
update_encounters_neutral()
s32 update_encounters_neutral ()
Default/neutral state during world gameplay; checks for player-enemy collisions and initiates battles when they occur.
Definition at line 213 of file code_1a1f0_len_5390.c.
Referenced by update_counters().
draw_encounters_neutral()
void draw_encounters_neutral ()
Definition at line 215 of file code_1a1f0_len_5390.c.
Referenced by draw_encounter_ui().
update_encounters_pre_battle()
s32 update_encounters_pre_battle ()
Definition at line 218 of file code_1a1f0_len_5390.c.
Referenced by update_counters().
draw_encounters_pre_battle()
s32 draw_encounters_pre_battle ()
Definition at line 220 of file code_1a1f0_len_5390.c.
Referenced by draw_encounter_ui().
show_first_strike_message()
s32 show_first_strike_message ()
Definition at line 222 of file code_1a1f0_len_5390.c.
Referenced by draw_first_strike_ui().
update_encounters_post_battle()
s32 update_encounters_post_battle ()
Definition at line 224 of file code_1a1f0_len_5390.c.
Referenced by update_counters().
draw_encounters_post_battle()
s32 draw_encounters_post_battle (void)
Definition at line 226 of file code_1a1f0_len_5390.c.
Referenced by draw_encounter_ui().
update_encounters_conversation()
void update_encounters_conversation (void)
Definition at line 238 of file code_1a1f0_len_5390.c.
Referenced by update_counters().
draw_encounters_conversation()
void draw_encounters_conversation ()
Definition at line 294 of file code_1a1f0_len_5390.c.
Referenced by draw_encounter_ui().
check_conversation_trigger()
s32 check_conversation_trigger ()
Definition at line 297 of file code_1a1f0_len_5390.c.
create_encounters()
s32 create_encounters ()
Definition at line 299 of file code_1a1f0_len_5390.c.
Referenced by update_counters().
init_encounters_ui()
void init_encounters_ui ()
Definition at line 301 of file code_1a1f0_len_5390.c.
Referenced by draw_encounter_ui().
is_starting_conversation()
s32 is_starting_conversation (void)
Definition at line 304 of file code_1a1f0_len_5390.c.
Referenced by IsStartingConversation(), and partner_use_ability().