src/code_341d0.c File Reference - Paper Mario Documentation
code_341d0.c File Reference
Macros
#define EFFECT_LOADED 1
Typedefs
typedef s32 TlbEntry[0x1000/4]
typedef TlbEntry TlbMappablePage[15]
Functions
s32 func_80058DD0 ()
s32 func_80058E84 ()
s32 func_80058F88 ()
s32 func_80059008 ()
s32 func_8005904C ()
s32 func_80059310 ()
s32 func_800598A0 ()
s32 func_80059AB8 ()
s32 func_80059BD4 ()
void stub_effect_delegate (EffectInstance *effectInst)
Used for unbound function points in effect structs.
s32 set_effect_pos_offset ()
s32 clear_effect_data ()
void func_80059D48 (void)
s32 update_effects ()
s32 render_effects (void)
s32 func_80059F94 ()
EffectInstance * func_8005A2BC (EffectBlueprint *effectBp)
void remove_effect (EffectInstance *arg0)
void remove_all_effects (void)
s32 load_effect (s32 effectIndex)
Variables
TlbMappablePage D_80197000
EffectTableEntry gEffectTable [135]
EffectInstance * D_800B4398 [96]
Effect D_800A4000 [15]
void * D_80059C80
Macro Definition Documentation
EFFECT_LOADED
#define EFFECT_LOADED 1
Definition at line 9 of file code_341d0.c.
Typedef Documentation
TlbEntry
typedef s32 TlbEntry[0x1000/4]
Definition at line 3 of file code_341d0.c.
TlbMappablePage
typedef TlbEntry TlbMappablePage[15]
Definition at line 4 of file code_341d0.c.
Function Documentation
func_80058DD0()
s32 func_80058DD0 ()
Definition at line 15 of file code_341d0.c.
func_80058E84()
s32 func_80058E84 ()
Definition at line 17 of file code_341d0.c.
func_80058F88()
s32 func_80058F88 ()
Definition at line 19 of file code_341d0.c.
func_80059008()
s32 func_80059008 ()
Definition at line 21 of file code_341d0.c.
func_8005904C()
s32 func_8005904C ()
Definition at line 23 of file code_341d0.c.
Referenced by func_80056DCC().
func_80059310()
s32 func_80059310 ()
Definition at line 25 of file code_341d0.c.
func_800598A0()
s32 func_800598A0 ()
Definition at line 27 of file code_341d0.c.
func_80059AB8()
s32 func_80059AB8 ()
Definition at line 29 of file code_341d0.c.
func_80059BD4()
s32 func_80059BD4 ()
Definition at line 31 of file code_341d0.c.
stub_effect_delegate()
void stub_effect_delegate (EffectInstance * effectInst)
Used for unbound function points in effect structs.
Definition at line 34 of file code_341d0.c.
Referenced by func_8005A2BC().
set_effect_pos_offset()
s32 set_effect_pos_offset ()
Definition at line 37 of file code_341d0.c.
clear_effect_data()
s32 clear_effect_data ()
Definition at line 39 of file code_341d0.c.
Referenced by load_engine_data(), and step_init_state().
func_80059D48()
void func_80059D48 (void)
Definition at line 41 of file code_341d0.c.
update_effects()
s32 update_effects ()
Definition at line 44 of file code_341d0.c.
Referenced by step_battle(), and step_world().
render_effects()
s32 render_effects (void)
Definition at line 46 of file code_341d0.c.
func_80059F94()
s32 func_80059F94 ()
Definition at line 64 of file code_341d0.c.
func_8005A2BC()
EffectInstance* func_8005A2BC (EffectBlueprint * effectBp)
Definition at line 66 of file code_341d0.c.
remove_effect()
void remove_effect (EffectInstance * arg0)
Definition at line 130 of file code_341d0.c.
Referenced by delete_actor(), delete_player_actor(), remove_player_buffs(), and RemoveEffect().
remove_all_effects()
void remove_all_effects (void)
Definition at line 153 of file code_341d0.c.
load_effect()
s32 load_effect (s32 effectIndex)
Definition at line 169 of file code_341d0.c.
Variable Documentation
D_80197000
TlbMappablePage D_80197000 extern
Referenced by load_effect().
gEffectTable
EffectTableEntry gEffectTable[135] extern
Referenced by load_effect().
D_800B4398
EffectInstance* D_800B4398[96] extern
Referenced by func_8005A2BC(), remove_all_effects(), remove_effect(), and render_effects().
D_800A4000
Effect D_800A4000[15] extern
Referenced by func_8005A2BC(), and load_effect().
D_80059C80
void* D_80059C80 extern