src/code_759b0_len_61b0.c File Reference - Paper Mario Documentation
code_759b0_len_61b0.c File Reference
Functions
s32 func_800DC500 ()
s32 func_800DC778 ()
s32 func_800DCB7C (s32 arg0, f32 *arg1, f32 *arg2, f32 *arg3, f32 *arg4)
s32 func_800DCE70 ()
s32 func_800DD04C ()
s32 func_800DD228 ()
s32 func_800DD44C ()
void func_800DD5B4 (f32 *arg0, f32 *arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5)
s32 func_800DD618 ()
s32 func_800DD8FC ()
s32 func_800DDAE4 ()
s32 func_800DDC44 (s32 arg0, f32 *arg1, f32 *arg2, f32 *arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7)
s32 func_800DDCEC ()
s32 func_800DDD94 ()
s32 test_below_player ()
s32 func_800DE46C ()
s32 trace_below_player ()
s32 collision_check_above ()
s32 trace_above_player ()
s32 do_lateral_collision ()
s32 func_800DEE5C ()
s32 func_800DF15C ()
void func_800DF3FC (f32 *arg0, f32 *arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5)
s32 test_player_lateral ()
s32 update_player ()
s32 check_input_use_partner ()
s32 func_800DFAAC ()
void func_800DFBE8 (void)
void clear_player_status (void)
void func_800DFC74 (void)
s32 func_800DFCF4 (void)
s32 func_800DFD48 ()
void func_800DFEFC (void)
void func_800DFF50 (s32 arg0)
void func_800DFF78 (void)
s32 func_800DFFCC ()
f32 func_800E0088 (f32 x, f32 z)
void enable_player_shadow (void)
void disable_player_shadow (void)
s32 disable_player_static_collisions (void)
s32 enable_player_static_collisions (void)
s32 disable_player_input (void)
s32 enable_player_input (void)
void func_800E01DC (void)
s32 func_800E0208 (void)
void func_800E0260 (void)
s32 func_800E0294 ()
void func_800E0330 (void)
void func_800E0374 (void)
s32 func_800E0398 ()
void func_800E04D0 (void)
void func_800E0514 (void)
s32 func_800E0538 (void)
s32 func_800E0580 ()
void func_800E0658 (void)
void func_800E069C (void)
void func_800E06C0 (s32 arg0)
s32 func_800E06D8 ()
s32 func_800E0818 ()
void func_800E0AD0 (void)
void func_800E0B14 (void)
void func_800E0B38 (void)
s32 func_800E0B90 ()
s32 func_800E0FEC ()
void render_player (void)
void render_player_model ()
s32 appendGfx_player ()
s32 appendGfx_player_spin ()
s32 update_player_shadow ()
s32 update_player_input ()
s32 func_800E205C ()
void func_800E22E4 (s32 *arg0)
s32 input_to_move_vector ()
s32 func_800E23FC ()
s32 func_800E24F8 ()
Variables
s32 D_8010C920
s32 D_8010C93C
s32 D_8010C940
s32 D_8010C950
s32 D_8010C958
Function Documentation
func_800DC500()
s32 func_800DC500 ()
Definition at line 9 of file code_759b0_len_61b0.c.
func_800DC778()
s32 func_800DC778 ()
Definition at line 11 of file code_759b0_len_61b0.c.
func_800DCB7C()
s32 func_800DCB7C (s32 arg0, f32 * arg1, f32 * arg2, f32 * arg3, f32 * arg4)
Definition at line 13 of file code_759b0_len_61b0.c.
Referenced by func_80045900().
func_800DCE70()
s32 func_800DCE70 ()
Definition at line 15 of file code_759b0_len_61b0.c.
func_800DD04C()
s32 func_800DD04C ()
Definition at line 17 of file code_759b0_len_61b0.c.
func_800DD228()
s32 func_800DD228 ()
Definition at line 19 of file code_759b0_len_61b0.c.
func_800DD44C()
s32 func_800DD44C ()
Definition at line 21 of file code_759b0_len_61b0.c.
func_800DD5B4()
void func_800DD5B4 (f32 * arg0, f32 * arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5)
Definition at line 23 of file code_759b0_len_61b0.c.
func_800DD618()
s32 func_800DD618 ()
Definition at line 30 of file code_759b0_len_61b0.c.
func_800DD8FC()
s32 func_800DD8FC ()
Definition at line 32 of file code_759b0_len_61b0.c.
func_800DDAE4()
s32 func_800DDAE4 ()
Definition at line 34 of file code_759b0_len_61b0.c.
func_800DDC44()
s32 func_800DDC44 (s32 arg0, f32 * arg1, f32 * arg2, f32 * arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7)
Definition at line 37 of file code_759b0_len_61b0.c.
Referenced by UnkNpcAIFunc12().
func_800DDCEC()
s32 func_800DDCEC ()
Definition at line 39 of file code_759b0_len_61b0.c.
func_800DDD94()
s32 func_800DDD94 ()
Definition at line 41 of file code_759b0_len_61b0.c.
test_below_player()
s32 test_below_player ()
Definition at line 43 of file code_759b0_len_61b0.c.
func_800DE46C()
s32 func_800DE46C ()
Definition at line 45 of file code_759b0_len_61b0.c.
trace_below_player()
s32 trace_below_player ()
Definition at line 47 of file code_759b0_len_61b0.c.
collision_check_above()
s32 collision_check_above ()
Definition at line 49 of file code_759b0_len_61b0.c.
trace_above_player()
s32 trace_above_player ()
Definition at line 51 of file code_759b0_len_61b0.c.
do_lateral_collision()
s32 do_lateral_collision ()
Definition at line 53 of file code_759b0_len_61b0.c.
func_800DEE5C()
s32 func_800DEE5C ()
Definition at line 55 of file code_759b0_len_61b0.c.
func_800DF15C()
s32 func_800DF15C ()
Definition at line 57 of file code_759b0_len_61b0.c.
func_800DF3FC()
void func_800DF3FC (f32 * arg0, f32 * arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5)
Definition at line 59 of file code_759b0_len_61b0.c.
test_player_lateral()
s32 test_player_lateral ()
Definition at line 66 of file code_759b0_len_61b0.c.
update_player()
s32 update_player ()
Definition at line 68 of file code_759b0_len_61b0.c.
Referenced by step_world().
check_input_use_partner()
s32 check_input_use_partner ()
Definition at line 70 of file code_759b0_len_61b0.c.
func_800DFAAC()
s32 func_800DFAAC ()
Definition at line 72 of file code_759b0_len_61b0.c.
func_800DFBE8()
void func_800DFBE8 (void)
Definition at line 74 of file code_759b0_len_61b0.c.
clear_player_status()
void clear_player_status (void)
Definition at line 88 of file code_759b0_len_61b0.c.
Referenced by step_init_state().
func_800DFC74()
void func_800DFC74 (void)
Definition at line 92 of file code_759b0_len_61b0.c.
func_800DFCF4()
s32 func_800DFCF4 (void)
Definition at line 108 of file code_759b0_len_61b0.c.
func_800DFD48()
s32 func_800DFD48 ()
Definition at line 116 of file code_759b0_len_61b0.c.
Referenced by func_800DFEFC(), and func_800DFF78().
func_800DFEFC()
void func_800DFEFC (void)
Definition at line 118 of file code_759b0_len_61b0.c.
func_800DFF50()
void func_800DFF50 (s32 arg0)
Definition at line 129 of file code_759b0_len_61b0.c.
func_800DFF78()
void func_800DFF78 (void)
Definition at line 137 of file code_759b0_len_61b0.c.
func_800DFFCC()
s32 func_800DFFCC ()
Definition at line 148 of file code_759b0_len_61b0.c.
func_800E0088()
f32 func_800E0088 (f32 x, f32 z)
Definition at line 151 of file code_759b0_len_61b0.c.
Referenced by func_802401B0_8C8140().
enable_player_shadow()
void enable_player_shadow (void)
Definition at line 157 of file code_759b0_len_61b0.c.
Referenced by HidePlayerShadow().
disable_player_shadow()
void disable_player_shadow (void)
Definition at line 161 of file code_759b0_len_61b0.c.
Referenced by HidePlayerShadow(), and player_enter_blue_pipe().
disable_player_static_collisions()
s32 disable_player_static_collisions (void)
Definition at line 165 of file code_759b0_len_61b0.c.
Referenced by DisablePlayerPhysics().
enable_player_static_collisions()
s32 enable_player_static_collisions (void)
Definition at line 173 of file code_759b0_len_61b0.c.
Referenced by DisablePlayerPhysics(), and func_802D6954().
disable_player_input()
s32 disable_player_input (void)
Definition at line 183 of file code_759b0_len_61b0.c.
Referenced by DisablePlayerInput().
enable_player_input()
s32 enable_player_input (void)
Definition at line 191 of file code_759b0_len_61b0.c.
Referenced by DisablePlayerInput(), func_802D6954(), set_action_state(), and world_goombario_pre_battle().
func_800E01DC()
void func_800E01DC (void)
Definition at line 201 of file code_759b0_len_61b0.c.
Referenced by DisablePlayerInput().
func_800E0208()
s32 func_800E0208 (void)
Definition at line 209 of file code_759b0_len_61b0.c.
Referenced by func_800E34D8().
func_800E0260()
void func_800E0260 (void)
Definition at line 222 of file code_759b0_len_61b0.c.
func_800E0294()
s32 func_800E0294 ()
Definition at line 229 of file code_759b0_len_61b0.c.
func_800E0330()
void func_800E0330 (void)
Definition at line 231 of file code_759b0_len_61b0.c.
Referenced by func_800E0260().
func_800E0374()
void func_800E0374 (void)
Definition at line 237 of file code_759b0_len_61b0.c.
Referenced by func_800DFC74().
func_800E0398()
s32 func_800E0398 ()
Definition at line 242 of file code_759b0_len_61b0.c.
func_800E04D0()
void func_800E04D0 (void)
Definition at line 244 of file code_759b0_len_61b0.c.
Referenced by func_800E0260().
func_800E0514()
void func_800E0514 (void)
Definition at line 250 of file code_759b0_len_61b0.c.
Referenced by func_800DFC74().
func_800E0538()
s32 func_800E0538 (void)
Definition at line 255 of file code_759b0_len_61b0.c.
func_800E0580()
s32 func_800E0580 ()
Definition at line 268 of file code_759b0_len_61b0.c.
func_800E0658()
void func_800E0658 (void)
Definition at line 270 of file code_759b0_len_61b0.c.
Referenced by func_800E0260().
func_800E069C()
void func_800E069C (void)
Definition at line 276 of file code_759b0_len_61b0.c.
Referenced by func_800DFC74().
func_800E06C0()
void func_800E06C0 (s32 arg0)
Definition at line 281 of file code_759b0_len_61b0.c.
func_800E06D8()
s32 func_800E06D8 ()
Definition at line 285 of file code_759b0_len_61b0.c.
func_800E0818()
s32 func_800E0818 ()
Definition at line 287 of file code_759b0_len_61b0.c.
func_800E0AD0()
void func_800E0AD0 (void)
Definition at line 289 of file code_759b0_len_61b0.c.
Referenced by func_800E0260().
func_800E0B14()
void func_800E0B14 (void)
Definition at line 295 of file code_759b0_len_61b0.c.
Referenced by func_800DFC74().
func_800E0B38()
void func_800E0B38 (void)
Definition at line 300 of file code_759b0_len_61b0.c.
func_800E0B90()
s32 func_800E0B90 ()
Definition at line 314 of file code_759b0_len_61b0.c.
func_800E0FEC()
s32 func_800E0FEC ()
Definition at line 316 of file code_759b0_len_61b0.c.
render_player()
void render_player (void)
Definition at line 318 of file code_759b0_len_61b0.c.
render_player_model()
void render_player_model ()
Definition at line 324 of file code_759b0_len_61b0.c.
Referenced by render_player().
appendGfx_player()
s32 appendGfx_player ()
Definition at line 326 of file code_759b0_len_61b0.c.
appendGfx_player_spin()
s32 appendGfx_player_spin ()
Definition at line 328 of file code_759b0_len_61b0.c.
update_player_shadow()
s32 update_player_shadow ()
Definition at line 330 of file code_759b0_len_61b0.c.
update_player_input()
s32 update_player_input ()
Definition at line 332 of file code_759b0_len_61b0.c.
func_800E205C()
s32 func_800E205C ()
Definition at line 334 of file code_759b0_len_61b0.c.
Referenced by func_800DFC74().
func_800E22E4()
void func_800E22E4 (s32 * arg0)
Definition at line 336 of file code_759b0_len_61b0.c.
input_to_move_vector()
s32 input_to_move_vector ()
Definition at line 342 of file code_759b0_len_61b0.c.
func_800E23FC()
s32 func_800E23FC ()
Definition at line 344 of file code_759b0_len_61b0.c.
func_800E24F8()
s32 func_800E24F8 ()
Definition at line 346 of file code_759b0_len_61b0.c.
Variable Documentation
D_8010C920
s32 D_8010C920 extern
Referenced by func_800E04D0(), and func_800E0514().
D_8010C93C
s32 D_8010C93C extern
Referenced by func_800E0330(), and func_800E0374().
D_8010C940
s32 D_8010C940 extern
Referenced by func_800E0658(), and func_800E069C().
D_8010C950
s32 D_8010C950 extern
Referenced by func_800E06C0().
D_8010C958
s32 D_8010C958 extern
Referenced by func_800E0AD0(), and func_800E0B14().