src/code_F5750.c File Reference - Paper Mario Documentation
code_F5750.c File Reference
Data Structures
struct UnkF5750
Typedefs
typedef UnkF5750 * UnkF5750List[0x40]
Functions
ApiStatus HidePlayerShadow (ScriptInstance *script, s32 isInitialCall)
ApiStatus DisablePlayerPhysics (ScriptInstance *script, s32 isInitialCall)
ApiStatus DisablePlayerInput (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerCollisionSize (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerSpeed (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerJumpscale (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerActionState (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerAnimationSpeed (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlayerMoveTo (ScriptInstance *script, s32 isInitialCall)
s32 func_802D1270 ()
s32 func_802D1380 ()
s32 player_jump ()
void PlayerJump (ScriptInstance *script, s32 isInitialCall)
void PlayerJump1 (ScriptInstance *script, s32 isInitialCall)
void PlayerJump2 (ScriptInstance *script, s32 isInitialCall)
ApiStatus InterpPlayerYaw (ScriptInstance *script, s32 isInitialCall)
s32 PlayerFaceNpc (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPlayerTargetYaw (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerFlagBits (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPlayerActionState (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPlayerPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPlayerAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus FullyRestoreHPandFP (ScriptInstance *script, s32 isInitialCall)
ApiStatus FullyRestoreSP (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnablePartner (ScriptInstance *script, s32 isInitialCall)
ApiStatus DisablePartner (ScriptInstance *script, s32 isInitialCall)
s32 UseEntryHeading ()
ApiStatus func_802D2148 (ScriptInstance *script, s32 isInitialCall)
s32 UseExitHeading ()
s32 func_802D23F8 ()
ApiStatus WaitForPlayerTouchingFloor (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D2484 (ScriptInstance *script, s32 isInitialCall)
ApiStatus IsPlayerOnValidFloor (ScriptInstance *script, s32 isInitialCall)
ApiStatus WaitForPlayerMoveToComplete (ScriptInstance *script, s32 isInitialCall)
ApiStatus WaitForPlayerInputEnabled (ScriptInstance *script, s32 isInitialCall)
s32 func_802D2520 ()
ApiStatus func_802D286C (ScriptInstance *script, s32 isInitialCall)
s32 func_802D2884 ()
ApiStatus DisablePulseStone (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCurrentPartner (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D2B50 (void)
ApiStatus func_802D2B6C (ScriptInstance *script, s32 isInitialCall)
ApiStatus Disable8bitMario (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D2C14 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D2C40 (ScriptInstance *script)
ApiStatus PlaySoundAtPlayer (ScriptInstance *script, s32 isInitialCall)
s32 func_802D2D30 ()
s32 func_802D2ED4 ()
s32 func_802D2F34 ()
s32 func_802D2FCC ()
s32 func_802D3028 ()
s32 func_802D31E0 ()
s32 func_802D3398 ()
s32 func_802D33D4 ()
ApiStatus func_802D3474 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D354C (ScriptInstance *script, s32 isInitialCall)
s32 func_802D3624 ()
s32 func_802D3674 ()
s32 func_802D36E0 ()
s32 func_802D378C ()
s32 func_802D3840 ()
s32 func_802D38EC ()
s32 func_802D3998 ()
s32 func_802D39FC ()
s32 func_802D3A60 ()
s32 func_802D3C58 ()
s32 func_802D3EB8 ()
s32 func_802D3F74 ()
s32 func_802D3FC8 ()
s32 func_802D4050 ()
UnkF5750 * func_802D4164 (s32 index)
s32 func_802D417C ()
s32 func_802D420C ()
s32 func_802D42AC ()
s32 func_802D4364 ()
void func_802D43AC (s32 index, f32 arg1, f32 arg2, f32 arg3)
void func_802D43D0 (s32 index, s32 arg1, s32 arg2, s32 arg3)
s32 func_802D43F4 ()
s32 func_802D4434 ()
s32 func_802D4488 ()
s32 func_802D4560 ()
Variables
s16 D_802DB5B0
UnkF5750List * D_802DB7C0
Typedef Documentation
UnkF5750List
typedef UnkF5750* UnkF5750List[0x40]
Definition at line 16 of file code_F5750.c.
Function Documentation
HidePlayerShadow()
ApiStatus HidePlayerShadow (ScriptInstance * script, s32 isInitialCall)
Definition at line 21 of file code_F5750.c.
Referenced by N().
DisablePlayerPhysics()
ApiStatus DisablePlayerPhysics (ScriptInstance * script, s32 isInitialCall)
Definition at line 33 of file code_F5750.c.
Referenced by N().
DisablePlayerInput()
ApiStatus DisablePlayerInput (ScriptInstance * script, s32 isInitialCall)
Definition at line 45 of file code_F5750.c.
Referenced by N().
SetPlayerPos()
ApiStatus SetPlayerPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 69 of file code_F5750.c.
Referenced by N().
SetPlayerCollisionSize()
ApiStatus SetPlayerCollisionSize (ScriptInstance * script, s32 isInitialCall)
Definition at line 87 of file code_F5750.c.
SetPlayerSpeed()
ApiStatus SetPlayerSpeed (ScriptInstance * script, s32 isInitialCall)
Definition at line 103 of file code_F5750.c.
Referenced by N().
SetPlayerJumpscale()
ApiStatus SetPlayerJumpscale (ScriptInstance * script, s32 isInitialCall)
Definition at line 108 of file code_F5750.c.
Referenced by N().
SetPlayerAnimation()
ApiStatus SetPlayerAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 114 of file code_F5750.c.
Referenced by N().
SetPlayerActionState()
ApiStatus SetPlayerActionState (ScriptInstance * script, s32 isInitialCall)
Definition at line 133 of file code_F5750.c.
SetPlayerAnimationSpeed()
ApiStatus SetPlayerAnimationSpeed (ScriptInstance * script, s32 isInitialCall)
Definition at line 138 of file code_F5750.c.
PlayerMoveTo()
ApiStatus PlayerMoveTo (ScriptInstance * script, s32 isInitialCall)
Definition at line 143 of file code_F5750.c.
Referenced by N().
func_802D1270()
s32 func_802D1270 ()
Definition at line 170 of file code_F5750.c.
func_802D1380()
s32 func_802D1380 ()
Definition at line 172 of file code_F5750.c.
player_jump()
s32 player_jump ()
Definition at line 174 of file code_F5750.c.
Referenced by PlayerJump(), PlayerJump1(), and PlayerJump2().
PlayerJump()
void PlayerJump (ScriptInstance * script, s32 isInitialCall)
Definition at line 176 of file code_F5750.c.
Referenced by N().
PlayerJump1()
void PlayerJump1 (ScriptInstance * script, s32 isInitialCall)
Definition at line 180 of file code_F5750.c.
PlayerJump2()
void PlayerJump2 (ScriptInstance * script, s32 isInitialCall)
Definition at line 184 of file code_F5750.c.
InterpPlayerYaw()
ApiStatus InterpPlayerYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 188 of file code_F5750.c.
Referenced by N().
PlayerFaceNpc()
s32 PlayerFaceNpc (ScriptInstance * script, s32 isInitialCall)
Definition at line 232 of file code_F5750.c.
Referenced by N().
GetPlayerTargetYaw()
ApiStatus GetPlayerTargetYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 234 of file code_F5750.c.
SetPlayerFlagBits()
ApiStatus SetPlayerFlagBits (ScriptInstance * script, s32 isInitialCall)
Definition at line 239 of file code_F5750.c.
GetPlayerActionState()
ApiStatus GetPlayerActionState (ScriptInstance * script, s32 isInitialCall)
Definition at line 255 of file code_F5750.c.
GetPlayerPos()
ApiStatus GetPlayerPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 261 of file code_F5750.c.
Referenced by N().
GetPlayerAnimation()
ApiStatus GetPlayerAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 274 of file code_F5750.c.
FullyRestoreHPandFP()
ApiStatus FullyRestoreHPandFP (ScriptInstance * script, s32 isInitialCall)
Definition at line 281 of file code_F5750.c.
FullyRestoreSP()
ApiStatus FullyRestoreSP (ScriptInstance * script, s32 isInitialCall)
Definition at line 289 of file code_F5750.c.
EnablePartner()
ApiStatus EnablePartner (ScriptInstance * script, s32 isInitialCall)
Definition at line 296 of file code_F5750.c.
DisablePartner()
ApiStatus DisablePartner (ScriptInstance * script, s32 isInitialCall)
Definition at line 304 of file code_F5750.c.
UseEntryHeading()
s32 UseEntryHeading ()
Definition at line 312 of file code_F5750.c.
func_802D2148()
ApiStatus func_802D2148 (ScriptInstance * script, s32 isInitialCall)
Definition at line 314 of file code_F5750.c.
UseExitHeading()
s32 UseExitHeading ()
Definition at line 319 of file code_F5750.c.
Referenced by N().
func_802D23F8()
s32 func_802D23F8 ()
Definition at line 321 of file code_F5750.c.
Referenced by IsPlayerOnValidFloor(), and WaitForPlayerTouchingFloor().
WaitForPlayerTouchingFloor()
ApiStatus WaitForPlayerTouchingFloor (ScriptInstance * script, s32 isInitialCall)
Definition at line 323 of file code_F5750.c.
func_802D2484()
ApiStatus func_802D2484 (ScriptInstance * script, s32 isInitialCall)
Definition at line 331 of file code_F5750.c.
IsPlayerOnValidFloor()
ApiStatus IsPlayerOnValidFloor (ScriptInstance * script, s32 isInitialCall)
Definition at line 335 of file code_F5750.c.
WaitForPlayerMoveToComplete()
ApiStatus WaitForPlayerMoveToComplete (ScriptInstance * script, s32 isInitialCall)
Definition at line 347 of file code_F5750.c.
WaitForPlayerInputEnabled()
ApiStatus WaitForPlayerInputEnabled (ScriptInstance * script, s32 isInitialCall)
Definition at line 351 of file code_F5750.c.
func_802D2520()
s32 func_802D2520 ()
Definition at line 355 of file code_F5750.c.
func_802D286C()
ApiStatus func_802D286C (ScriptInstance * script, s32 isInitialCall)
Definition at line 357 of file code_F5750.c.
func_802D2884()
s32 func_802D2884 ()
Definition at line 364 of file code_F5750.c.
DisablePulseStone()
ApiStatus DisablePulseStone (ScriptInstance * script, s32 isInitialCall)
Definition at line 366 of file code_F5750.c.
GetCurrentPartner()
ApiStatus GetCurrentPartner (ScriptInstance * script, s32 isInitialCall)
Definition at line 379 of file code_F5750.c.
func_802D2B50()
ApiStatus func_802D2B50 (void)
Definition at line 393 of file code_F5750.c.
func_802D2B6C()
ApiStatus func_802D2B6C (ScriptInstance * script, s32 isInitialCall)
Definition at line 400 of file code_F5750.c.
Disable8bitMario()
ApiStatus Disable8bitMario (ScriptInstance * script, s32 isInitialCall)
Definition at line 407 of file code_F5750.c.
func_802D2C14()
ApiStatus func_802D2C14 (ScriptInstance * script, s32 isInitialCall)
Definition at line 425 of file code_F5750.c.
func_802D2C40()
ApiStatus func_802D2C40 (ScriptInstance * script)
Definition at line 430 of file code_F5750.c.
PlaySoundAtPlayer()
ApiStatus PlaySoundAtPlayer (ScriptInstance * script, s32 isInitialCall)
Definition at line 444 of file code_F5750.c.
Referenced by N().
func_802D2D30()
s32 func_802D2D30 ()
Definition at line 453 of file code_F5750.c.
func_802D2ED4()
s32 func_802D2ED4 ()
Definition at line 455 of file code_F5750.c.
func_802D2F34()
s32 func_802D2F34 ()
Definition at line 457 of file code_F5750.c.
func_802D2FCC()
s32 func_802D2FCC ()
Definition at line 459 of file code_F5750.c.
func_802D3028()
s32 func_802D3028 ()
Definition at line 461 of file code_F5750.c.
func_802D31E0()
s32 func_802D31E0 ()
Definition at line 463 of file code_F5750.c.
func_802D3398()
s32 func_802D3398 ()
Definition at line 465 of file code_F5750.c.
func_802D33D4()
s32 func_802D33D4 ()
Definition at line 467 of file code_F5750.c.
func_802D3474()
ApiStatus func_802D3474 (ScriptInstance * script, s32 isInitialCall)
Definition at line 469 of file code_F5750.c.
Referenced by N().
func_802D354C()
ApiStatus func_802D354C (ScriptInstance * script, s32 isInitialCall)
Definition at line 504 of file code_F5750.c.
func_802D3624()
s32 func_802D3624 ()
Definition at line 539 of file code_F5750.c.
Referenced by N().
func_802D3674()
s32 func_802D3674 ()
Definition at line 541 of file code_F5750.c.
func_802D36E0()
s32 func_802D36E0 ()
Definition at line 543 of file code_F5750.c.
Referenced by N().
func_802D378C()
s32 func_802D378C ()
Definition at line 545 of file code_F5750.c.
func_802D3840()
s32 func_802D3840 ()
Definition at line 547 of file code_F5750.c.
Referenced by N().
func_802D38EC()
s32 func_802D38EC ()
Definition at line 549 of file code_F5750.c.
Referenced by N().
func_802D3998()
s32 func_802D3998 ()
Definition at line 551 of file code_F5750.c.
func_802D39FC()
s32 func_802D39FC ()
Definition at line 553 of file code_F5750.c.
Referenced by N().
func_802D3A60()
s32 func_802D3A60 ()
Definition at line 555 of file code_F5750.c.
func_802D3C58()
s32 func_802D3C58 ()
Definition at line 557 of file code_F5750.c.
Referenced by N().
func_802D3EB8()
s32 func_802D3EB8 ()
Definition at line 559 of file code_F5750.c.
func_802D3F74()
s32 func_802D3F74 ()
Definition at line 561 of file code_F5750.c.
func_802D3FC8()
s32 func_802D3FC8 ()
Definition at line 563 of file code_F5750.c.
func_802D4050()
s32 func_802D4050 ()
Definition at line 565 of file code_F5750.c.
func_802D4164()
UnkF5750* func_802D4164 (s32 index)
Definition at line 567 of file code_F5750.c.
func_802D417C()
s32 func_802D417C ()
Definition at line 571 of file code_F5750.c.
func_802D420C()
s32 func_802D420C ()
Definition at line 573 of file code_F5750.c.
func_802D42AC()
s32 func_802D42AC ()
Definition at line 575 of file code_F5750.c.
func_802D4364()
s32 func_802D4364 ()
Definition at line 577 of file code_F5750.c.
func_802D43AC()
void func_802D43AC (s32 index, f32 arg1, f32 arg2, f32 arg3)
Definition at line 579 of file code_F5750.c.
func_802D43D0()
void func_802D43D0 (s32 index, s32 arg1, s32 arg2, s32 arg3)
Definition at line 587 of file code_F5750.c.
func_802D43F4()
s32 func_802D43F4 ()
Definition at line 595 of file code_F5750.c.
func_802D4434()
s32 func_802D4434 ()
Definition at line 597 of file code_F5750.c.
func_802D4488()
s32 func_802D4488 ()
Definition at line 599 of file code_F5750.c.
Referenced by clear_script_list().
func_802D4560()
s32 func_802D4560 ()
Definition at line 601 of file code_F5750.c.
Referenced by init_script_list().
Variable Documentation
D_802DB5B0
s16 D_802DB5B0 extern
Referenced by func_802D286C().
D_802DB7C0
UnkF5750List* D_802DB7C0 extern
Referenced by func_802D3474(), func_802D354C(), and func_802D4164().