src/code_b72b0_len_15ed0.c File Reference - Paper Mario Documentation
code_b72b0_len_15ed0.c File Reference
Functions
s32 clear_virtual_models ()
s32 init_virtual_models ()
s32 load_virtual_model ()
s32 func_80120DE4 ()
s32 func_80120F04 ()
s32 func_80120FB8 ()
s32 func_80121140 ()
s32 func_80121184 ()
s32 func_80121CE8 ()
s32 func_80121EB8 ()
s32 func_80122088 ()
s32 func_80122188 ()
s32 func_80122288 ()
s32 func_80122D7C ()
s32 func_80122DDC ()
s32 func_80122DFC ()
s32 func_80122E94 ()
s32 func_80122EE8 ()
s32 func_80122F24 ()
s32 func_80122F64 ()
s32 func_80122F8C ()
s32 func_80122FB8 ()
s32 enable_entity_fog ()
s32 disable_entity_fog ()
s32 set_entity_fog_dist ()
s32 set_entity_fog_color ()
s32 is_entity_fog_enabled ()
s32 get_entity_fog_distance ()
s32 get_entity_fog_color ()
void stub_dynamic_entity_delegate (void)
s32 clear_dynamic_entity_list ()
s32 init_dynamic_entity_list ()
s32 bind_dynamic_entity_3 ()
s32 bind_dynamic_entity_7 ()
s32 bind_dynamic_entity_B ()
s32 update_dynamic_entities ()
s32 render_dynamic_entities ()
s32 func_801234E0 ()
s32 func_80123550 ()
s32 func_801235C0 ()
s32 get_dynamic_entity ()
s32 clear_character_set ()
s32 clear_printers ()
s32 load_font_data ()
s32 load_font ()
s32 update_messages ()
s32 _update_message ()
s32 render_messages ()
s32 func_80124434 ()
s32 func_80124570 ()
s32 initialize_printer ()
s32 dma_load_string ()
s32 load_message_to_buffer ()
PrintContext * load_string (s32 stringId, s32 *a1)
s32 _load_string ()
s32 load_message_to_printer ()
s32 clamp_printer_coords ()
s32 cancel_message ()
s32 set_message_images ()
s32 set_message_string ()
s32 set_message_value ()
s32 close_message ()
s32 func_80125C84 ()
s32 get_char_width ()
s32 get_string_properties ()
s32 get_string_width ()
s32 func_801264B0 ()
s32 draw_string ()
s32 func_80126790 ()
s32 func_80126EAC ()
s32 func_80126F78 ()
s32 draw_digit ()
s32 draw_number ()
s32 func_80127B70 ()
s32 func_80127BA4 ()
s32 func_80127D90 ()
s32 func_8012C2E0 ()
s32 func_8012C324 ()
s32 func_8012C9A8 ()
s32 func_8012CA08 ()
s32 _draw_message_box ()
s32 func_8012D3DC ()
s32 func_8012DB58 ()
s32 func_8012E8E0 ()
s32 func_8012E9A0 ()
s32 func_8012EC94 ()
s32 func_8012F500 ()
s32 func_8012FE10 ()
s32 func_8012FE78 ()
s32 func_801309F0 ()
s32 func_80130A04 ()
s32 func_80130ACC ()
s32 draw_coin_sparkles ()
ItemEntity * get_item_entity (s32 itemEntityIndex)
s32 func_80130F70 ()
s32 func_80130FAC ()
s32 clear_item_entity_data ()
s32 init_item_entity_list ()
s32 func_80131128 ()
s32 make_item_entity ()
s32 make_item_entity_nodelay (s32 itemID, f32 x, f32 y, f32 z, ItemSpawnMode itemSpawnMode, s32 pickupVar)
void make_item_entity_delayed (s32 itemID, f32 x, f32 y, f32 z, s32 unk1, s32 unk2, s32 unk3)
s32 init_got_item ()
s32 func_80131DD4 ()
s32 update_item_entities ()
s32 appendGfx_item_entity ()
s32 draw_item_entities ()
s32 func_80132D94 ()
s32 render_item_entities ()
s32 remove_item_entity_by_reference ()
s32 remove_item_entity_by_index ()
s32 func_80133A94 ()
s32 test_item_player_collision ()
s32 func_80133FC8 ()
void set_item_entity_flags (s32 itemEntityIndex, s32 flag)
s32 clear_item_entity_flags ()
s32 func_801341B0 ()
s32 func_801341E8 ()
void set_item_entity_position (s32 itemEntityIndex, f32 x, f32 y, f32 z)
s32 func_80134230 ()
s32 func_80134240 ()
s32 update_item_entity_collectable ()
s32 func_8013559C ()
s32 update_item_entity_static ()
void func_801356C4 (void)
void func_801356CC (void)
void func_801356D4 (void)
s32 update_item_entity_temp ()
s32 func_801363A0 ()
s32 func_8013673C ()
s32 func_801369D0 ()
s32 func_80136A08 ()
Function Documentation
clear_virtual_models()
s32 clear_virtual_models ()
Definition at line 3 of file code_b72b0_len_15ed0.c.
Referenced by step_init_state().
init_virtual_models()
s32 init_virtual_models ()
Definition at line 5 of file code_b72b0_len_15ed0.c.
load_virtual_model()
s32 load_virtual_model ()
Definition at line 7 of file code_b72b0_len_15ed0.c.
func_80120DE4()
s32 func_80120DE4 ()
Definition at line 9 of file code_b72b0_len_15ed0.c.
func_80120F04()
s32 func_80120F04 ()
Definition at line 11 of file code_b72b0_len_15ed0.c.
func_80120FB8()
s32 func_80120FB8 ()
Definition at line 13 of file code_b72b0_len_15ed0.c.
func_80121140()
s32 func_80121140 ()
Definition at line 15 of file code_b72b0_len_15ed0.c.
func_80121184()
s32 func_80121184 ()
Definition at line 17 of file code_b72b0_len_15ed0.c.
func_80121CE8()
s32 func_80121CE8 ()
Definition at line 19 of file code_b72b0_len_15ed0.c.
func_80121EB8()
s32 func_80121EB8 ()
Definition at line 21 of file code_b72b0_len_15ed0.c.
func_80122088()
s32 func_80122088 ()
Definition at line 23 of file code_b72b0_len_15ed0.c.
func_80122188()
s32 func_80122188 ()
Definition at line 25 of file code_b72b0_len_15ed0.c.
func_80122288()
s32 func_80122288 ()
Definition at line 27 of file code_b72b0_len_15ed0.c.
func_80122D7C()
s32 func_80122D7C ()
Definition at line 29 of file code_b72b0_len_15ed0.c.
func_80122DDC()
s32 func_80122DDC ()
Definition at line 31 of file code_b72b0_len_15ed0.c.
func_80122DFC()
s32 func_80122DFC ()
Definition at line 33 of file code_b72b0_len_15ed0.c.
func_80122E94()
s32 func_80122E94 ()
Definition at line 35 of file code_b72b0_len_15ed0.c.
func_80122EE8()
s32 func_80122EE8 ()
Definition at line 37 of file code_b72b0_len_15ed0.c.
func_80122F24()
s32 func_80122F24 ()
Definition at line 39 of file code_b72b0_len_15ed0.c.
func_80122F64()
s32 func_80122F64 ()
Definition at line 41 of file code_b72b0_len_15ed0.c.
func_80122F8C()
s32 func_80122F8C ()
Definition at line 43 of file code_b72b0_len_15ed0.c.
func_80122FB8()
s32 func_80122FB8 ()
Definition at line 45 of file code_b72b0_len_15ed0.c.
enable_entity_fog()
s32 enable_entity_fog ()
Definition at line 47 of file code_b72b0_len_15ed0.c.
disable_entity_fog()
s32 disable_entity_fog ()
Definition at line 49 of file code_b72b0_len_15ed0.c.
set_entity_fog_dist()
s32 set_entity_fog_dist ()
Definition at line 51 of file code_b72b0_len_15ed0.c.
set_entity_fog_color()
s32 set_entity_fog_color ()
Definition at line 53 of file code_b72b0_len_15ed0.c.
is_entity_fog_enabled()
s32 is_entity_fog_enabled ()
Definition at line 55 of file code_b72b0_len_15ed0.c.
get_entity_fog_distance()
s32 get_entity_fog_distance ()
Definition at line 57 of file code_b72b0_len_15ed0.c.
get_entity_fog_color()
s32 get_entity_fog_color ()
Definition at line 59 of file code_b72b0_len_15ed0.c.
stub_dynamic_entity_delegate()
void stub_dynamic_entity_delegate (void)
Definition at line 61 of file code_b72b0_len_15ed0.c.
clear_dynamic_entity_list()
s32 clear_dynamic_entity_list ()
Definition at line 64 of file code_b72b0_len_15ed0.c.
Referenced by step_init_state().
init_dynamic_entity_list()
s32 init_dynamic_entity_list ()
Definition at line 66 of file code_b72b0_len_15ed0.c.
bind_dynamic_entity_3()
s32 bind_dynamic_entity_3 ()
Definition at line 68 of file code_b72b0_len_15ed0.c.
bind_dynamic_entity_7()
s32 bind_dynamic_entity_7 ()
Definition at line 70 of file code_b72b0_len_15ed0.c.
bind_dynamic_entity_B()
s32 bind_dynamic_entity_B ()
Definition at line 72 of file code_b72b0_len_15ed0.c.
update_dynamic_entities()
s32 update_dynamic_entities ()
Definition at line 74 of file code_b72b0_len_15ed0.c.
render_dynamic_entities()
s32 render_dynamic_entities ()
Definition at line 76 of file code_b72b0_len_15ed0.c.
func_801234E0()
s32 func_801234E0 ()
Definition at line 78 of file code_b72b0_len_15ed0.c.
func_80123550()
s32 func_80123550 ()
Definition at line 80 of file code_b72b0_len_15ed0.c.
func_801235C0()
s32 func_801235C0 ()
Definition at line 82 of file code_b72b0_len_15ed0.c.
Referenced by func_80241CC8_8D31D8().
get_dynamic_entity()
s32 get_dynamic_entity ()
Definition at line 84 of file code_b72b0_len_15ed0.c.
clear_character_set()
s32 clear_character_set ()
Definition at line 86 of file code_b72b0_len_15ed0.c.
clear_printers()
s32 clear_printers ()
Definition at line 88 of file code_b72b0_len_15ed0.c.
Referenced by step_init_state().
load_font_data()
s32 load_font_data ()
Definition at line 90 of file code_b72b0_len_15ed0.c.
load_font()
s32 load_font ()
Definition at line 92 of file code_b72b0_len_15ed0.c.
update_messages()
s32 update_messages ()
Definition at line 94 of file code_b72b0_len_15ed0.c.
_update_message()
s32 _update_message ()
Definition at line 96 of file code_b72b0_len_15ed0.c.
render_messages()
s32 render_messages ()
Definition at line 98 of file code_b72b0_len_15ed0.c.
func_80124434()
s32 func_80124434 ()
Definition at line 100 of file code_b72b0_len_15ed0.c.
func_80124570()
s32 func_80124570 ()
Definition at line 102 of file code_b72b0_len_15ed0.c.
initialize_printer()
s32 initialize_printer ()
Definition at line 104 of file code_b72b0_len_15ed0.c.
dma_load_string()
s32 dma_load_string ()
Definition at line 106 of file code_b72b0_len_15ed0.c.
load_message_to_buffer()
s32 load_message_to_buffer ()
Definition at line 108 of file code_b72b0_len_15ed0.c.
load_string()
PrintContext* load_string (s32 stringId, s32 * a1)
Definition at line 110 of file code_b72b0_len_15ed0.c.
Referenced by ActorSpeak().
_load_string()
s32 _load_string ()
Definition at line 112 of file code_b72b0_len_15ed0.c.
load_message_to_printer()
s32 load_message_to_printer ()
Definition at line 114 of file code_b72b0_len_15ed0.c.
Referenced by SwitchMessage().
clamp_printer_coords()
s32 clamp_printer_coords ()
Definition at line 116 of file code_b72b0_len_15ed0.c.
cancel_message()
s32 cancel_message ()
Definition at line 118 of file code_b72b0_len_15ed0.c.
Referenced by CancelMessage(), and CancelMessageAndBlock().
set_message_images()
s32 set_message_images ()
Definition at line 120 of file code_b72b0_len_15ed0.c.
Referenced by SetMessageImages().
set_message_string()
s32 set_message_string ()
Definition at line 122 of file code_b72b0_len_15ed0.c.
Referenced by SetMessageString().
set_message_value()
s32 set_message_value ()
Definition at line 124 of file code_b72b0_len_15ed0.c.
Referenced by SetMessageValue().
close_message()
s32 close_message ()
Definition at line 126 of file code_b72b0_len_15ed0.c.
Referenced by CloseChoice(), and CloseMessage().
func_80125C84()
s32 func_80125C84 ()
Definition at line 128 of file code_b72b0_len_15ed0.c.
get_char_width()
s32 get_char_width ()
Definition at line 130 of file code_b72b0_len_15ed0.c.
get_string_properties()
s32 get_string_properties ()
Definition at line 132 of file code_b72b0_len_15ed0.c.
get_string_width()
s32 get_string_width ()
Definition at line 134 of file code_b72b0_len_15ed0.c.
func_801264B0()
s32 func_801264B0 ()
Definition at line 136 of file code_b72b0_len_15ed0.c.
draw_string()
s32 draw_string ()
Definition at line 138 of file code_b72b0_len_15ed0.c.
func_80126790()
s32 func_80126790 ()
Definition at line 140 of file code_b72b0_len_15ed0.c.
func_80126EAC()
s32 func_80126EAC ()
Definition at line 142 of file code_b72b0_len_15ed0.c.
func_80126F78()
s32 func_80126F78 ()
Definition at line 144 of file code_b72b0_len_15ed0.c.
draw_digit()
s32 draw_digit ()
Definition at line 146 of file code_b72b0_len_15ed0.c.
draw_number()
s32 draw_number ()
Definition at line 148 of file code_b72b0_len_15ed0.c.
Referenced by coin_counter_draw_content().
func_80127B70()
s32 func_80127B70 ()
Definition at line 150 of file code_b72b0_len_15ed0.c.
func_80127BA4()
s32 func_80127BA4 ()
Definition at line 152 of file code_b72b0_len_15ed0.c.
func_80127D90()
s32 func_80127D90 ()
Definition at line 154 of file code_b72b0_len_15ed0.c.
func_8012C2E0()
s32 func_8012C2E0 ()
Definition at line 156 of file code_b72b0_len_15ed0.c.
func_8012C324()
s32 func_8012C324 ()
Definition at line 158 of file code_b72b0_len_15ed0.c.
func_8012C9A8()
s32 func_8012C9A8 ()
Definition at line 160 of file code_b72b0_len_15ed0.c.
func_8012CA08()
s32 func_8012CA08 ()
Definition at line 162 of file code_b72b0_len_15ed0.c.
_draw_message_box()
s32 _draw_message_box ()
Definition at line 164 of file code_b72b0_len_15ed0.c.
func_8012D3DC()
s32 func_8012D3DC ()
Definition at line 166 of file code_b72b0_len_15ed0.c.
func_8012DB58()
s32 func_8012DB58 ()
Definition at line 168 of file code_b72b0_len_15ed0.c.
func_8012E8E0()
s32 func_8012E8E0 ()
Definition at line 170 of file code_b72b0_len_15ed0.c.
func_8012E9A0()
s32 func_8012E9A0 ()
Definition at line 172 of file code_b72b0_len_15ed0.c.
func_8012EC94()
s32 func_8012EC94 ()
Definition at line 174 of file code_b72b0_len_15ed0.c.
func_8012F500()
s32 func_8012F500 ()
Definition at line 176 of file code_b72b0_len_15ed0.c.
func_8012FE10()
s32 func_8012FE10 ()
Definition at line 178 of file code_b72b0_len_15ed0.c.
func_8012FE78()
s32 func_8012FE78 ()
Definition at line 180 of file code_b72b0_len_15ed0.c.
func_801309F0()
s32 func_801309F0 ()
Definition at line 182 of file code_b72b0_len_15ed0.c.
func_80130A04()
s32 func_80130A04 ()
Definition at line 184 of file code_b72b0_len_15ed0.c.
func_80130ACC()
s32 func_80130ACC ()
Definition at line 186 of file code_b72b0_len_15ed0.c.
draw_coin_sparkles()
s32 draw_coin_sparkles ()
Definition at line 188 of file code_b72b0_len_15ed0.c.
get_item_entity()
ItemEntity* get_item_entity (s32 itemEntityIndex)
Definition at line 190 of file code_b72b0_len_15ed0.c.
Referenced by func_802D721C(), SetItemFlags(), SetItemPos(), ShowGotItem(), and SomeItemEntityFunc().
func_80130F70()
s32 func_80130F70 ()
Definition at line 192 of file code_b72b0_len_15ed0.c.
func_80130FAC()
s32 func_80130FAC ()
Definition at line 194 of file code_b72b0_len_15ed0.c.
clear_item_entity_data()
s32 clear_item_entity_data ()
Definition at line 196 of file code_b72b0_len_15ed0.c.
Referenced by step_init_state().
init_item_entity_list()
s32 init_item_entity_list ()
Definition at line 198 of file code_b72b0_len_15ed0.c.
func_80131128()
s32 func_80131128 ()
Definition at line 200 of file code_b72b0_len_15ed0.c.
make_item_entity()
s32 make_item_entity ()
Definition at line 202 of file code_b72b0_len_15ed0.c.
make_item_entity_nodelay()
s32 make_item_entity_nodelay (s32 itemID, f32 x, f32 y, f32 z, ItemSpawnMode itemSpawnMode, s32 pickupVar)
Definition at line 205 of file code_b72b0_len_15ed0.c.
Referenced by DropItemEntity(), DropItemEntityB(), and MakeItemEntity().
make_item_entity_delayed()
void make_item_entity_delayed (s32 itemID, f32 x, f32 y, f32 z, s32 unk1, s32 unk2, s32 unk3)
Definition at line 209 of file code_b72b0_len_15ed0.c.
Referenced by OnFleeBattleDrops().
init_got_item()
s32 init_got_item ()
Definition at line 211 of file code_b72b0_len_15ed0.c.
Referenced by ShowGotItem().
func_80131DD4()
s32 func_80131DD4 ()
Definition at line 213 of file code_b72b0_len_15ed0.c.
update_item_entities()
s32 update_item_entities ()
Definition at line 215 of file code_b72b0_len_15ed0.c.
Referenced by step_world().
appendGfx_item_entity()
s32 appendGfx_item_entity ()
Definition at line 217 of file code_b72b0_len_15ed0.c.
draw_item_entities()
s32 draw_item_entities ()
Definition at line 219 of file code_b72b0_len_15ed0.c.
func_80132D94()
s32 func_80132D94 ()
Definition at line 221 of file code_b72b0_len_15ed0.c.
render_item_entities()
s32 render_item_entities ()
Definition at line 223 of file code_b72b0_len_15ed0.c.
remove_item_entity_by_reference()
s32 remove_item_entity_by_reference ()
Definition at line 225 of file code_b72b0_len_15ed0.c.
remove_item_entity_by_index()
s32 remove_item_entity_by_index ()
Definition at line 227 of file code_b72b0_len_15ed0.c.
Referenced by RemoveItemEntity().
func_80133A94()
s32 func_80133A94 ()
Definition at line 229 of file code_b72b0_len_15ed0.c.
test_item_player_collision()
s32 test_item_player_collision ()
Definition at line 231 of file code_b72b0_len_15ed0.c.
func_80133FC8()
s32 func_80133FC8 ()
Definition at line 233 of file code_b72b0_len_15ed0.c.
set_item_entity_flags()
void set_item_entity_flags (s32 itemEntityIndex, s32 flag)
Definition at line 235 of file code_b72b0_len_15ed0.c.
Referenced by DropItemEntityB(), func_80240000_800880(), and func_80240044_8008C4().
clear_item_entity_flags()
s32 clear_item_entity_flags ()
Definition at line 237 of file code_b72b0_len_15ed0.c.
func_801341B0()
s32 func_801341B0 ()
Definition at line 239 of file code_b72b0_len_15ed0.c.
func_801341E8()
s32 func_801341E8 ()
Definition at line 241 of file code_b72b0_len_15ed0.c.
set_item_entity_position()
void set_item_entity_position (s32 itemEntityIndex, f32 x, f32 y, f32 z)
Definition at line 243 of file code_b72b0_len_15ed0.c.
Referenced by Bandit_DropCoin().
func_80134230()
s32 func_80134230 ()
Definition at line 245 of file code_b72b0_len_15ed0.c.
Referenced by func_80282774(), and func_802827A8().
func_80134240()
s32 func_80134240 ()
Definition at line 247 of file code_b72b0_len_15ed0.c.
Referenced by func_80282774().
update_item_entity_collectable()
s32 update_item_entity_collectable ()
Definition at line 249 of file code_b72b0_len_15ed0.c.
func_8013559C()
s32 func_8013559C ()
Definition at line 251 of file code_b72b0_len_15ed0.c.
update_item_entity_static()
s32 update_item_entity_static ()
Definition at line 253 of file code_b72b0_len_15ed0.c.
func_801356C4()
void func_801356C4 (void)
Definition at line 255 of file code_b72b0_len_15ed0.c.
func_801356CC()
void func_801356CC (void)
Definition at line 258 of file code_b72b0_len_15ed0.c.
func_801356D4()
void func_801356D4 (void)
Definition at line 261 of file code_b72b0_len_15ed0.c.
update_item_entity_temp()
s32 update_item_entity_temp ()
Definition at line 264 of file code_b72b0_len_15ed0.c.
func_801363A0()
s32 func_801363A0 ()
Definition at line 266 of file code_b72b0_len_15ed0.c.
func_8013673C()
s32 func_8013673C ()
Definition at line 268 of file code_b72b0_len_15ed0.c.
func_801369D0()
s32 func_801369D0 ()
Definition at line 270 of file code_b72b0_len_15ed0.c.
func_80136A08()
s32 func_80136A08 ()
Definition at line 272 of file code_b72b0_len_15ed0.c.