src/code_a5dd0_len_114e0.c File Reference - Paper Mario Documentation
code_a5dd0_len_114e0.c File Reference
Data Structures
struct Fog
struct RenderTaskEntry
struct GameMode
Macros
#define AREA_SPECIFIC_ENTITY_VRAM &entity_default_VRAM
Typedefs
typedef Model * SmallModelList[4]
Functions
s32 update_entities ()
s32 update_shadows ()
s32 set_entity_updatecmd ()
s32 step_entity_updatecmd ()
void exec_entity_updatecmd (Entity *entity)
void func_8010FD98 (s32 arg0, s32 alpha)
s32 func_8010FE44 ()
void entity_model_set_shadow_color (s32 alpha)
s32 render_entities ()
s32 render_shadows ()
s32 update_entity_transform_matrix ()
s32 update_shadow_transform_matrix ()
s32 update_entity_inverse_rotation_matrix ()
Entity * get_entity_by_index (s32 index)
Shadow * get_shadow_by_index (s32 index)
EntityList * get_entity_list (void)
ShadowList * get_shadow_list (void)
s32 func_80110678 ()
u32 get_entity_type (s32 index)
s32 delete_entity ()
s32 delete_entity_and_unload_data ()
s32 func_8011085C ()
s32 entity_get_collision_flags ()
s32 func_801109DC ()
s32 test_player_entity_aabb ()
s32 is_player_action_state (ActionState actionState)
s32 func_80110BCC ()
s32 func_80110BF8 ()
void load_area_specific_entity_data (void)
s32 clear_entity_data ()
s32 func_80110E58 ()
s32 func_80110F10 ()
s32 func_801110B4 ()
s32 is_entity_data_loaded ()
s32 load_simple_entity_data ()
s32 load_split_entity_data ()
s32 func_80111790 ()
s32 func_801117DC ()
s32 create_entity (StaticEntityData *data, s32 x, s32 y, s32 z, s32 arg4, s32 flags)
s32 create_shadow_from_data ()
s32 MakeEntity (ScriptInstance *script, s32 isInitialCall)
s32 func_80111E9C ()
s32 UseDynamicShadow ()
s32 AssignScript (ScriptInstance *script, s32 isInitialCall)
s32 AssignAreaFlag (ScriptInstance *script, s32 isInitialCall)
s32 AssignBlockFlag (ScriptInstance *script, s32 isInitialCall)
ApiStatus AssignFlag (ScriptInstance *script, s32 isInitialCall)
s32 AssignPanelFlag (ScriptInstance *script, s32 isInitialCall)
s32 AssignCrateFlag (ScriptInstance *script, s32 isInitialCall)
s32 create_entity_shadow ()
Shadow * create_shadow_type (s32 type, f32 x, f32 y, f32 z)
s32 func_80112328 ()
s32 func_80112344 ()
s32 func_801125E8 ()
s32 set_standard_shadow_scale ()
s32 set_npc_shadow_scale ()
s32 set_peach_shadow_scale ()
s32 func_80112B20 ()
void NOP_state (void)
s32 func_80112B98 ()
GameMode * set_next_game_mode (GameMode *arg0)
GameMode * set_game_mode_slot (s32 i, GameMode *arg0)
void func_80112D84 (s32 i, void(*fn)(void))
void func_80112DD4 (s32 i)
void func_80112DFC (s32 i)
void func_80112E24 (s32 i)
void func_80112E4C (s32 i)
void step_current_game_mode (void)
s32 func_80112EEC ()
s32 render_ui ()
s32 func_80112FC4 ()
s32 appendGfx_model ()
s32 func_80114B58 ()
s32 load_tile_header ()
s32 func_80115498 ()
s32 get_model_property ()
s32 _load_model_textures ()
s32 load_model_textures ()
s32 mdl_get_child_count ()
s32 clear_model_data ()
s32 init_model_data ()
s32 calculate_model_sizes ()
s32 mdl_create_model ()
s32 func_80116674 ()
s32 func_80116698 ()
s32 render_models ()
s32 appendGfx_model_group ()
s32 func_80117D00 ()
s32 func_80117E74 ()
s32 func_8011800C ()
s32 func_801180E8 ()
Model * get_model_from_list_index (s32 listIndex)
s32 load_data_for_models ()
s32 load_model_transforms ()
s32 get_model_list_index_from_tree_index (s32 treeIndex)
s32 func_8011B090 ()
void get_model_center_and_size (s32 modelID, f32 *centerX, f32 *centerY, f32 *centerZ, f32 *sizeX, f32 *sizeY, f32 *sizeZ)
s32 func_8011B1C0 ()
s32 func_8011B1D8 ()
s32 func_8011B37C ()
s32 func_8011B5D0 ()
s32 func_8011B660 ()
void clone_model (u16 srcModelID, u16 newModelID)
void func_8011B7C0 (u16 arg0, s32 arg1, s32 arg2)
s32 func_8011B950 ()
void func_8011BAE8 (void)
void enable_world_fog (void)
void disable_world_fog (void)
void set_world_fog_dist (s32 start, s32 end)
void set_world_fog_color (s32 r, s32 g, s32 b, s32 a)
s32 is_world_fog_enabled (void)
void get_world_fog_distance (s32 *start, s32 *end)
void get_world_fog_color (s32 *r, s32 *g, s32 *b, s32 *a)
void set_tex_panner (Model *model, s8 texPannerID)
void set_main_pan_u (s32 texPannerID, s32 value)
void set_main_pan_v (s32 texPannerID, s32 value)
void set_aux_pan_u (s32 texPannerID, s32 value)
void set_aux_pan_v (s32 texPannerID, s32 value)
s32 func_8011BC7C ()
s32 func_8011BCB4 ()
s32 func_8011BCD0 ()
s32 func_8011BCEC ()
s32 is_identity_fixed_mtx ()
void set_background_color_blend (u8 r, u8 g, u8 b, u8 a)
s32 get_background_color_blend ()
s32 func_8011BEB4 ()
s32 func_8011BF14 ()
s32 func_8011BF98 ()
s32 func_8011BFD4 ()
s32 func_8011C028 ()
s32 func_8011C0DC ()
s32 func_8011C130 ()
s32 func_8011C164 ()
s32 func_8011C2B0 ()
s32 func_8011C2EC ()
s32 func_8011C32C ()
s32 func_8011C80C ()
s32 func_8011CFBC ()
void func_8011D72C (Gfx **arg0, u16 treeIndex)
s32 func_8011D7E4 ()
s32 func_8011D82C ()
s32 func_8011D890 ()
s32 func_8011D8D0 ()
RenderTaskEntry * queue_render_task (RenderTask *task)
s32 func_8011D9B8 ()
Variables
SmallModelList * D_801512E0
s32 D_8015132C
Fog * wFog
s32 D_801533B0
s32 D_801533AC
s32 D_8014C188 []
RenderTaskEntry * D_801533A0 []
s32 texPannerMainU [MAX_TEX_PANNERS]
s32 texPannerMainV [MAX_TEX_PANNERS]
s32 texPannerAuxU [MAX_TEX_PANNERS]
s32 texPannerAuxV [MAX_TEX_PANNERS]
GameMode gMainGameState [2]
Macro Definition Documentation
AREA_SPECIFIC_ENTITY_VRAM
#define AREA_SPECIFIC_ENTITY_VRAM &entity_default_VRAM
Definition at line 137 of file code_a5dd0_len_114e0.c.
Typedef Documentation
SmallModelList
typedef Model* SmallModelList[4]
Definition at line 21 of file code_a5dd0_len_114e0.c.
Function Documentation
update_entities()
s32 update_entities ()
Definition at line 37 of file code_a5dd0_len_114e0.c.
Referenced by func_802A123C_718A8C(), and step_game_loop().
update_shadows()
s32 update_shadows ()
Definition at line 39 of file code_a5dd0_len_114e0.c.
set_entity_updatecmd()
s32 set_entity_updatecmd ()
Definition at line 41 of file code_a5dd0_len_114e0.c.
Referenced by func_802E1350(), func_802E38D8(), func_802E3BA4(), and func_802E4154().
step_entity_updatecmd()
s32 step_entity_updatecmd ()
Definition at line 43 of file code_a5dd0_len_114e0.c.
exec_entity_updatecmd()
void exec_entity_updatecmd (Entity * entity)
Definition at line 45 of file code_a5dd0_len_114e0.c.
Referenced by func_80240444_8CAD44(), func_802E1204(), func_802E1270(), func_802E1328(), func_802E1350(), func_802E1400(), func_802E1460(), func_802E14D8(), func_802E1614(), func_802E1660(), func_802E1740(), func_802E17A8(), func_802E1EDC(), func_802E3728(), func_802E37E4(), func_802E3A48(), func_802E3BA4(), func_802E4154(), func_802E54CC(), func_802E555C(), func_802E8858(), func_802E89B0(), func_802E89F8(), func_802E8A58(), func_802E8ADC(), func_802E8C94(), and func_802E8D74().
func_8010FD98()
void func_8010FD98 (s32 arg0, s32 alpha)
Definition at line 47 of file code_a5dd0_len_114e0.c.
func_8010FE44()
s32 func_8010FE44 ()
Definition at line 57 of file code_a5dd0_len_114e0.c.
entity_model_set_shadow_color()
void entity_model_set_shadow_color (s32 alpha)
Definition at line 59 of file code_a5dd0_len_114e0.c.
render_entities()
s32 render_entities ()
Definition at line 64 of file code_a5dd0_len_114e0.c.
render_shadows()
s32 render_shadows ()
Definition at line 66 of file code_a5dd0_len_114e0.c.
update_entity_transform_matrix()
s32 update_entity_transform_matrix ()
Definition at line 68 of file code_a5dd0_len_114e0.c.
update_shadow_transform_matrix()
s32 update_shadow_transform_matrix ()
Definition at line 70 of file code_a5dd0_len_114e0.c.
update_entity_inverse_rotation_matrix()
s32 update_entity_inverse_rotation_matrix ()
Definition at line 72 of file code_a5dd0_len_114e0.c.
get_entity_by_index()
Entity* get_entity_by_index (s32 index)
Definition at line 74 of file code_a5dd0_len_114e0.c.
Referenced by AssignFlag(), func_802402BC_8D878C(), func_80240444_8CAD44(), func_80240A6C_8D482C(), func_80240EC0_8DAFC0(), func_802A123C_718A8C(), func_802A12E4_718B34(), func_802A1318_718B68(), func_802E2BA4(), func_802E38D8(), func_802E4108(), func_802E421C(), func_802E455C(), func_802E4B10(), func_802E4B60(), func_802E55A8(), func_802E5690(), func_802E56EC(), func_802E581C(), get_entity_type(), GetEntityPosition(), SetEntityFlags100000(), and SetEntityPosition().
get_shadow_by_index()
Shadow* get_shadow_by_index (s32 index)
Definition at line 78 of file code_a5dd0_len_114e0.c.
Referenced by disable_npc_shadow(), disable_player_shadow(), enable_npc_shadow(), enable_player_shadow(), func_802E4108(), func_802E421C(), and func_802E4484().
get_entity_list()
EntityList* get_entity_list (void)
Definition at line 82 of file code_a5dd0_len_114e0.c.
get_shadow_list()
ShadowList* get_shadow_list (void)
Definition at line 93 of file code_a5dd0_len_114e0.c.
func_80110678()
s32 func_80110678 ()
Definition at line 104 of file code_a5dd0_len_114e0.c.
Referenced by func_802E1460(), func_802E1EA8(), func_802E3BA4(), func_802E4040(), func_802E8858(), func_802E8E10(), and func_802E9050().
get_entity_type()
u32 get_entity_type (s32 index)
Definition at line 106 of file code_a5dd0_len_114e0.c.
Referenced by func_802E2EB0(), func_802E2FD0(), func_802E31EC(), func_802E328C(), func_802E3BA4(), func_802E40A0(), func_802E4154(), and func_802E421C().
delete_entity()
s32 delete_entity ()
Definition at line 116 of file code_a5dd0_len_114e0.c.
delete_entity_and_unload_data()
s32 delete_entity_and_unload_data ()
Definition at line 118 of file code_a5dd0_len_114e0.c.
func_8011085C()
s32 func_8011085C ()
Definition at line 120 of file code_a5dd0_len_114e0.c.
entity_get_collision_flags()
s32 entity_get_collision_flags ()
Definition at line 122 of file code_a5dd0_len_114e0.c.
func_801109DC()
s32 func_801109DC ()
Definition at line 124 of file code_a5dd0_len_114e0.c.
test_player_entity_aabb()
s32 test_player_entity_aabb ()
Definition at line 126 of file code_a5dd0_len_114e0.c.
is_player_action_state()
s32 is_player_action_state (ActionState actionState)
Definition at line 128 of file code_a5dd0_len_114e0.c.
func_80110BCC()
s32 func_80110BCC ()
Definition at line 132 of file code_a5dd0_len_114e0.c.
Referenced by func_802E5428(), func_802E54A8(), and func_802E8858().
func_80110BF8()
s32 func_80110BF8 ()
Definition at line 134 of file code_a5dd0_len_114e0.c.
load_area_specific_entity_data()
void load_area_specific_entity_data (void)
Definition at line 142 of file code_a5dd0_len_114e0.c.
clear_entity_data()
s32 clear_entity_data ()
Definition at line 156 of file code_a5dd0_len_114e0.c.
Referenced by load_engine_data(), step_battle(), and step_init_state().
func_80110E58()
s32 func_80110E58 ()
Definition at line 158 of file code_a5dd0_len_114e0.c.
func_80110F10()
s32 func_80110F10 ()
Definition at line 160 of file code_a5dd0_len_114e0.c.
func_801110B4()
s32 func_801110B4 ()
Definition at line 162 of file code_a5dd0_len_114e0.c.
is_entity_data_loaded()
s32 is_entity_data_loaded ()
Definition at line 164 of file code_a5dd0_len_114e0.c.
load_simple_entity_data()
s32 load_simple_entity_data ()
Definition at line 166 of file code_a5dd0_len_114e0.c.
load_split_entity_data()
s32 load_split_entity_data ()
Definition at line 168 of file code_a5dd0_len_114e0.c.
func_80111790()
s32 func_80111790 ()
Definition at line 170 of file code_a5dd0_len_114e0.c.
func_801117DC()
s32 func_801117DC ()
Definition at line 172 of file code_a5dd0_len_114e0.c.
create_entity()
s32 create_entity (StaticEntityData * data, s32 x, s32 y, s32 z, s32 arg4, s32 flags)
Definition at line 175 of file code_a5dd0_len_114e0.c.
Referenced by func_802E2FD0(), func_802E38D8(), func_802E3A48(), func_802E3B08(), func_802E4154(), func_802E421C(), func_802E55A8(), and func_802E56EC().
create_shadow_from_data()
s32 create_shadow_from_data ()
Definition at line 177 of file code_a5dd0_len_114e0.c.
MakeEntity()
s32 MakeEntity (ScriptInstance * script, s32 isInitialCall)
Definition at line 179 of file code_a5dd0_len_114e0.c.
Referenced by N().
func_80111E9C()
s32 func_80111E9C ()
Definition at line 181 of file code_a5dd0_len_114e0.c.
UseDynamicShadow()
s32 UseDynamicShadow ()
Definition at line 183 of file code_a5dd0_len_114e0.c.
AssignScript()
s32 AssignScript (ScriptInstance * script, s32 isInitialCall)
Definition at line 185 of file code_a5dd0_len_114e0.c.
Referenced by N().
AssignAreaFlag()
s32 AssignAreaFlag (ScriptInstance * script, s32 isInitialCall)
Definition at line 187 of file code_a5dd0_len_114e0.c.
AssignBlockFlag()
s32 AssignBlockFlag (ScriptInstance * script, s32 isInitialCall)
Definition at line 189 of file code_a5dd0_len_114e0.c.
Referenced by N().
AssignFlag()
ApiStatus AssignFlag (ScriptInstance * script, s32 isInitialCall)
Definition at line 191 of file code_a5dd0_len_114e0.c.
AssignPanelFlag()
s32 AssignPanelFlag (ScriptInstance * script, s32 isInitialCall)
Definition at line 204 of file code_a5dd0_len_114e0.c.
AssignCrateFlag()
s32 AssignCrateFlag (ScriptInstance * script, s32 isInitialCall)
Definition at line 206 of file code_a5dd0_len_114e0.c.
create_entity_shadow()
s32 create_entity_shadow ()
Definition at line 208 of file code_a5dd0_len_114e0.c.
create_shadow_type()
Shadow * create_shadow_type (s32 type, f32 x, f32 y, f32 z)
Definition at line 210 of file code_a5dd0_len_114e0.c.
Referenced by create_part_shadow(), create_part_shadow_by_ref(), and func_800DFC74().
func_80112328()
s32 func_80112328 ()
Definition at line 212 of file code_a5dd0_len_114e0.c.
Referenced by delete_actor(), delete_player_actor(), and remove_part_shadow().
func_80112344()
s32 func_80112344 ()
Definition at line 214 of file code_a5dd0_len_114e0.c.
func_801125E8()
s32 func_801125E8 ()
Definition at line 216 of file code_a5dd0_len_114e0.c.
set_standard_shadow_scale()
s32 set_standard_shadow_scale ()
Definition at line 218 of file code_a5dd0_len_114e0.c.
set_npc_shadow_scale()
s32 set_npc_shadow_scale ()
Definition at line 220 of file code_a5dd0_len_114e0.c.
set_peach_shadow_scale()
s32 set_peach_shadow_scale ()
Definition at line 222 of file code_a5dd0_len_114e0.c.
func_80112B20()
s32 func_80112B20 ()
Definition at line 224 of file code_a5dd0_len_114e0.c.
Referenced by func_802E3650(), and func_802E421C().
NOP_state()
void NOP_state (void)
Definition at line 226 of file code_a5dd0_len_114e0.c.
Referenced by func_80112D84(), set_game_mode_slot(), and set_next_game_mode().
func_80112B98()
s32 func_80112B98 ()
Definition at line 229 of file code_a5dd0_len_114e0.c.
Referenced by load_engine_data().
set_next_game_mode()
GameMode* set_next_game_mode (GameMode * arg0)
Definition at line 246 of file code_a5dd0_len_114e0.c.
set_game_mode_slot()
GameMode* set_game_mode_slot (s32 i, GameMode * arg0)
Definition at line 276 of file code_a5dd0_len_114e0.c.
Referenced by set_game_mode().
func_80112D84()
void func_80112D84 (s32 i, void(*)(void) fn)
Definition at line 298 of file code_a5dd0_len_114e0.c.
Referenced by begin_state_world().
func_80112DD4()
void func_80112DD4 (s32 i)
Definition at line 311 of file code_a5dd0_len_114e0.c.
func_80112DFC()
void func_80112DFC (s32 i)
Definition at line 318 of file code_a5dd0_len_114e0.c.
func_80112E24()
void func_80112E24 (s32 i)
Definition at line 325 of file code_a5dd0_len_114e0.c.
func_80112E4C()
void func_80112E4C (s32 i)
Definition at line 332 of file code_a5dd0_len_114e0.c.
step_current_game_mode()
void step_current_game_mode (void)
Definition at line 343 of file code_a5dd0_len_114e0.c.
Referenced by step_game_loop().
func_80112EEC()
s32 func_80112EEC ()
Definition at line 360 of file code_a5dd0_len_114e0.c.
render_ui()
s32 render_ui ()
Definition at line 363 of file code_a5dd0_len_114e0.c.
func_80112FC4()
s32 func_80112FC4 ()
Definition at line 366 of file code_a5dd0_len_114e0.c.
appendGfx_model()
s32 appendGfx_model ()
Definition at line 368 of file code_a5dd0_len_114e0.c.
Referenced by func_8011D72C().
func_80114B58()
s32 func_80114B58 ()
Definition at line 370 of file code_a5dd0_len_114e0.c.
load_tile_header()
s32 load_tile_header ()
Definition at line 372 of file code_a5dd0_len_114e0.c.
func_80115498()
s32 func_80115498 ()
Definition at line 374 of file code_a5dd0_len_114e0.c.
get_model_property()
s32 get_model_property ()
Definition at line 376 of file code_a5dd0_len_114e0.c.
_load_model_textures()
s32 _load_model_textures ()
Definition at line 378 of file code_a5dd0_len_114e0.c.
load_model_textures()
s32 load_model_textures ()
Definition at line 380 of file code_a5dd0_len_114e0.c.
Referenced by state_init_file_select().
mdl_get_child_count()
s32 mdl_get_child_count ()
Definition at line 382 of file code_a5dd0_len_114e0.c.
clear_model_data()
s32 clear_model_data ()
Definition at line 384 of file code_a5dd0_len_114e0.c.
Referenced by load_engine_data(), step_battle(), and step_init_state().
init_model_data()
s32 init_model_data ()
Definition at line 386 of file code_a5dd0_len_114e0.c.
calculate_model_sizes()
s32 calculate_model_sizes ()
Definition at line 388 of file code_a5dd0_len_114e0.c.
mdl_create_model()
s32 mdl_create_model ()
Definition at line 390 of file code_a5dd0_len_114e0.c.
func_80116674()
s32 func_80116674 ()
Definition at line 392 of file code_a5dd0_len_114e0.c.
Referenced by step_battle(), and step_world().
func_80116698()
s32 func_80116698 ()
Definition at line 394 of file code_a5dd0_len_114e0.c.
render_models()
s32 render_models ()
Definition at line 396 of file code_a5dd0_len_114e0.c.
appendGfx_model_group()
s32 appendGfx_model_group ()
Definition at line 398 of file code_a5dd0_len_114e0.c.
func_80117D00()
s32 func_80117D00 ()
Definition at line 400 of file code_a5dd0_len_114e0.c.
func_80117E74()
s32 func_80117E74 ()
Definition at line 402 of file code_a5dd0_len_114e0.c.
func_8011800C()
s32 func_8011800C ()
Definition at line 404 of file code_a5dd0_len_114e0.c.
func_801180E8()
s32 func_801180E8 ()
Definition at line 406 of file code_a5dd0_len_114e0.c.
get_model_from_list_index()
Model* get_model_from_list_index (s32 listIndex)
Definition at line 408 of file code_a5dd0_len_114e0.c.
Referenced by clone_model(), EnableModel(), EnableTexPanning(), func_8011D72C(), func_802C8EE4(), func_802C90FC(), func_802C91A4(), hide_foreground_models(), hide_foreground_models_unsafe(), RotateModel(), ScaleModel(), SetModelFlag10(), SetModelFlags(), SetRenderMode(), SetTexPanner(), show_foreground_models(), show_foreground_models_unsafe(), SomeMatrixOperation2(), and TranslateModel().
load_data_for_models()
s32 load_data_for_models ()
Definition at line 412 of file code_a5dd0_len_114e0.c.
load_model_transforms()
s32 load_model_transforms ()
Definition at line 414 of file code_a5dd0_len_114e0.c.
get_model_list_index_from_tree_index()
s32 get_model_list_index_from_tree_index (s32 treeIndex)
Definition at line 416 of file code_a5dd0_len_114e0.c.
Referenced by clone_model(), EnableModel(), EnableTexPanning(), func_8011D72C(), func_802C8EE4(), func_802C90FC(), func_802C91A4(), GetModelIndex(), hide_foreground_models(), hide_foreground_models_unsafe(), ParentColliderToModel(), RotateModel(), ScaleModel(), SetModelFlag10(), SetModelFlags(), SetRenderMode(), SetTexPanner(), show_foreground_models(), show_foreground_models_unsafe(), SomeMatrixOperation2(), and TranslateModel().
func_8011B090()
s32 func_8011B090 ()
Definition at line 418 of file code_a5dd0_len_114e0.c.
Referenced by func_802C9B40().
get_model_center_and_size()
void get_model_center_and_size (s32 modelID, f32 * centerX, f32 * centerY, f32 * centerZ, f32 * sizeX, f32 * sizeY, f32 * sizeZ)
Definition at line 421 of file code_a5dd0_len_114e0.c.
Referenced by GetModelCenter(), and PlaySoundAtModel().
func_8011B1C0()
s32 func_8011B1C0 ()
Definition at line 423 of file code_a5dd0_len_114e0.c.
func_8011B1D8()
s32 func_8011B1D8 ()
Definition at line 425 of file code_a5dd0_len_114e0.c.
func_8011B37C()
s32 func_8011B37C ()
Definition at line 427 of file code_a5dd0_len_114e0.c.
Referenced by func_802C971C().
func_8011B5D0()
s32 func_8011B5D0 ()
Definition at line 429 of file code_a5dd0_len_114e0.c.
Referenced by func_802C9748().
func_8011B660()
s32 func_8011B660 ()
Definition at line 431 of file code_a5dd0_len_114e0.c.
Referenced by func_802C9748().
clone_model()
void clone_model (u16 srcModelID, u16 newModelID)
Definition at line 433 of file code_a5dd0_len_114e0.c.
Referenced by CloneModel().
func_8011B7C0()
void func_8011B7C0 (u16 arg0, s32 arg1, s32 arg2)
Definition at line 452 of file code_a5dd0_len_114e0.c.
Referenced by SetGroupEnabled().
func_8011B950()
s32 func_8011B950 ()
Definition at line 454 of file code_a5dd0_len_114e0.c.
func_8011BAE8()
void func_8011BAE8 (void)
Definition at line 456 of file code_a5dd0_len_114e0.c.
Referenced by step_game_loop().
enable_world_fog()
void enable_world_fog (void)
Definition at line 476 of file code_a5dd0_len_114e0.c.
disable_world_fog()
void disable_world_fog (void)
Definition at line 480 of file code_a5dd0_len_114e0.c.
set_world_fog_dist()
void set_world_fog_dist (s32 start, s32 end)
Definition at line 484 of file code_a5dd0_len_114e0.c.
set_world_fog_color()
void set_world_fog_color (s32 r, s32 g, s32 b, s32 a)
Definition at line 489 of file code_a5dd0_len_114e0.c.
is_world_fog_enabled()
s32 is_world_fog_enabled (void)
Definition at line 496 of file code_a5dd0_len_114e0.c.
get_world_fog_distance()
void get_world_fog_distance (s32 * start, s32 * end)
Definition at line 500 of file code_a5dd0_len_114e0.c.
get_world_fog_color()
void get_world_fog_color (s32 * r, s32 * g, s32 * b, s32 * a)
Definition at line 507 of file code_a5dd0_len_114e0.c.
set_tex_panner()
void set_tex_panner (Model * model, s8 texPannerID)
Definition at line 516 of file code_a5dd0_len_114e0.c.
Referenced by SetTexPanner().
set_main_pan_u()
void set_main_pan_u (s32 texPannerID, s32 value)
Definition at line 520 of file code_a5dd0_len_114e0.c.
Referenced by SetTexPanOffset(), UnkTexturePanFunc(), and UnkTexturePanFunc2().
set_main_pan_v()
void set_main_pan_v (s32 texPannerID, s32 value)
Definition at line 524 of file code_a5dd0_len_114e0.c.
Referenced by SetTexPanOffset(), UnkTexturePanFunc(), and UnkTexturePanFunc2().
set_aux_pan_u()
void set_aux_pan_u (s32 texPannerID, s32 value)
Definition at line 528 of file code_a5dd0_len_114e0.c.
Referenced by SetTexPanOffset(), UnkTexturePanFunc(), and UnkTexturePanFunc2().
set_aux_pan_v()
void set_aux_pan_v (s32 texPannerID, s32 value)
Definition at line 532 of file code_a5dd0_len_114e0.c.
Referenced by SetTexPanOffset(), UnkTexturePanFunc(), and UnkTexturePanFunc2().
func_8011BC7C()
s32 func_8011BC7C ()
Definition at line 536 of file code_a5dd0_len_114e0.c.
Referenced by func_802C90FC().
func_8011BCB4()
s32 func_8011BCB4 ()
Definition at line 538 of file code_a5dd0_len_114e0.c.
Referenced by func_802C9428().
func_8011BCD0()
s32 func_8011BCD0 ()
Definition at line 540 of file code_a5dd0_len_114e0.c.
Referenced by func_802C94A0().
func_8011BCEC()
s32 func_8011BCEC ()
Definition at line 542 of file code_a5dd0_len_114e0.c.
is_identity_fixed_mtx()
s32 is_identity_fixed_mtx ()
Returns
TRUE if mtx is NULL or identity.
Definition at line 545 of file code_a5dd0_len_114e0.c.
set_background_color_blend()
void set_background_color_blend (u8 r, u8 g, u8 b, u8 a)
Definition at line 547 of file code_a5dd0_len_114e0.c.
Referenced by FadeBackgroundToBlack(), func_802188A8_5CEF38(), func_802188EC_5CEF7C(), func_802A12D4_71B474(), func_802A12D4_7270A4(), func_802A12D4_72BBE4(), func_802A1378_716FD8(), func_802A13B8_71C1E8(), func_802A1420_722F60(), func_802A1444_71DBB4(), func_802A14D4_71DC44(), func_802A247C_79843C(), func_802A247C_79AC2C(), UnfadeBackgroundFromBlack(), UnkAlphaFunc(), UnkBackgroundFunc(), and UnkBackgroundFunc2().
get_background_color_blend()
s32 get_background_color_blend ()
Definition at line 549 of file code_a5dd0_len_114e0.c.
func_8011BEB4()
s32 func_8011BEB4 ()
Definition at line 551 of file code_a5dd0_len_114e0.c.
func_8011BF14()
s32 func_8011BF14 ()
Definition at line 553 of file code_a5dd0_len_114e0.c.
func_8011BF98()
s32 func_8011BF98 ()
Definition at line 555 of file code_a5dd0_len_114e0.c.
func_8011BFD4()
s32 func_8011BFD4 ()
Definition at line 557 of file code_a5dd0_len_114e0.c.
func_8011C028()
s32 func_8011C028 ()
Definition at line 559 of file code_a5dd0_len_114e0.c.
func_8011C0DC()
s32 func_8011C0DC ()
Definition at line 561 of file code_a5dd0_len_114e0.c.
func_8011C130()
s32 func_8011C130 ()
Definition at line 563 of file code_a5dd0_len_114e0.c.
func_8011C164()
s32 func_8011C164 ()
Definition at line 565 of file code_a5dd0_len_114e0.c.
Referenced by func_802C9C70().
func_8011C2B0()
s32 func_8011C2B0 ()
Definition at line 567 of file code_a5dd0_len_114e0.c.
func_8011C2EC()
s32 func_8011C2EC ()
Definition at line 569 of file code_a5dd0_len_114e0.c.
func_8011C32C()
s32 func_8011C32C ()
Definition at line 571 of file code_a5dd0_len_114e0.c.
func_8011C80C()
s32 func_8011C80C ()
Definition at line 573 of file code_a5dd0_len_114e0.c.
func_8011CFBC()
s32 func_8011CFBC ()
Definition at line 575 of file code_a5dd0_len_114e0.c.
func_8011D72C()
void func_8011D72C (Gfx ** arg0, u16 treeIndex)
Definition at line 577 of file code_a5dd0_len_114e0.c.
func_8011D7E4()
s32 func_8011D7E4 ()
Definition at line 601 of file code_a5dd0_len_114e0.c.
func_8011D82C()
s32 func_8011D82C ()
Definition at line 603 of file code_a5dd0_len_114e0.c.
Referenced by FadeBackgroundToBlack(), func_802188A8_5CEF38(), func_802A1444_71DBB4(), UnkAlphaFunc(), and UnkBackgroundFunc2().
func_8011D890()
s32 func_8011D890 ()
Definition at line 605 of file code_a5dd0_len_114e0.c.
Referenced by load_engine_data(), and step_init_state().
func_8011D8D0()
s32 func_8011D8D0 ()
Definition at line 607 of file code_a5dd0_len_114e0.c.
queue_render_task()
RenderTaskEntry* queue_render_task (RenderTask * task)
Definition at line 609 of file code_a5dd0_len_114e0.c.
func_8011D9B8()
s32 func_8011D9B8 ()
Definition at line 628 of file code_a5dd0_len_114e0.c.
Variable Documentation
D_801512E0
SmallModelList* D_801512E0 extern
Referenced by func_8011BAE8().
D_8015132C
s32 D_8015132C extern
Referenced by load_area_specific_entity_data().
wFog
Fog* wFog extern
Referenced by disable_world_fog(), enable_world_fog(), get_world_fog_color(), get_world_fog_distance(), is_world_fog_enabled(), set_world_fog_color(), and set_world_fog_dist().
D_801533B0
s32 D_801533B0 extern
Referenced by queue_render_task().
D_801533AC
s32 D_801533AC extern
Referenced by queue_render_task().
D_8014C188
s32 D_8014C188[] extern
Referenced by queue_render_task().
D_801533A0
RenderTaskEntry* D_801533A0[] extern
Referenced by queue_render_task().
texPannerMainU
s32 texPannerMainU[MAX_TEX_PANNERS] extern
Referenced by set_main_pan_u().
texPannerMainV
s32 texPannerMainV[MAX_TEX_PANNERS] extern
Referenced by set_main_pan_v().
texPannerAuxU
s32 texPannerAuxU[MAX_TEX_PANNERS] extern
Referenced by set_aux_pan_u().
texPannerAuxV
s32 texPannerAuxV[MAX_TEX_PANNERS] extern
Referenced by set_aux_pan_v().
gMainGameState
GameMode gMainGameState[2] extern
Referenced by func_80112D84(), func_80112DD4(), func_80112DFC(), func_80112E24(), func_80112E4C(), set_game_mode_slot(), set_next_game_mode(), and step_current_game_mode().