src/code_1370_len_7d0.c File Reference - Paper Mario Documentation
code_1370_len_7d0.c File Reference
Functions
void gfxRetrace_Callback (s32)
void gfxPreNMI_Callback (void)
void gfx_task_main (void)
void boot_main (void)
Variables
s16 D_80074010 = 8
s32 * D_80073E00
s32 D_80073E04
s16 D_80073E08
s16 D_80073E0A
s32 * D_8009A680
Function Documentation
gfxRetrace_Callback()
void gfxRetrace_Callback (s32 arg0)
Definition at line 54 of file code_1370_len_7d0.c.
Referenced by boot_main().
gfxPreNMI_Callback()
void gfxPreNMI_Callback (void)
Definition at line 98 of file code_1370_len_7d0.c.
Referenced by boot_main().
gfx_task_main()
void gfx_task_main (void)
Definition at line 96 of file code_1370_len_7d0.c.
Referenced by gfxRetrace_Callback().
boot_main()
void boot_main (void)
Definition at line 18 of file code_1370_len_7d0.c.
Referenced by boot_idle().
Variable Documentation
D_80074010
s16 D_80074010 = 8
Definition at line 4 of file code_1370_len_7d0.c.
D_80073E00
s32* D_80073E00 extern
Referenced by gfxPreNMI_Callback(), and gfxRetrace_Callback().
D_80073E04
s32 D_80073E04 extern
Referenced by gfxRetrace_Callback().
D_80073E08
s16 D_80073E08 extern
Referenced by gfxRetrace_Callback().
D_80073E0A
s16 D_80073E0A extern
Referenced by gfxRetrace_Callback().
D_8009A680
s32* D_8009A680 extern
Referenced by gfxRetrace_Callback().