src/code_13870_len_6980.c File Reference - Paper Mario Documentation
code_13870_len_6980.c File Reference
Functions
void NOP_npc_callback (void)
void mtx_ident_mirror_y (Matrix4f *mtx)
s32 clear_npcs ()
void init_npc_list (void)
void func_8003857C (void)
s32 _create_npc (NpcBlueprint *blueprint, s32 animList[], s32 skipLoadingAnims)
void create_basic_npc (s32 *arg0)
void create_standard_npc (s32 *arg0, s32 arg1)
void create_partner_npc (NpcBlueprint *blueprint)
s32 free_npc_by_index ()
s32 free_npc ()
Npc * get_npc_by_index (s32 listIndex)
s32 npc_do_world_collision ()
s32 npc_do_other_npc_collision ()
s32 npc_do_player_collision ()
s32 func_80039688 ()
s32 func_800397E8 ()
s32 update_npcs ()
s32 func_80039DA4 ()
s32 appendGfx_npc ()
s32 render_npcs ()
void npc_move_heading (Npc *npc, f32 speed, f32 yaw)
Npc * get_npc_unsafe (NpcId npcId)
Npc * get_npc_safe (NpcId npcId)
void enable_npc_shadow (Npc *npc)
void disable_npc_shadow (Npc *npc)
func_802DE2AC (s32 arg0, s32 arg1, f32 arg2)
void set_npc_sprite (Npc *npc, s32 arg1, s32 arg2)
void enable_npc_blur (Npc *npc)
void disable_npc_blur (Npc *npc)
void update_npc_blur (Npc *npc)
s32 appedGfx_npc_blur ()
s32 func_8003B184 ()
s32 func_8003B198 ()
void func_8003B1A8 (void)
s32 func_8003B1B0 ()
void set_npc_yaw (Npc *npc, f32 angle)
s32 func_8003B3D0 ()
s32 func_8003B3F8 ()
s32 func_8003B420 ()
s32 func_8003B44C ()
s32 func_8003B464 ()
s32 func_8003B47C ()
s32 func_8003B500 ()
s32 func_8003B5B4 ()
s32 func_8003B96C ()
s32 func_8003BA60 ()
s32 func_8003BED8 ()
s32 func_8003C3D8 ()
s32 func_8003C428 ()
s32 func_8003C444 ()
s32 func_8003C53C ()
s32 func_8003C61C ()
void func_8003C658 (void)
void func_8003C660 (void)
s32 func_8003C668 ()
s32 func_8003C78C ()
s32 func_8003C7A8 ()
void func_8003C8AC (void)
s32 func_8003C8B4 ()
s32 func_8003C984 ()
s32 func_8003C9A8 ()
s32 func_8003CB20 ()
s32 func_8003CB44 ()
s32 func_8003CC8C ()
s32 func_8003CCB0 ()
void func_8003CFA0 (void)
s32 func_8003CFA8 ()
s32 func_8003CFB4 ()
s32 func_8003D0C4 ()
s32 func_8003D1D4 ()
s32 func_8003D2F8 ()
s32 func_8003D3BC ()
s32 func_8003D624 ()
s32 func_8003D660 ()
s32 func_8003D788 ()
s32 func_8003DA38 ()
s32 func_8003DC38 ()
s32 func_8003DFA0 ()
s32 func_8003E0D4 ()
s32 func_8003E1D0 ()
s32 COPY_set_defeated ()
s32 func_8003E338 ()
s32 clear_encounter_status ()
void func_8003E50C (void)
s32 func_8003E514 ()
s32 update_counters ()
s32 draw_encounter_ui ()
s32 draw_first_strike_ui ()
void func_8003E670 (void)
s32 make_npcs ()
s32 kill_encounter ()
s32 kill_enemy ()
s32 bind_enemy_ai ()
s32 bind_enemy_aux ()
s32 bind_enemy_interact ()
s32 bind_npc_ai ()
s32 bind_npc_aux ()
s32 bind_npc_interact ()
Enemy * get_enemy (NpcId npcId)
s32 get_enemy_safe ()
Function Documentation
NOP_npc_callback()
void NOP_npc_callback (void)
Definition at line 4 of file code_13870_len_6980.c.
mtx_ident_mirror_y()
void mtx_ident_mirror_y (Matrix4f * mtx)
Definition at line 7 of file code_13870_len_6980.c.
clear_npcs()
s32 clear_npcs ()
Definition at line 15 of file code_13870_len_6980.c.
Referenced by load_engine_data(), step_battle(), and step_init_state().
init_npc_list()
void init_npc_list (void)
Definition at line 17 of file code_13870_len_6980.c.
func_8003857C()
void func_8003857C (void)
Definition at line 28 of file code_13870_len_6980.c.
Referenced by step_game_loop().
_create_npc()
s32 _create_npc (NpcBlueprint * blueprint, s32 animList[], s32 skipLoadingAnims)
Definition at line 38 of file code_13870_len_6980.c.
Referenced by create_basic_npc(), create_partner_npc(), and create_standard_npc().
create_basic_npc()
void create_basic_npc (s32 * arg0)
Definition at line 40 of file code_13870_len_6980.c.
create_standard_npc()
void create_standard_npc (s32 * arg0, s32 arg1)
Definition at line 44 of file code_13870_len_6980.c.
create_partner_npc()
void create_partner_npc (NpcBlueprint * blueprint)
Definition at line 48 of file code_13870_len_6980.c.
free_npc_by_index()
s32 free_npc_by_index ()
Definition at line 52 of file code_13870_len_6980.c.
Referenced by func_800E63A4(), and func_800EA6A8().
free_npc()
s32 free_npc ()
Definition at line 54 of file code_13870_len_6980.c.
Referenced by DeleteNpc().
get_npc_by_index()
Npc* get_npc_by_index (s32 listIndex)
Definition at line 56 of file code_13870_len_6980.c.
Referenced by func_800E636C(), func_800E6500(), load_partner_npc(), and UnkAlphaFunc().
npc_do_world_collision()
s32 npc_do_world_collision ()
Definition at line 60 of file code_13870_len_6980.c.
npc_do_other_npc_collision()
s32 npc_do_other_npc_collision ()
Definition at line 62 of file code_13870_len_6980.c.
npc_do_player_collision()
s32 npc_do_player_collision ()
Definition at line 64 of file code_13870_len_6980.c.
func_80039688()
s32 func_80039688 ()
Definition at line 66 of file code_13870_len_6980.c.
func_800397E8()
s32 func_800397E8 ()
Definition at line 68 of file code_13870_len_6980.c.
update_npcs()
s32 update_npcs ()
Definition at line 70 of file code_13870_len_6980.c.
Referenced by step_battle(), and step_world().
func_80039DA4()
s32 func_80039DA4 ()
Definition at line 72 of file code_13870_len_6980.c.
appendGfx_npc()
s32 appendGfx_npc ()
Definition at line 74 of file code_13870_len_6980.c.
render_npcs()
s32 render_npcs ()
Definition at line 76 of file code_13870_len_6980.c.
npc_move_heading()
void npc_move_heading (Npc * npc, f32 speed, f32 yaw)
Definition at line 78 of file code_13870_len_6980.c.
Referenced by UnkNpcAIFunc11(), and UnkNpcAIFunc12().
get_npc_unsafe()
Npc * get_npc_unsafe (NpcId npcId)
Definition at line 87 of file code_13870_len_6980.c.
Referenced by Bandit_DropCoin(), CheckPartnerFlags1000(), DeleteNpc(), DoNpcDefeat(), FadeInMerlee(), FadeOutMerlee(), func_80045900(), func_80048F0C(), func_800493EC(), func_80049550(), func_80049E3C(), func_80049ECC(), func_8004A3E8(), func_8004A6F0(), func_8004A73C(), func_800E6860(), func_80240060_BFA100(), func_802401B0_8C8140(), func_80240530_8AC4C0(), func_80240A70_9B2200(), func_80240BD8_8ACB68(), func_80283908(), get_npc_pos(), GetNpcUnsafeOwner2(), GetPartnerPos(), NpcJumpFunc(), NpcJumpFunc2(), NpcJumpFunc3(), OnDefeatEnemy(), set_script_owner_npc_anim(), set_script_owner_npc_col_height(), SetNpcCollision32(), SetSelfRotation(), SyncOverrideEnemyPos(), TeleportPartnerToPlayer(), UnkDurationCheck(), UnkMovePartner(), UnkNpcAIFunc1(), UnkNpcAIFunc10(), UnkNpcAIFunc11(), UnkNpcAIFunc12(), UnkNpcAIFunc13(), UnkNpcAIFunc13_2(), UnkNpcAIFunc14(), UnkNpcAIFunc15(), UnkNpcAIFunc16(), UnkNpcAIFunc17(), UnkNpcAIFunc18(), UnkNpcAIFunc19(), UnkNpcAIFunc2(), UnkNpcAIFunc20(), UnkNpcAIFunc21(), UnkNpcAIFunc22(), UnkNpcAIFunc3(), UnkNpcAIFunc4(), UnkNpcAIFunc5(), UnkNpcAIFunc6(), UnkNpcAIFunc7(), UnkNpcAIFunc8(), UnkNpcAIFunc9(), UnkNpcDurationFlagFunc(), UnkRotatePartner(), UnkSetDurationFunc(), UnkYawFunc(), and update_player().
get_npc_safe()
Npc * get_npc_safe (NpcId npcId)
Definition at line 89 of file code_13870_len_6980.c.
Referenced by AwaitPlayerNearNpc(), func_80240000_8C7F90(), func_80240814_97BE44(), func_802408B4_97BEE4(), GetNpcCollisionHeight(), GetNpcPointer(), play_sound_at_npc(), resolve_npc(), SetPartnerFlags20000(), SetPartnerFlags80000(), SetPartnerFlagsA0000(), UnkPartnerPosFunc(), and UnkPartnerPosFunc2().
enable_npc_shadow()
void enable_npc_shadow (Npc * npc)
Definition at line 91 of file code_13870_len_6980.c.
Referenced by EnableNpcShadow(), and UnkNpcAIFunc21().
disable_npc_shadow()
void disable_npc_shadow (Npc * npc)
Definition at line 101 of file code_13870_len_6980.c.
Referenced by EnableNpcShadow(), func_80240000_8C7F90(), and UnkNpcAIFunc18().
func_802DE2AC()
s32 func_802DE2AC (s32 arg0, s32 arg1, f32 arg2)
Definition at line 177 of file code_fee30_len_2d60.c.
Referenced by set_npc_sprite().
set_npc_sprite()
void set_npc_sprite (Npc * npc, s32 arg1, s32 arg2)
Definition at line 114 of file code_13870_len_6980.c.
Referenced by SetNpcSprite().
enable_npc_blur()
void enable_npc_blur (Npc * npc)
Definition at line 132 of file code_13870_len_6980.c.
Referenced by EnableNpcBlur().
disable_npc_blur()
void disable_npc_blur (Npc * npc)
Definition at line 152 of file code_13870_len_6980.c.
Referenced by EnableNpcBlur(), and world_goombario_pre_battle().
update_npc_blur()
void update_npc_blur (Npc * npc)
Definition at line 160 of file code_13870_len_6980.c.
appedGfx_npc_blur()
s32 appedGfx_npc_blur ()
Definition at line 176 of file code_13870_len_6980.c.
func_8003B184()
s32 func_8003B184 ()
Definition at line 178 of file code_13870_len_6980.c.
func_8003B198()
s32 func_8003B198 ()
Definition at line 180 of file code_13870_len_6980.c.
func_8003B1A8()
void func_8003B1A8 (void)
Definition at line 182 of file code_13870_len_6980.c.
Referenced by step_battle().
func_8003B1B0()
s32 func_8003B1B0 ()
Definition at line 185 of file code_13870_len_6980.c.
set_npc_yaw()
void set_npc_yaw (Npc * npc, f32 angle)
Definition at line 187 of file code_13870_len_6980.c.
Referenced by func_80240000_8C7F90(), SetNpcYaw(), TeleportPartnerToPlayer(), and UnkNpcAIFunc4().
func_8003B3D0()
s32 func_8003B3D0 ()
Definition at line 199 of file code_13870_len_6980.c.
Referenced by func_802CFE80().
func_8003B3F8()
s32 func_8003B3F8 ()
Definition at line 201 of file code_13870_len_6980.c.
func_8003B420()
s32 func_8003B420 ()
Definition at line 203 of file code_13870_len_6980.c.
func_8003B44C()
s32 func_8003B44C ()
Definition at line 205 of file code_13870_len_6980.c.
Referenced by func_802CFEEC(), and func_802CFFC0().
func_8003B464()
s32 func_8003B464 ()
Definition at line 207 of file code_13870_len_6980.c.
Referenced by func_802CFFC0().
func_8003B47C()
s32 func_8003B47C ()
Definition at line 209 of file code_13870_len_6980.c.
func_8003B500()
s32 func_8003B500 ()
Definition at line 211 of file code_13870_len_6980.c.
func_8003B5B4()
s32 func_8003B5B4 ()
Definition at line 213 of file code_13870_len_6980.c.
func_8003B96C()
s32 func_8003B96C ()
Definition at line 215 of file code_13870_len_6980.c.
func_8003BA60()
s32 func_8003BA60 ()
Definition at line 217 of file code_13870_len_6980.c.
func_8003BED8()
s32 func_8003BED8 ()
Definition at line 219 of file code_13870_len_6980.c.
func_8003C3D8()
s32 func_8003C3D8 ()
Definition at line 221 of file code_13870_len_6980.c.
Referenced by SetNpcEffect().
func_8003C428()
s32 func_8003C428 ()
Definition at line 223 of file code_13870_len_6980.c.
func_8003C444()
s32 func_8003C444 ()
Definition at line 225 of file code_13870_len_6980.c.
func_8003C53C()
s32 func_8003C53C ()
Definition at line 227 of file code_13870_len_6980.c.
func_8003C61C()
s32 func_8003C61C ()
Definition at line 229 of file code_13870_len_6980.c.
func_8003C658()
void func_8003C658 (void)
Definition at line 231 of file code_13870_len_6980.c.
func_8003C660()
void func_8003C660 (void)
Definition at line 234 of file code_13870_len_6980.c.
func_8003C668()
s32 func_8003C668 ()
Definition at line 237 of file code_13870_len_6980.c.
func_8003C78C()
s32 func_8003C78C ()
Definition at line 239 of file code_13870_len_6980.c.
func_8003C7A8()
s32 func_8003C7A8 ()
Definition at line 241 of file code_13870_len_6980.c.
func_8003C8AC()
void func_8003C8AC (void)
Definition at line 243 of file code_13870_len_6980.c.
func_8003C8B4()
s32 func_8003C8B4 ()
Definition at line 246 of file code_13870_len_6980.c.
func_8003C984()
s32 func_8003C984 ()
Definition at line 248 of file code_13870_len_6980.c.
func_8003C9A8()
s32 func_8003C9A8 ()
Definition at line 250 of file code_13870_len_6980.c.
func_8003CB20()
s32 func_8003CB20 ()
Definition at line 252 of file code_13870_len_6980.c.
func_8003CB44()
s32 func_8003CB44 ()
Definition at line 254 of file code_13870_len_6980.c.
func_8003CC8C()
s32 func_8003CC8C ()
Definition at line 256 of file code_13870_len_6980.c.
func_8003CCB0()
s32 func_8003CCB0 ()
Definition at line 258 of file code_13870_len_6980.c.
func_8003CFA0()
void func_8003CFA0 (void)
Definition at line 260 of file code_13870_len_6980.c.
func_8003CFA8()
s32 func_8003CFA8 ()
Definition at line 263 of file code_13870_len_6980.c.
func_8003CFB4()
s32 func_8003CFB4 ()
Definition at line 265 of file code_13870_len_6980.c.
func_8003D0C4()
s32 func_8003D0C4 ()
Definition at line 267 of file code_13870_len_6980.c.
func_8003D1D4()
s32 func_8003D1D4 ()
Definition at line 269 of file code_13870_len_6980.c.
func_8003D2F8()
s32 func_8003D2F8 ()
Definition at line 271 of file code_13870_len_6980.c.
func_8003D3BC()
s32 func_8003D3BC ()
Definition at line 273 of file code_13870_len_6980.c.
func_8003D624()
s32 func_8003D624 ()
Definition at line 275 of file code_13870_len_6980.c.
Referenced by func_800E6860(), and func_802CFD30().
func_8003D660()
s32 func_8003D660 ()
Definition at line 277 of file code_13870_len_6980.c.
Referenced by UnkNpcAIFunc11().
func_8003D788()
s32 func_8003D788 ()
Definition at line 279 of file code_13870_len_6980.c.
func_8003DA38()
s32 func_8003DA38 ()
Definition at line 281 of file code_13870_len_6980.c.
func_8003DC38()
s32 func_8003DC38 ()
Definition at line 283 of file code_13870_len_6980.c.
func_8003DFA0()
s32 func_8003DFA0 ()
Definition at line 285 of file code_13870_len_6980.c.
func_8003E0D4()
s32 func_8003E0D4 ()
Definition at line 287 of file code_13870_len_6980.c.
func_8003E1D0()
s32 func_8003E1D0 ()
Definition at line 289 of file code_13870_len_6980.c.
COPY_set_defeated()
s32 COPY_set_defeated ()
Definition at line 291 of file code_13870_len_6980.c.
func_8003E338()
s32 func_8003E338 ()
Definition at line 293 of file code_13870_len_6980.c.
Referenced by load_engine_data(), and step_init_state().
clear_encounter_status()
s32 clear_encounter_status ()
Definition at line 295 of file code_13870_len_6980.c.
func_8003E50C()
void func_8003E50C (void)
Definition at line 297 of file code_13870_len_6980.c.
func_8003E514()
s32 func_8003E514 ()
Definition at line 300 of file code_13870_len_6980.c.
update_counters()
s32 update_counters ()
Definition at line 302 of file code_13870_len_6980.c.
Referenced by step_battle(), and step_world().
draw_encounter_ui()
s32 draw_encounter_ui ()
Definition at line 304 of file code_13870_len_6980.c.
Referenced by func_80033B54(), and func_80035DA0().
draw_first_strike_ui()
s32 draw_first_strike_ui ()
Definition at line 306 of file code_13870_len_6980.c.
Referenced by func_80035DCC().
func_8003E670()
void func_8003E670 (void)
Definition at line 308 of file code_13870_len_6980.c.
make_npcs()
s32 make_npcs ()
Definition at line 311 of file code_13870_len_6980.c.
Referenced by MakeNpcs().
kill_encounter()
s32 kill_encounter ()
Definition at line 313 of file code_13870_len_6980.c.
kill_enemy()
s32 kill_enemy ()
Definition at line 315 of file code_13870_len_6980.c.
bind_enemy_ai()
s32 bind_enemy_ai ()
Definition at line 317 of file code_13870_len_6980.c.
bind_enemy_aux()
s32 bind_enemy_aux ()
Definition at line 319 of file code_13870_len_6980.c.
bind_enemy_interact()
s32 bind_enemy_interact ()
Definition at line 321 of file code_13870_len_6980.c.
bind_npc_ai()
s32 bind_npc_ai ()
Definition at line 323 of file code_13870_len_6980.c.
bind_npc_aux()
s32 bind_npc_aux ()
Definition at line 325 of file code_13870_len_6980.c.
bind_npc_interact()
s32 bind_npc_interact ()
Definition at line 327 of file code_13870_len_6980.c.
get_enemy()
Enemy * get_enemy (NpcId npcId)
Definition at line 329 of file code_13870_len_6980.c.
Referenced by BindNpcAux(), BindNpcDefeat(), BindNpcHit(), BindNpcIdle(), BindNpcInteract(), EnableNpcAI(), EnableNpcAux(), func_800494C0(), func_80240060_BFA100(), GetNpcVar(), RestartNpcAI(), RestartNpcAux(), set_npc_animation(), SetEnemyFlagBits(), SetNpcVar(), SetTattleString(), and UnkNpcAIFunc9().
get_enemy_safe()
s32 get_enemy_safe ()
Definition at line 331 of file code_13870_len_6980.c.
Referenced by func_802414F8_8D72F8(), func_8024173C_8CF7AC(), func_8024268C_B4D0FC(), and GetGoomba().