src/code_7bb60_len_41b0.c File Reference - Paper Mario Documentation
code_7bb60_len_41b0.c File Reference
Functions
f32 func_800E34D8 (void)
f32 func_800E3514 (f32, f32 *)
void func_800E26B0 (void)
s32 func_800E26C4 (void)
void set_action_state (s32 actionState)
void move_player (s32 duration, f32 heading, f32 speed)
s32 collision_main_above ()
s32 func_800E29C8 ()
s32 func_800E2BB0 ()
s32 update_fall_state ()
s32 func_800E2F60 ()
void gravity_use_fall_params (void)
void func_800E3100 (void)
s32 func_800E315C ()
s32 phys_player_land ()
f32 integrate_gravity (void)
s32 collision_main_lateral ()
s32 collision_check_player_intersecting_world (s32 arg0, s32 arg1, f32 arg2)
s32 func_800E4404 (s32 arg0, s32 arg1, f32 arg2, f32 *outX, f32 *outY, f32 *outZ)
void func_800E4508 (void)
s32 func_800E45E0 ()
s32 func_800E46C8 ()
s32 func_800E4744 ()
void func_800E4AD8 (s32 arg0)
void func_800E4B40 (s32 arg0, f32 *arg1, f32 *arg2, f32 *arg3)
s32 func_800E4BB8 ()
void func_800E4F10 (void)
void check_input_midair_jump (void)
PartnerID get_current_partner_id (void)
void func_800E5098 (s32 arg0)
void func_800E5150 (void)
s32 func_800E5174 ()
s32 can_player_interact ()
s32 func_800E5348 ()
void func_800E546C (void)
void save_ground_pos (void)
void func_800E5520 (void)
s32 func_800E5530 ()
s32 func_800E58F0 ()
s32 func_800E5938 ()
s32 func_800E59A0 ()
s32 func_800E5A2C ()
s32 func_800E5C78 ()
void update_locomotion_state (void)
void start_falling (void)
void start_bounce_a (void)
void start_bounce_b (void)
s32 check_input_hammer (void)
s32 check_input_jump ()
void check_input_spin (void)
void func_800E636C (s32 arg0)
void func_800E63A4 (s32 arg0)
void func_800E6428 (void)
void func_800E6500 (void)
Npc * make_disguise_npc (s32 peachDisguise)
s32 func_800E66C4 ()
Variables
s32 D_8010C96C
s16 D_8010C9B0
Function Documentation
func_800E34D8()
f32 func_800E34D8 (void)
Definition at line 127 of file code_7bb60_len_41b0.c.
Referenced by func_800E3100().
func_800E3514()
f32 func_800E3514 (f32 arg0, f32 * arg1)
Definition at line 136 of file code_7bb60_len_41b0.c.
Referenced by func_800E3100().
func_800E26B0()
void func_800E26B0 (void)
Definition at line 10 of file code_7bb60_len_41b0.c.
func_800E26C4()
s32 func_800E26C4 (void)
Definition at line 16 of file code_7bb60_len_41b0.c.
set_action_state()
void set_action_state (s32 actionState)
Definition at line 350 of file code_7bb60_len_41b0.c.
Referenced by check_input_hammer(), check_input_midair_jump(), check_input_spin(), func_800E0208(), func_800E4F10(), func_800E63A4(), func_800E6428(), func_802E44F8(), func_802E8858(), move_player(), SetPlayerActionState(), start_bounce_a(), start_bounce_b(), start_falling(), update_encounters_conversation(), and update_locomotion_state().
move_player()
void move_player (s32 duration, f32 heading, f32 speed)
Definition at line 53 of file code_7bb60_len_41b0.c.
Referenced by func_80283BD0(), func_802E8BC0(), and PlayerMoveTo().
collision_main_above()
s32 collision_main_above (void)
Definition at line 66 of file code_7bb60_len_41b0.c.
Referenced by func_800DFAAC().
func_800E29C8()
s32 func_800E29C8 ()
Definition at line 68 of file code_7bb60_len_41b0.c.
func_800E2BB0()
s32 func_800E2BB0 ()
Definition at line 70 of file code_7bb60_len_41b0.c.
update_fall_state()
s32 update_fall_state ()
Definition at line 72 of file code_7bb60_len_41b0.c.
Referenced by func_800DFAAC().
func_800E2F60()
s32 func_800E2F60 ()
Definition at line 74 of file code_7bb60_len_41b0.c.
gravity_use_fall_params()
void gravity_use_fall_params (void)
Definition at line 76 of file code_7bb60_len_41b0.c.
Referenced by func_802E44F8().
func_800E3100()
void func_800E3100 (void)
Definition at line 97 of file code_7bb60_len_41b0.c.
Referenced by func_800DFAAC().
func_800E315C()
s32 func_800E315C ()
Definition at line 108 of file code_7bb60_len_41b0.c.
Referenced by func_800E3100().
phys_player_land()
s32 phys_player_land ()
Definition at line 110 of file code_7bb60_len_41b0.c.
integrate_gravity()
f32 integrate_gravity (void)
Definition at line 112 of file code_7bb60_len_41b0.c.
Referenced by func_800E34D8().
collision_main_lateral()
s32 collision_main_lateral ()
Definition at line 138 of file code_7bb60_len_41b0.c.
Referenced by func_800DFAAC(), func_800DFBE8(), and update_player().
collision_check_player_intersecting_world()
s32 collision_check_player_intersecting_world (s32 arg0, s32 arg1, f32 arg2)
Definition at line 142 of file code_7bb60_len_41b0.c.
Referenced by func_800E4AD8().
func_800E4404()
s32 func_800E4404 (s32 arg0, s32 arg1, f32 arg2, f32 * outX, f32 * outY, f32 * outZ)
Definition at line 169 of file code_7bb60_len_41b0.c.
Referenced by func_800E4B40().
func_800E4508()
void func_800E4508 (void)
Definition at line 192 of file code_7bb60_len_41b0.c.
Referenced by func_800DFAAC().
func_800E45E0()
s32 func_800E45E0 ()
Definition at line 216 of file code_7bb60_len_41b0.c.
func_800E46C8()
s32 func_800E46C8 ()
Definition at line 218 of file code_7bb60_len_41b0.c.
func_800E4744()
s32 func_800E4744 ()
Definition at line 220 of file code_7bb60_len_41b0.c.
Referenced by func_800DFAAC().
func_800E4AD8()
void func_800E4AD8 (s32 arg0)
Definition at line 222 of file code_7bb60_len_41b0.c.
func_800E4B40()
void func_800E4B40 (s32 arg0, f32 * arg1, f32 * arg2, f32 * arg3)
Definition at line 228 of file code_7bb60_len_41b0.c.
func_800E4BB8()
s32 func_800E4BB8 ()
Definition at line 234 of file code_7bb60_len_41b0.c.
Referenced by func_800DFBE8().
func_800E4F10()
void func_800E4F10 (void)
Definition at line 236 of file code_7bb60_len_41b0.c.
Referenced by func_800DFAAC().
check_input_midair_jump()
void check_input_midair_jump (void)
Definition at line 253 of file code_7bb60_len_41b0.c.
Referenced by func_800DFAAC().
get_current_partner_id()
PartnerID get_current_partner_id (void)
Definition at line 274 of file code_7bb60_len_41b0.c.
func_800E5098()
void func_800E5098 (s32 arg0)
Definition at line 278 of file code_7bb60_len_41b0.c.
func_800E5150()
void func_800E5150 (void)
Definition at line 304 of file code_7bb60_len_41b0.c.
func_800E5174()
s32 func_800E5174 ()
Definition at line 308 of file code_7bb60_len_41b0.c.
Referenced by func_800E5150().
can_player_interact()
s32 can_player_interact ()
Definition at line 310 of file code_7bb60_len_41b0.c.
Referenced by should_collider_allow_interact().
func_800E5348()
s32 func_800E5348 ()
Definition at line 312 of file code_7bb60_len_41b0.c.
func_800E546C()
void func_800E546C (void)
Definition at line 314 of file code_7bb60_len_41b0.c.
Referenced by func_802E88EC().
save_ground_pos()
void save_ground_pos (void)
Definition at line 326 of file code_7bb60_len_41b0.c.
func_800E5520()
void func_800E5520 (void)
Definition at line 334 of file code_7bb60_len_41b0.c.
Referenced by func_800DFC74().
func_800E5530()
s32 func_800E5530 ()
Definition at line 338 of file code_7bb60_len_41b0.c.
func_800E58F0()
s32 func_800E58F0 ()
Definition at line 340 of file code_7bb60_len_41b0.c.
func_800E5938()
s32 func_800E5938 ()
Definition at line 342 of file code_7bb60_len_41b0.c.
func_800E59A0()
s32 func_800E59A0 ()
Definition at line 344 of file code_7bb60_len_41b0.c.
func_800E5A2C()
s32 func_800E5A2C ()
Definition at line 346 of file code_7bb60_len_41b0.c.
Referenced by func_800DFAAC(), func_800DFBE8(), and update_player().
func_800E5C78()
s32 func_800E5C78 ()
Definition at line 348 of file code_7bb60_len_41b0.c.
update_locomotion_state()
void update_locomotion_state (void)
Definition at line 424 of file code_7bb60_len_41b0.c.
start_falling()
void start_falling (void)
Definition at line 432 of file code_7bb60_len_41b0.c.
start_bounce_a()
void start_bounce_a (void)
Definition at line 442 of file code_7bb60_len_41b0.c.
start_bounce_b()
void start_bounce_b (void)
Definition at line 452 of file code_7bb60_len_41b0.c.
check_input_hammer()
s32 check_input_hammer (void)
Definition at line 463 of file code_7bb60_len_41b0.c.
check_input_jump()
s32 check_input_jump ()
Definition at line 481 of file code_7bb60_len_41b0.c.
check_input_spin()
void check_input_spin (void)
Definition at line 483 of file code_7bb60_len_41b0.c.
func_800E636C()
void func_800E636C (s32 arg0)
Definition at line 517 of file code_7bb60_len_41b0.c.
func_800E63A4()
void func_800E63A4 (s32 arg0)
Definition at line 525 of file code_7bb60_len_41b0.c.
func_800E6428()
void func_800E6428 (void)
Definition at line 541 of file code_7bb60_len_41b0.c.
func_800E6500()
void func_800E6500 (void)
Definition at line 570 of file code_7bb60_len_41b0.c.
make_disguise_npc()
Npc * make_disguise_npc (s32 peachDisguise)
Definition at line 588 of file code_7bb60_len_41b0.c.
Referenced by func_800E6428().
func_800E66C4()
s32 func_800E66C4 ()
Definition at line 590 of file code_7bb60_len_41b0.c.
Variable Documentation
D_8010C96C
s32 D_8010C96C extern
Referenced by func_800E636C(), func_800E63A4(), and func_800E6500().
D_8010C9B0
s16 D_8010C9B0 extern
Referenced by func_800E5520().