src/code_B9D60.c File Reference - Paper Mario Documentation
code_B9D60.c File Reference
Functions
void clear_character_set (void)
s32 clear_printers ()
s32 load_font_data ()
s32 load_font ()
s32 update_messages ()
s32 _update_message ()
s32 render_messages ()
s32 func_80124434 ()
s32 func_80124570 ()
s32 initialize_printer ()
s32 dma_load_string ()
s32 load_message_to_buffer ()
PrintContext * load_string (s32 stringID, s32 *a1)
s32 _load_string ()
s32 load_message_to_printer ()
s32 clamp_printer_coords ()
s32 cancel_message (PrintContext *printContext)
void set_message_images (s32 *images)
s32 set_message_string ()
s32 set_message_value ()
void close_message (PrintContext *printContext)
s32 func_80125C84 ()
s32 get_char_width ()
s32 get_string_properties ()
s32 get_string_width ()
s32 func_801264B0 ()
s32 draw_string ()
s32 func_80126790 ()
s32 func_80126EAC ()
s32 func_80126F78 ()
s32 draw_digit ()
s32 draw_number ()
void func_80127B70 (s32 arg0)
s32 func_80127BA4 ()
s32 func_80127D90 ()
s32 func_8012C2E0 ()
s32 func_8012C324 ()
s32 func_8012C9A8 ()
s32 func_8012CA08 ()
s32 _draw_message_box ()
s32 func_8012D3DC ()
s32 func_8012DB58 ()
s32 func_8012E8E0 ()
s32 func_8012E9A0 ()
s32 func_8012EC94 ()
s32 func_8012F500 ()
s32 func_8012FE10 ()
s32 func_8012FE78 ()
s32 func_801309F0 ()
s32 func_80130A04 ()
s32 func_80130ACC ()
s32 draw_coin_sparkles ()
ItemEntity * get_item_entity (s32 itemEntityIndex)
s32 func_80130F70 ()
s32 func_80130FAC ()
s32 clear_item_entity_data ()
s32 init_item_entity_list ()
s32 func_80131128 ()
s32 make_item_entity (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 facingAngleSign, s32 pickupVar)
s32 make_item_entity_nodelay (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupVar)
s32 make_item_entity_delayed (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 pickupVar)
s32 init_got_item ()
s32 func_80131DD4 ()
s32 update_item_entities ()
s32 appendGfx_item_entity ()
s32 draw_item_entities ()
s32 func_80132D94 ()
s32 render_item_entities ()
s32 remove_item_entity_by_reference ()
s32 remove_item_entity_by_index ()
s32 func_80133A94 ()
s32 test_item_player_collision ()
s32 func_80133FC8 ()
void set_item_entity_flags (s32 index, s32 flags)
void clear_item_entity_flags (s32 index, s32 flags)
void func_801341B0 (s32 index)
s32 func_801341E8 (void)
void set_item_entity_position (s32 itemEntityIndex, f32 x, f32 y, f32 z)
void func_80134230 (s32 arg0)
s32 func_80134240 (void)
s32 update_item_entity_collectable ()
s32 func_8013559C ()
s32 update_item_entity_static ()
void func_801356C4 (void)
void func_801356CC (void)
void func_801356D4 (void)
s32 update_item_entity_temp ()
s32 func_801363A0 ()
s32 func_8013673C ()
s32 func_801369D0 ()
s32 func_80136A08 ()
Variables
s32 D_801512F4
s16 D_80155C98
s32 D_80155D88
ItemEntity ** D_801565A0
s16 D_801565A4
s16 D_801565A8
Function Documentation
clear_character_set()
void clear_character_set (void)
Definition at line 10 of file code_B9D60.c.
clear_printers()
s32 clear_printers ()
Definition at line 14 of file code_B9D60.c.
Referenced by step_init_state().
load_font_data()
s32 load_font_data ()
Definition at line 16 of file code_B9D60.c.
load_font()
s32 load_font ()
Definition at line 18 of file code_B9D60.c.
update_messages()
s32 update_messages ()
Definition at line 20 of file code_B9D60.c.
_update_message()
s32 _update_message ()
Definition at line 22 of file code_B9D60.c.
render_messages()
s32 render_messages ()
Definition at line 24 of file code_B9D60.c.
func_80124434()
s32 func_80124434 ()
Definition at line 26 of file code_B9D60.c.
func_80124570()
s32 func_80124570 ()
Definition at line 28 of file code_B9D60.c.
initialize_printer()
s32 initialize_printer ()
Definition at line 30 of file code_B9D60.c.
dma_load_string()
s32 dma_load_string ()
Definition at line 32 of file code_B9D60.c.
load_message_to_buffer()
s32 load_message_to_buffer ()
Definition at line 34 of file code_B9D60.c.
load_string()
PrintContext* load_string (s32 stringID, s32 * a1)
Definition at line 36 of file code_B9D60.c.
Referenced by ActorSpeak(), and ShowBattleChoice().
_load_string()
s32 _load_string ()
Definition at line 40 of file code_B9D60.c.
Referenced by load_string().
load_message_to_printer()
s32 load_message_to_printer ()
Definition at line 42 of file code_B9D60.c.
Referenced by SwitchMessage().
clamp_printer_coords()
s32 clamp_printer_coords ()
Definition at line 44 of file code_B9D60.c.
cancel_message()
s32 cancel_message (PrintContext * printContext)
Definition at line 46 of file code_B9D60.c.
Referenced by CancelMessage(), and CancelMessageAndBlock().
set_message_images()
void set_message_images (s32 * images)
Definition at line 55 of file code_B9D60.c.
Referenced by SetMessageImages().
set_message_string()
s32 set_message_string ()
Definition at line 59 of file code_B9D60.c.
Referenced by SetMessageString().
set_message_value()
s32 set_message_value ()
Definition at line 61 of file code_B9D60.c.
Referenced by SetMessageValue().
close_message()
void close_message (PrintContext * printContext)
Definition at line 63 of file code_B9D60.c.
Referenced by CloseChoice(), and CloseMessage().
func_80125C84()
s32 func_80125C84 ()
Definition at line 67 of file code_B9D60.c.
get_char_width()
s32 get_char_width ()
Definition at line 69 of file code_B9D60.c.
get_string_properties()
s32 get_string_properties ()
Definition at line 71 of file code_B9D60.c.
get_string_width()
s32 get_string_width ()
Definition at line 73 of file code_B9D60.c.
func_801264B0()
s32 func_801264B0 ()
Definition at line 75 of file code_B9D60.c.
draw_string()
s32 draw_string ()
Definition at line 77 of file code_B9D60.c.
func_80126790()
s32 func_80126790 ()
Definition at line 79 of file code_B9D60.c.
func_80126EAC()
s32 func_80126EAC ()
Definition at line 81 of file code_B9D60.c.
func_80126F78()
s32 func_80126F78 ()
Definition at line 83 of file code_B9D60.c.
draw_digit()
s32 draw_digit ()
Definition at line 85 of file code_B9D60.c.
draw_number()
s32 draw_number ()
Definition at line 87 of file code_B9D60.c.
Referenced by coin_counter_draw_content().
func_80127B70()
void func_80127B70 (s32 arg0)
Definition at line 89 of file code_B9D60.c.
func_80127BA4()
s32 func_80127BA4 ()
Definition at line 93 of file code_B9D60.c.
func_80127D90()
s32 func_80127D90 ()
Definition at line 95 of file code_B9D60.c.
Referenced by func_80127B70().
func_8012C2E0()
s32 func_8012C2E0 ()
Definition at line 97 of file code_B9D60.c.
func_8012C324()
s32 func_8012C324 ()
Definition at line 99 of file code_B9D60.c.
func_8012C9A8()
s32 func_8012C9A8 ()
Definition at line 101 of file code_B9D60.c.
func_8012CA08()
s32 func_8012CA08 ()
Definition at line 103 of file code_B9D60.c.
_draw_message_box()
s32 _draw_message_box ()
Definition at line 105 of file code_B9D60.c.
func_8012D3DC()
s32 func_8012D3DC ()
Definition at line 107 of file code_B9D60.c.
func_8012DB58()
s32 func_8012DB58 ()
Definition at line 109 of file code_B9D60.c.
func_8012E8E0()
s32 func_8012E8E0 ()
Definition at line 111 of file code_B9D60.c.
func_8012E9A0()
s32 func_8012E9A0 ()
Definition at line 113 of file code_B9D60.c.
func_8012EC94()
s32 func_8012EC94 ()
Definition at line 115 of file code_B9D60.c.
func_8012F500()
s32 func_8012F500 ()
Definition at line 117 of file code_B9D60.c.
func_8012FE10()
s32 func_8012FE10 ()
Definition at line 119 of file code_B9D60.c.
func_8012FE78()
s32 func_8012FE78 ()
Definition at line 121 of file code_B9D60.c.
func_801309F0()
s32 func_801309F0 ()
Definition at line 123 of file code_B9D60.c.
func_80130A04()
s32 func_80130A04 ()
Definition at line 125 of file code_B9D60.c.
func_80130ACC()
s32 func_80130ACC ()
Definition at line 127 of file code_B9D60.c.
draw_coin_sparkles()
s32 draw_coin_sparkles ()
Definition at line 129 of file code_B9D60.c.
get_item_entity()
ItemEntity* get_item_entity (s32 itemEntityIndex)
Definition at line 131 of file code_B9D60.c.
Referenced by func_802D721C(), SetItemFlags(), SetItemPos(), ShowGotItem(), and SomeItemEntityFunc().
func_80130F70()
s32 func_80130F70 ()
Definition at line 135 of file code_B9D60.c.
func_80130FAC()
s32 func_80130FAC ()
Definition at line 137 of file code_B9D60.c.
clear_item_entity_data()
s32 clear_item_entity_data ()
Definition at line 139 of file code_B9D60.c.
Referenced by step_init_state().
init_item_entity_list()
s32 init_item_entity_list ()
Definition at line 141 of file code_B9D60.c.
func_80131128()
s32 func_80131128 ()
Definition at line 143 of file code_B9D60.c.
make_item_entity()
s32 make_item_entity (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 facingAngleSign, s32 pickupVar)
Definition at line 148 of file code_B9D60.c.
Referenced by make_item_entity_delayed(), and make_item_entity_nodelay().
make_item_entity_nodelay()
s32 make_item_entity_nodelay (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupVar)
Definition at line 150 of file code_B9D60.c.
Referenced by DropItemEntity(), DropItemEntityB(), and MakeItemEntity().
make_item_entity_delayed()
s32 make_item_entity_delayed (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 pickupVar)
Definition at line 154 of file code_B9D60.c.
Referenced by OnFleeBattleDrops().
init_got_item()
s32 init_got_item ()
Definition at line 158 of file code_B9D60.c.
Referenced by ShowGotItem().
func_80131DD4()
s32 func_80131DD4 ()
Definition at line 160 of file code_B9D60.c.
update_item_entities()
s32 update_item_entities ()
Definition at line 162 of file code_B9D60.c.
Referenced by step_world().
appendGfx_item_entity()
s32 appendGfx_item_entity ()
Definition at line 164 of file code_B9D60.c.
draw_item_entities()
s32 draw_item_entities ()
Definition at line 166 of file code_B9D60.c.
func_80132D94()
s32 func_80132D94 ()
Definition at line 168 of file code_B9D60.c.
render_item_entities()
s32 render_item_entities ()
Definition at line 170 of file code_B9D60.c.
remove_item_entity_by_reference()
s32 remove_item_entity_by_reference ()
Definition at line 172 of file code_B9D60.c.
remove_item_entity_by_index()
s32 remove_item_entity_by_index ()
Definition at line 174 of file code_B9D60.c.
Referenced by RemoveItemEntity().
func_80133A94()
s32 func_80133A94 ()
Definition at line 176 of file code_B9D60.c.
test_item_player_collision()
s32 test_item_player_collision ()
Definition at line 178 of file code_B9D60.c.
func_80133FC8()
s32 func_80133FC8 ()
Definition at line 180 of file code_B9D60.c.
set_item_entity_flags()
void set_item_entity_flags (s32 index, s32 flags)
Definition at line 182 of file code_B9D60.c.
Referenced by DropItemEntityB(), func_80240000_800880(), and func_80240044_8008C4().
clear_item_entity_flags()
void clear_item_entity_flags (s32 index, s32 flags)
Definition at line 191 of file code_B9D60.c.
func_801341B0()
void func_801341B0 (s32 index)
Definition at line 197 of file code_B9D60.c.
func_801341E8()
s32 func_801341E8 (void)
Definition at line 205 of file code_B9D60.c.
set_item_entity_position()
void set_item_entity_position (s32 itemEntityIndex, f32 x, f32 y, f32 z)
Definition at line 214 of file code_B9D60.c.
Referenced by Bandit_DropCoin().
func_80134230()
void func_80134230 (s32 arg0)
Definition at line 222 of file code_B9D60.c.
Referenced by func_80282774(), and func_802827A8().
func_80134240()
s32 func_80134240 (void)
Definition at line 226 of file code_B9D60.c.
Referenced by func_80282774().
update_item_entity_collectable()
s32 update_item_entity_collectable ()
Definition at line 230 of file code_B9D60.c.
func_8013559C()
s32 func_8013559C ()
Definition at line 232 of file code_B9D60.c.
update_item_entity_static()
s32 update_item_entity_static ()
Definition at line 234 of file code_B9D60.c.
func_801356C4()
void func_801356C4 (void)
Definition at line 236 of file code_B9D60.c.
func_801356CC()
void func_801356CC (void)
Definition at line 239 of file code_B9D60.c.
func_801356D4()
void func_801356D4 (void)
Definition at line 242 of file code_B9D60.c.
update_item_entity_temp()
s32 update_item_entity_temp ()
Definition at line 245 of file code_B9D60.c.
func_801363A0()
s32 func_801363A0 ()
Definition at line 247 of file code_B9D60.c.
func_8013673C()
s32 func_8013673C ()
Definition at line 249 of file code_B9D60.c.
func_801369D0()
s32 func_801369D0 ()
Definition at line 251 of file code_B9D60.c.
func_80136A08()
s32 func_80136A08 ()
Definition at line 253 of file code_B9D60.c.
Variable Documentation
D_801512F4
s32 D_801512F4 extern
Referenced by set_message_images().
D_80155C98
s16 D_80155C98 extern
Referenced by clear_character_set().
D_80155D88
s32 D_80155D88 extern
Referenced by func_80134230(), and func_80134240().
D_801565A0
ItemEntity** D_801565A0
Definition at line 6 of file code_B9D60.c.
Referenced by clear_item_entity_flags(), func_801341B0(), get_item_entity(), set_item_entity_flags(), and set_item_entity_position().
D_801565A4
s16 D_801565A4 extern
Referenced by func_801341E8().
D_801565A8
s16 D_801565A8 extern
Referenced by func_801341E8(), and set_item_entity_flags().