src/code_197F40.c File Reference - Paper Mario Documentation
code_197F40.c File Reference
Functions
s32 count_targets (Actor *actor, s32 targetHomeIndex, s32 targetSelectionFlags)
s32 get_nearest_home_index (f32 x, f32 y, f32 z)
void set_goal_pos_to_part (f32 *goalPos, ActorID target, s32 partIndex)
s32 set_part_goal_to_actor_part ()
void set_actor_current_position (ActorID actorID, f32 x, f32 y, f32 z)
void set_part_absolute_position (ActorID actorID, s32 partIndex, f32 x, f32 y, f32 z)
void set_actor_home_position (ActorID actorID, f32 x, f32 y, f32 z)
Actor * get_actor (s32 actorID)
s32 LoadBattleSection ()
ApiStatus GetBattlePhase (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetLastElement (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_80269E80 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_80269EAC (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetGoalToHome (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetIdleGoalToHome (ScriptInstance *script, s32 isInitialCall)
s32 SetGoalToIndex ()
ApiStatus GetIndexFromPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetIndexFromHome (ScriptInstance *script, s32 isInitialCall)
ApiStatus CountPlayerTargets (ScriptInstance *script, s32 isInitialCall)
ApiStatus ForceHomePos (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetHomePos (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetGoalToTarget (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartGoalToTarget (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetGoalToFirstTarget (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetGoalPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetIdleGoal (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddGoalPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetGoalPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetIdleGoal (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPartTarget (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetActorPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPartOffset (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPartPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetHomePos (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetEnemyTargetOffset (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetAnimationRate (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorYaw (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetActorYaw (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartYaw (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPartYaw (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorJumpGravity (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorIdleJumpGravity (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorSpeed (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorIdleSpeed (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartJumpGravity (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartMoveSpeed (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetJumpAnimations (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddActorPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorDispOffset (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPartDispOffset (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartDispOffset (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddPartDispOffset (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8026BF48 (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetActorVar (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorVar (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddActorVar (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPartMovementVar (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartMovementVar (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddPartMovementVar (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorRotation (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorRotationOffset (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetActorRotation (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartRotation (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartRotationOffset (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPartRotation (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorScale (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorScaleModifier (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetActorScale (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartScale (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPartScale (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetBattleFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetBattleFlagBits (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetBattleFlags2 (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetBattleFlagBits2 (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorFlagBits (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetActorFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartFlagBits (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartTargetFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartTargetFlagBits (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPartFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPartTargetFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartEventFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPartEventBits (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPartEventFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8026D51C (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8026D5A4 (ScriptInstance *script, s32 isInitialCall)
ApiStatus HPBarToHome (ScriptInstance *script, s32 isInitialCall)
ApiStatus HPBarToCurrent (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8026D8EC (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8026D940 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8026DA94 (ScriptInstance *script, s32 isInitialCall)
s32 SummonEnemy ()
ApiStatus GetOwnerID (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetOwnerID (ScriptInstance *script, s32 isInitialCall)
ApiStatus ActorExists (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8026DEF0 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8026DF88 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8026E020 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8026E038 (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetBattleInputMask (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetBattleInputButtons (ScriptInstance *script, s32 isInitialCall)
ApiStatus CheckButtonPress (ScriptInstance *script, s32 isInitialCall)
ApiStatus CheckButtonHeld (ScriptInstance *script, s32 isInitialCall)
ApiStatus CheckButtonDown (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetBattleState (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8026E16C (ScriptInstance *script, s32 isInitialCall)
s32 func_8026E198 ()
s32 func_8026E208 ()
s32 func_8026E260 ()
ApiStatus PlayerCreateTargetList (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnemyCreateTargetList (ScriptInstance *script, s32 isInitialCall)
s32 InitTargetIterator ()
s32 SetOwnerTarget ()
s32 ChooseNextTarget ()
s32 func_8026E558 ()
ApiStatus GetTargetListLength (ScriptInstance *script)
s32 GetOwnerTarget ()
s32 func_8026E914 ()
ApiStatus GetAttackerActorID (ScriptInstance *script, s32 isInitialCall)
s32 func_8026E9A0 ()
s32 GetDistanceToGoal ()
s32 func_8026EA7C ()
s32 func_8026EB20 ()
s32 func_8026EBF8 ()
s32 func_8026ED20 ()
s32 func_8026EDE4 ()
s32 AddActorDecoration ()
s32 RemoveActorDecoration ()
s32 ModifyActorDecoration ()
s32 UseIdleAnimation ()
s32 func_8026F1A0 ()
s32 GetStatusFlags ()
ApiStatus RemovePlayerBuffs (ScriptInstance *script, s32 isInitialCall)
s32 SetPartAlpha ()
s32 CreatePartShadow ()
s32 RemovePartShadow ()
ApiStatus func_8026F60C (ScriptInstance *script, s32 isInitialCall)
s32 SetBattleVar ()
s32 GetBattleVar ()
s32 ResetAllActorSounds ()
s32 SetActorSounds ()
s32 ResetActorSounds ()
s32 SetPartSounds ()
s32 SetActorType ()
s32 ShowShockEffect ()
s32 GetActorAttackBoost ()
s32 GetActorDefenseBoost ()
s32 BoostAttack ()
s32 BoostDefense ()
s32 VanishActor ()
s32 ElectrifyActor ()
s32 HealActor ()
s32 WaitForBuffDone ()
s32 CopyBuffs ()
s32 func_80271210 ()
s32 func_80271258 ()
s32 func_802712A0 ()
s32 func_80271328 ()
s32 func_802713B0 ()
s32 func_8027143C ()
s32 func_80271484 ()
s32 func_80271588 ()
s32 dispatch_event_player ()
s32 dispatch_event_player_continue_turn ()
s32 calc_player_test_enemy ()
s32 calc_player_damage_enemy ()
s32 dispatch_damage_event_player ()
void dispatch_damage_event_player_0 (s32 damageAmount, Event event)
void dispatch_damage_event_player_1 (s32 damageAmount, Event event)
s32 GetMenuSelection ()
s32 func_80273444 ()
s32 PlayerFallToGoal ()
s32 PlayerLandJump ()
s32 PlayerRunToGoal ()
s32 CancelablePlayerRunToGoal ()
ApiStatus GetPlayerHP (ScriptInstance *script, s32 isInitialCall)
s32 PlayerDamageEnemy ()
s32 PlayerPowerBounceEnemy ()
s32 PlayerTestEnemy ()
s32 DispatchDamagePlayerEvent ()
s32 EnablePlayerBlur ()
ApiStatus func_802749D8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802749F8 (ScriptInstance *script, s32 isInitialCall)
s32 func_80274A18 ()
s32 func_802752AC ()
s32 func_80275F00 ()
s32 DidActionSucceed ()
ApiStatus func_80276EFC (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_80276F1C (ScriptInstance *script, s32 isInitialCall)
Function Documentation
count_targets()
s32 count_targets (Actor * actor, s32 targetHomeIndex, s32 targetSelectionFlags)
Definition at line 3 of file code_197F40.c.
Referenced by CountPlayerTargets().
get_nearest_home_index()
s32 get_nearest_home_index (f32 x, f32 y, f32 z)
Definition at line 12 of file code_197F40.c.
Referenced by CountPlayerTargets(), GetIndexFromHome(), and GetIndexFromPos().
set_goal_pos_to_part()
void set_goal_pos_to_part (f32 * goalPos, ActorID target, s32 partIndex)
Definition at line 39 of file code_197F40.c.
Referenced by SetGoalToFirstTarget(), and SetGoalToTarget().
set_part_goal_to_actor_part()
s32 set_part_goal_to_actor_part ()
Definition at line 41 of file code_197F40.c.
Referenced by SetPartGoalToTarget().
set_actor_current_position()
void set_actor_current_position (ActorID actorID, f32 x, f32 y, f32 z)
Definition at line 43 of file code_197F40.c.
set_part_absolute_position()
void set_part_absolute_position (ActorID actorID, s32 partIndex, f32 x, f32 y, f32 z)
Definition at line 51 of file code_197F40.c.
set_actor_home_position()
void set_actor_home_position (ActorID actorID, f32 x, f32 y, f32 z)
Definition at line 71 of file code_197F40.c.
get_actor()
Actor* get_actor (s32 actorID)
Definition at line 79 of file code_197F40.c.
Referenced by ActorExists(), ActorSpeak(), AddActorPos(), AddActorVar(), AddGoalPos(), AddPartDispOffset(), AddPartMovementVar(), ApplyShrinkFromOwner(), BindHandleEvent(), BindIdle(), BindNextTurn(), BindTakeTurn(), calc_item_check_hit(), CountPlayerTargets(), create_part_shadow(), DispatchDamageEvent(), DispatchEvent(), EnableActorBlur(), EnemyCreateTargetList(), ForceHomePos(), func_80252B3C(), func_80261D98(), func_8026D51C(), func_8026D5A4(), func_8026D8EC(), func_8026D940(), func_8026DA94(), func_8026DEF0(), func_8026DF88(), func_8027D2D8(), func_8027D32C(), func_8027D434(), func_8027D628(), func_8027D75C(), GetActorFlags(), GetActorLevel(), GetActorPos(), GetActorRotation(), GetActorScale(), GetActorSize(), GetActorVar(), GetActorYaw(), GetAnimation(), GetCurrentActorType(), GetEnemyMaxHP(), GetGoalPos(), GetHomePos(), GetIdleGoal(), GetIndexFromHome(), GetIndexFromPos(), GetLastDamage(), GetLastEvent(), GetOriginalActorType(), GetPartDispOffset(), GetPartEventFlags(), GetPartFlags(), GetPartMovementVar(), GetPartOffset(), GetPartPos(), GetPartRotation(), GetPartScale(), GetPartTarget(), GetPartTargetFlags(), GetPartYaw(), GetTargetListLength(), HPBarToCurrent(), HPBarToHome(), ItemAfflictEnemy(), ItemCheckHit(), ItemDamageEnemy(), MultiplyByActorScale(), MultiplyVec2ByActorScale(), MultiplyVec3yActorScale(), PauseTakeTurn(), PlayerCreateTargetList(), PlayLoopingSoundAtActor(), PlaySoundAtActor(), PlaySoundAtPart(), remove_part_shadow(), ResumeTakeTurn(), set_actor_current_position(), set_actor_home_position(), set_actor_yaw(), set_part_absolute_position(), set_part_yaw(), SetActorDispOffset(), SetActorFlagBits(), SetActorFlags(), SetActorIdleJumpGravity(), SetActorIdleSpeed(), SetActorJumpGravity(), SetActorPos(), SetActorRotation(), SetActorRotationOffset(), SetActorScale(), SetActorScaleModifier(), SetActorSpeed(), SetActorVar(), SetDefenseTable(), SetEnemyTargetOffset(), SetGoalPos(), SetGoalToFirstTarget(), SetGoalToHome(), SetGoalToTarget(), SetHomePos(), SetIdleAnimations(), SetIdleGoal(), SetIdleGoalToHome(), SetJumpAnimations(), SetPartDispOffset(), SetPartEventBits(), SetPartEventFlags(), SetPartFlagBits(), SetPartFlags(), SetPartGoalToTarget(), SetPartJumpGravity(), SetPartMovementVar(), SetPartMoveSpeed(), SetPartPos(), SetPartRotation(), SetPartRotationOffset(), SetPartScale(), SetPartTargetFlagBits(), SetPartTargetFlags(), SetStatusTable(), SetTargetActor(), and StopLoopingSoundAtActor().
LoadBattleSection()
s32 LoadBattleSection ()
Definition at line 99 of file code_197F40.c.
GetBattlePhase()
ApiStatus GetBattlePhase (ScriptInstance * script, s32 isInitialCall)
Definition at line 101 of file code_197F40.c.
GetLastElement()
ApiStatus GetLastElement (ScriptInstance * script, s32 isInitialCall)
Definition at line 106 of file code_197F40.c.
func_80269E80()
ApiStatus func_80269E80 (ScriptInstance * script, s32 isInitialCall)
Definition at line 111 of file code_197F40.c.
func_80269EAC()
ApiStatus func_80269EAC (ScriptInstance * script, s32 isInitialCall)
Definition at line 116 of file code_197F40.c.
SetGoalToHome()
ApiStatus SetGoalToHome (ScriptInstance * script, s32 isInitialCall)
Definition at line 123 of file code_197F40.c.
SetIdleGoalToHome()
ApiStatus SetIdleGoalToHome (ScriptInstance * script, s32 isInitialCall)
Definition at line 139 of file code_197F40.c.
SetGoalToIndex()
s32 SetGoalToIndex ()
Definition at line 155 of file code_197F40.c.
GetIndexFromPos()
ApiStatus GetIndexFromPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 157 of file code_197F40.c.
GetIndexFromHome()
ApiStatus GetIndexFromHome (ScriptInstance * script, s32 isInitialCall)
Definition at line 173 of file code_197F40.c.
CountPlayerTargets()
ApiStatus CountPlayerTargets (ScriptInstance * script, s32 isInitialCall)
Definition at line 189 of file code_197F40.c.
ForceHomePos()
ApiStatus ForceHomePos (ScriptInstance * script, s32 isInitialCall)
Definition at line 207 of file code_197F40.c.
SetHomePos()
ApiStatus SetHomePos (ScriptInstance * script, s32 isInitialCall)
Definition at line 232 of file code_197F40.c.
SetGoalToTarget()
ApiStatus SetGoalToTarget (ScriptInstance * script, s32 isInitialCall)
Definition at line 254 of file code_197F40.c.
SetPartGoalToTarget()
ApiStatus SetPartGoalToTarget (ScriptInstance * script, s32 isInitialCall)
Definition at line 269 of file code_197F40.c.
SetGoalToFirstTarget()
ApiStatus SetGoalToFirstTarget (ScriptInstance * script, s32 isInitialCall)
Definition at line 285 of file code_197F40.c.
SetGoalPos()
ApiStatus SetGoalPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 302 of file code_197F40.c.
SetIdleGoal()
ApiStatus SetIdleGoal (ScriptInstance * script, s32 isInitialCall)
Definition at line 342 of file code_197F40.c.
AddGoalPos()
ApiStatus AddGoalPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 381 of file code_197F40.c.
GetGoalPos()
ApiStatus GetGoalPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 403 of file code_197F40.c.
GetIdleGoal()
ApiStatus GetIdleGoal (ScriptInstance * script, s32 isInitialCall)
Definition at line 432 of file code_197F40.c.
GetPartTarget()
ApiStatus GetPartTarget (ScriptInstance * script, s32 isInitialCall)
Definition at line 460 of file code_197F40.c.
GetActorPos()
ApiStatus GetActorPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 491 of file code_197F40.c.
GetPartOffset()
ApiStatus GetPartOffset (ScriptInstance * script, s32 isInitialCall)
Definition at line 519 of file code_197F40.c.
GetPartPos()
ApiStatus GetPartPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 555 of file code_197F40.c.
GetHomePos()
ApiStatus GetHomePos (ScriptInstance * script, s32 isInitialCall)
Definition at line 585 of file code_197F40.c.
SetActorPos()
ApiStatus SetActorPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 613 of file code_197F40.c.
SetPartPos()
ApiStatus SetPartPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 635 of file code_197F40.c.
SetEnemyTargetOffset()
ApiStatus SetEnemyTargetOffset (ScriptInstance * script, s32 isInitialCall)
Definition at line 679 of file code_197F40.c.
SetAnimation()
ApiStatus SetAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 711 of file code_197F40.c.
GetAnimation()
ApiStatus GetAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 725 of file code_197F40.c.
SetAnimationRate()
ApiStatus SetAnimationRate (ScriptInstance * script, s32 isInitialCall)
Definition at line 746 of file code_197F40.c.
SetActorYaw()
ApiStatus SetActorYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 760 of file code_197F40.c.
GetActorYaw()
ApiStatus GetActorYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 772 of file code_197F40.c.
SetPartYaw()
ApiStatus SetPartYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 787 of file code_197F40.c.
GetPartYaw()
ApiStatus GetPartYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 799 of file code_197F40.c.
SetActorJumpGravity()
ApiStatus SetActorJumpGravity (ScriptInstance * script, s32 isInitialCall)
Definition at line 816 of file code_197F40.c.
SetActorIdleJumpGravity()
ApiStatus SetActorIdleJumpGravity (ScriptInstance * script, s32 isInitialCall)
Definition at line 830 of file code_197F40.c.
SetActorSpeed()
ApiStatus SetActorSpeed (ScriptInstance * script, s32 isInitialCall)
Definition at line 844 of file code_197F40.c.
SetActorIdleSpeed()
ApiStatus SetActorIdleSpeed (ScriptInstance * script, s32 isInitialCall)
Definition at line 859 of file code_197F40.c.
SetPartJumpGravity()
ApiStatus SetPartJumpGravity (ScriptInstance * script, s32 isInitialCall)
Definition at line 873 of file code_197F40.c.
SetPartMoveSpeed()
ApiStatus SetPartMoveSpeed (ScriptInstance * script, s32 isInitialCall)
Definition at line 890 of file code_197F40.c.
SetJumpAnimations()
ApiStatus SetJumpAnimations (ScriptInstance * script, s32 isInitialCall)
Definition at line 907 of file code_197F40.c.
AddActorPos()
ApiStatus AddActorPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 934 of file code_197F40.c.
SetActorDispOffset()
ApiStatus SetActorDispOffset (ScriptInstance * script, s32 isInitialCall)
Definition at line 956 of file code_197F40.c.
GetPartDispOffset()
ApiStatus GetPartDispOffset (ScriptInstance * script, s32 isInitialCall)
Definition at line 978 of file code_197F40.c.
SetPartDispOffset()
ApiStatus SetPartDispOffset (ScriptInstance * script, s32 isInitialCall)
Definition at line 1014 of file code_197F40.c.
AddPartDispOffset()
ApiStatus AddPartDispOffset (ScriptInstance * script, s32 isInitialCall)
Definition at line 1045 of file code_197F40.c.
func_8026BF48()
ApiStatus func_8026BF48 (ScriptInstance * script, s32 isInitialCall)
Definition at line 1076 of file code_197F40.c.
GetActorVar()
ApiStatus GetActorVar (ScriptInstance * script, s32 isInitialCall)
Definition at line 1090 of file code_197F40.c.
SetActorVar()
ApiStatus SetActorVar (ScriptInstance * script, s32 isInitialCall)
Definition at line 1108 of file code_197F40.c.
AddActorVar()
ApiStatus AddActorVar (ScriptInstance * script, s32 isInitialCall)
Definition at line 1127 of file code_197F40.c.
GetPartMovementVar()
ApiStatus GetPartMovementVar (ScriptInstance * script, s32 isInitialCall)
Definition at line 1148 of file code_197F40.c.
SetPartMovementVar()
ApiStatus SetPartMovementVar (ScriptInstance * script, s32 isInitialCall)
Definition at line 1168 of file code_197F40.c.
AddPartMovementVar()
ApiStatus AddPartMovementVar (ScriptInstance * script, s32 isInitialCall)
Definition at line 1188 of file code_197F40.c.
SetActorRotation()
ApiStatus SetActorRotation (ScriptInstance * script, s32 isInitialCall)
Definition at line 1208 of file code_197F40.c.
SetActorRotationOffset()
ApiStatus SetActorRotationOffset (ScriptInstance * script, s32 isInitialCall)
Definition at line 1239 of file code_197F40.c.
GetActorRotation()
ApiStatus GetActorRotation (ScriptInstance * script, s32 isInitialCall)
Definition at line 1262 of file code_197F40.c.
SetPartRotation()
ApiStatus SetPartRotation (ScriptInstance * script, s32 isInitialCall)
Definition at line 1285 of file code_197F40.c.
SetPartRotationOffset()
ApiStatus SetPartRotationOffset (ScriptInstance * script, s32 isInitialCall)
Definition at line 1309 of file code_197F40.c.
GetPartRotation()
ApiStatus GetPartRotation (ScriptInstance * script, s32 isInitialCall)
Definition at line 1333 of file code_197F40.c.
SetActorScale()
ApiStatus SetActorScale (ScriptInstance * script, s32 isInitialCall)
Definition at line 1357 of file code_197F40.c.
SetActorScaleModifier()
ApiStatus SetActorScaleModifier (ScriptInstance * script, s32 isInitialCall)
Definition at line 1380 of file code_197F40.c.
GetActorScale()
ApiStatus GetActorScale (ScriptInstance * script, s32 isInitialCall)
Definition at line 1403 of file code_197F40.c.
SetPartScale()
ApiStatus SetPartScale (ScriptInstance * script, s32 isInitialCall)
Definition at line 1426 of file code_197F40.c.
GetPartScale()
ApiStatus GetPartScale (ScriptInstance * script, s32 isInitialCall)
Definition at line 1450 of file code_197F40.c.
GetBattleFlags()
ApiStatus GetBattleFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 1474 of file code_197F40.c.
SetBattleFlagBits()
ApiStatus SetBattleFlagBits (ScriptInstance * script, s32 isInitialCall)
Definition at line 1479 of file code_197F40.c.
GetBattleFlags2()
ApiStatus GetBattleFlags2 (ScriptInstance * script, s32 isInitialCall)
Definition at line 1492 of file code_197F40.c.
SetBattleFlagBits2()
ApiStatus SetBattleFlagBits2 (ScriptInstance * script, s32 isInitialCall)
Definition at line 1497 of file code_197F40.c.
SetActorFlags()
ApiStatus SetActorFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 1512 of file code_197F40.c.
SetActorFlagBits()
ApiStatus SetActorFlagBits (ScriptInstance * script, s32 isInitialCall)
Definition at line 1527 of file code_197F40.c.
GetActorFlags()
ApiStatus GetActorFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 1551 of file code_197F40.c.
SetPartFlags()
ApiStatus SetPartFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 1567 of file code_197F40.c.
SetPartFlagBits()
ApiStatus SetPartFlagBits (ScriptInstance * script, s32 isInitialCall)
Definition at line 1585 of file code_197F40.c.
SetPartTargetFlags()
ApiStatus SetPartTargetFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 1612 of file code_197F40.c.
SetPartTargetFlagBits()
ApiStatus SetPartTargetFlagBits (ScriptInstance * script, s32 isInitialCall)
Definition at line 1632 of file code_197F40.c.
GetPartFlags()
ApiStatus GetPartFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 1659 of file code_197F40.c.
GetPartTargetFlags()
ApiStatus GetPartTargetFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 1678 of file code_197F40.c.
SetPartEventFlags()
ApiStatus SetPartEventFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 1697 of file code_197F40.c.
SetPartEventBits()
ApiStatus SetPartEventBits (ScriptInstance * script, s32 isInitialCall)
Definition at line 1717 of file code_197F40.c.
GetPartEventFlags()
ApiStatus GetPartEventFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 1744 of file code_197F40.c.
func_8026D51C()
ApiStatus func_8026D51C (ScriptInstance * script, s32 isInitialCall)
Definition at line 1763 of file code_197F40.c.
func_8026D5A4()
ApiStatus func_8026D5A4 (ScriptInstance * script, s32 isInitialCall)
Definition at line 1783 of file code_197F40.c.
HPBarToHome()
ApiStatus HPBarToHome (ScriptInstance * script, s32 isInitialCall)
Definition at line 1810 of file code_197F40.c.
HPBarToCurrent()
ApiStatus HPBarToCurrent (ScriptInstance * script, s32 isInitialCall)
Definition at line 1833 of file code_197F40.c.
func_8026D8EC()
ApiStatus func_8026D8EC (ScriptInstance * script, s32 isInitialCall)
Definition at line 1856 of file code_197F40.c.
func_8026D940()
ApiStatus func_8026D940 (ScriptInstance * script, s32 isInitialCall)
Definition at line 1869 of file code_197F40.c.
func_8026DA94()
ApiStatus func_8026DA94 (ScriptInstance * script, s32 isInitialCall)
Definition at line 1897 of file code_197F40.c.
SummonEnemy()
s32 SummonEnemy ()
Definition at line 1921 of file code_197F40.c.
GetOwnerID()
ApiStatus GetOwnerID (ScriptInstance * script, s32 isInitialCall)
Definition at line 1923 of file code_197F40.c.
SetOwnerID()
ApiStatus SetOwnerID (ScriptInstance * script, s32 isInitialCall)
Definition at line 1928 of file code_197F40.c.
ActorExists()
ApiStatus ActorExists (ScriptInstance * script, s32 isInitialCall)
Definition at line 1933 of file code_197F40.c.
func_8026DEF0()
ApiStatus func_8026DEF0 (ScriptInstance * script, s32 isInitialCall)
Definition at line 1952 of file code_197F40.c.
func_8026DF88()
ApiStatus func_8026DF88 (ScriptInstance * script, s32 isInitialCall)
Definition at line 1967 of file code_197F40.c.
func_8026E020()
ApiStatus func_8026E020 (ScriptInstance * script, s32 isInitialCall)
Definition at line 1982 of file code_197F40.c.
func_8026E038()
ApiStatus func_8026E038 (ScriptInstance * script, s32 isInitialCall)
Definition at line 1989 of file code_197F40.c.
SetBattleInputMask()
ApiStatus SetBattleInputMask (ScriptInstance * script, s32 isInitialCall)
Definition at line 1994 of file code_197F40.c.
SetBattleInputButtons()
ApiStatus SetBattleInputButtons (ScriptInstance * script, s32 isInitialCall)
Definition at line 1999 of file code_197F40.c.
CheckButtonPress()
ApiStatus CheckButtonPress (ScriptInstance * script, s32 isInitialCall)
Definition at line 2013 of file code_197F40.c.
CheckButtonHeld()
ApiStatus CheckButtonHeld (ScriptInstance * script, s32 isInitialCall)
Definition at line 2023 of file code_197F40.c.
CheckButtonDown()
ApiStatus CheckButtonDown (ScriptInstance * script, s32 isInitialCall)
Definition at line 2033 of file code_197F40.c.
GetBattleState()
ApiStatus GetBattleState (ScriptInstance * script, s32 isInitialCall)
Definition at line 2043 of file code_197F40.c.
func_8026E16C()
ApiStatus func_8026E16C (ScriptInstance * script, s32 isInitialCall)
Definition at line 2048 of file code_197F40.c.
func_8026E198()
s32 func_8026E198 ()
Definition at line 2053 of file code_197F40.c.
func_8026E208()
s32 func_8026E208 ()
Definition at line 2055 of file code_197F40.c.
func_8026E260()
s32 func_8026E260 ()
Definition at line 2057 of file code_197F40.c.
PlayerCreateTargetList()
ApiStatus PlayerCreateTargetList (ScriptInstance * script, s32 isInitialCall)
Definition at line 2059 of file code_197F40.c.
EnemyCreateTargetList()
ApiStatus EnemyCreateTargetList (ScriptInstance * script, s32 isInitialCall)
Definition at line 2069 of file code_197F40.c.
InitTargetIterator()
s32 InitTargetIterator ()
Definition at line 2079 of file code_197F40.c.
SetOwnerTarget()
s32 SetOwnerTarget ()
Definition at line 2081 of file code_197F40.c.
ChooseNextTarget()
s32 ChooseNextTarget ()
Definition at line 2083 of file code_197F40.c.
func_8026E558()
s32 func_8026E558 ()
Definition at line 2085 of file code_197F40.c.
GetTargetListLength()
ApiStatus GetTargetListLength (ScriptInstance * script)
Definition at line 2087 of file code_197F40.c.
GetOwnerTarget()
s32 GetOwnerTarget ()
Definition at line 2094 of file code_197F40.c.
func_8026E914()
s32 func_8026E914 ()
Definition at line 2096 of file code_197F40.c.
GetAttackerActorID()
ApiStatus GetAttackerActorID (ScriptInstance * script, s32 isInitialCall)
Definition at line 2098 of file code_197F40.c.
func_8026E9A0()
s32 func_8026E9A0 ()
Definition at line 2103 of file code_197F40.c.
GetDistanceToGoal()
s32 GetDistanceToGoal ()
Definition at line 2105 of file code_197F40.c.
func_8026EA7C()
s32 func_8026EA7C ()
Definition at line 2107 of file code_197F40.c.
func_8026EB20()
s32 func_8026EB20 ()
Definition at line 2109 of file code_197F40.c.
func_8026EBF8()
s32 func_8026EBF8 ()
Definition at line 2111 of file code_197F40.c.
func_8026ED20()
s32 func_8026ED20 ()
Definition at line 2113 of file code_197F40.c.
func_8026EDE4()
s32 func_8026EDE4 ()
Definition at line 2115 of file code_197F40.c.
AddActorDecoration()
s32 AddActorDecoration ()
Definition at line 2117 of file code_197F40.c.
RemoveActorDecoration()
s32 RemoveActorDecoration ()
Definition at line 2119 of file code_197F40.c.
ModifyActorDecoration()
s32 ModifyActorDecoration ()
Definition at line 2121 of file code_197F40.c.
UseIdleAnimation()
s32 UseIdleAnimation ()
Definition at line 2123 of file code_197F40.c.
func_8026F1A0()
s32 func_8026F1A0 ()
Definition at line 2125 of file code_197F40.c.
GetStatusFlags()
s32 GetStatusFlags ()
Definition at line 2127 of file code_197F40.c.
RemovePlayerBuffs()
ApiStatus RemovePlayerBuffs (ScriptInstance * script, s32 isInitialCall)
Definition at line 2129 of file code_197F40.c.
SetPartAlpha()
s32 SetPartAlpha ()
Definition at line 2134 of file code_197F40.c.
CreatePartShadow()
s32 CreatePartShadow ()
Definition at line 2136 of file code_197F40.c.
RemovePartShadow()
s32 RemovePartShadow ()
Definition at line 2138 of file code_197F40.c.
func_8026F60C()
ApiStatus func_8026F60C (ScriptInstance * script, s32 isInitialCall)
Definition at line 2140 of file code_197F40.c.
SetBattleVar()
s32 SetBattleVar ()
Definition at line 2145 of file code_197F40.c.
GetBattleVar()
s32 GetBattleVar ()
Definition at line 2147 of file code_197F40.c.
ResetAllActorSounds()
s32 ResetAllActorSounds ()
Definition at line 2149 of file code_197F40.c.
SetActorSounds()
s32 SetActorSounds ()
Definition at line 2151 of file code_197F40.c.
ResetActorSounds()
s32 ResetActorSounds ()
Definition at line 2153 of file code_197F40.c.
SetPartSounds()
s32 SetPartSounds ()
Definition at line 2155 of file code_197F40.c.
SetActorType()
s32 SetActorType ()
Definition at line 2157 of file code_197F40.c.
ShowShockEffect()
s32 ShowShockEffect ()
Definition at line 2159 of file code_197F40.c.
GetActorAttackBoost()
s32 GetActorAttackBoost ()
Definition at line 2161 of file code_197F40.c.
GetActorDefenseBoost()
s32 GetActorDefenseBoost ()
Definition at line 2163 of file code_197F40.c.
BoostAttack()
s32 BoostAttack ()
Definition at line 2165 of file code_197F40.c.
BoostDefense()
s32 BoostDefense ()
Definition at line 2167 of file code_197F40.c.
VanishActor()
s32 VanishActor ()
Definition at line 2169 of file code_197F40.c.
ElectrifyActor()
s32 ElectrifyActor ()
Definition at line 2171 of file code_197F40.c.
HealActor()
s32 HealActor ()
Definition at line 2173 of file code_197F40.c.
WaitForBuffDone()
s32 WaitForBuffDone ()
Definition at line 2175 of file code_197F40.c.
CopyBuffs()
s32 CopyBuffs ()
Definition at line 2177 of file code_197F40.c.
func_80271210()
s32 func_80271210 ()
Definition at line 2179 of file code_197F40.c.
func_80271258()
s32 func_80271258 ()
Definition at line 2181 of file code_197F40.c.
func_802712A0()
s32 func_802712A0 ()
Definition at line 2183 of file code_197F40.c.
func_80271328()
s32 func_80271328 ()
Definition at line 2185 of file code_197F40.c.
func_802713B0()
s32 func_802713B0 ()
Definition at line 2187 of file code_197F40.c.
func_8027143C()
s32 func_8027143C ()
Definition at line 2189 of file code_197F40.c.
func_80271484()
s32 func_80271484 ()
Definition at line 2191 of file code_197F40.c.
func_80271588()
s32 func_80271588 ()
Definition at line 2193 of file code_197F40.c.
dispatch_event_player()
s32 dispatch_event_player ()
Definition at line 2195 of file code_197F40.c.
Referenced by func_80276F1C().
dispatch_event_player_continue_turn()
s32 dispatch_event_player_continue_turn ()
Definition at line 2197 of file code_197F40.c.
calc_player_test_enemy()
s32 calc_player_test_enemy ()
Definition at line 2199 of file code_197F40.c.
calc_player_damage_enemy()
s32 calc_player_damage_enemy ()
Definition at line 2201 of file code_197F40.c.
dispatch_damage_event_player()
s32 dispatch_damage_event_player ()
Definition at line 2203 of file code_197F40.c.
Referenced by dispatch_damage_event_player_0(), and dispatch_damage_event_player_1().
dispatch_damage_event_player_0()
void dispatch_damage_event_player_0 (s32 damageAmount, Event event)
Definition at line 2205 of file code_197F40.c.
dispatch_damage_event_player_1()
void dispatch_damage_event_player_1 (s32 damageAmount, Event event)
Definition at line 2213 of file code_197F40.c.
GetMenuSelection()
s32 GetMenuSelection ()
Definition at line 2217 of file code_197F40.c.
func_80273444()
s32 func_80273444 ()
Definition at line 2219 of file code_197F40.c.
PlayerFallToGoal()
s32 PlayerFallToGoal ()
Definition at line 2221 of file code_197F40.c.
PlayerLandJump()
s32 PlayerLandJump ()
Definition at line 2223 of file code_197F40.c.
PlayerRunToGoal()
s32 PlayerRunToGoal ()
Definition at line 2225 of file code_197F40.c.
CancelablePlayerRunToGoal()
s32 CancelablePlayerRunToGoal ()
Definition at line 2227 of file code_197F40.c.
GetPlayerHP()
ApiStatus GetPlayerHP (ScriptInstance * script, s32 isInitialCall)
Definition at line 2229 of file code_197F40.c.
PlayerDamageEnemy()
s32 PlayerDamageEnemy ()
Definition at line 2234 of file code_197F40.c.
PlayerPowerBounceEnemy()
s32 PlayerPowerBounceEnemy ()
Definition at line 2236 of file code_197F40.c.
PlayerTestEnemy()
s32 PlayerTestEnemy ()
Definition at line 2238 of file code_197F40.c.
DispatchDamagePlayerEvent()
s32 DispatchDamagePlayerEvent ()
Definition at line 2240 of file code_197F40.c.
EnablePlayerBlur()
s32 EnablePlayerBlur ()
Definition at line 2242 of file code_197F40.c.
func_802749D8()
ApiStatus func_802749D8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 2244 of file code_197F40.c.
func_802749F8()
ApiStatus func_802749F8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 2249 of file code_197F40.c.
func_80274A18()
s32 func_80274A18 ()
Definition at line 2254 of file code_197F40.c.
func_802752AC()
s32 func_802752AC ()
Definition at line 2256 of file code_197F40.c.
func_80275F00()
s32 func_80275F00 ()
Definition at line 2258 of file code_197F40.c.
DidActionSucceed()
s32 DidActionSucceed ()
Definition at line 2260 of file code_197F40.c.
func_80276EFC()
ApiStatus func_80276EFC (ScriptInstance * script, s32 isInitialCall)
Definition at line 2262 of file code_197F40.c.
func_80276F1C()
ApiStatus func_80276F1C (ScriptInstance * script, s32 isInitialCall)
Definition at line 2267 of file code_197F40.c.