src/code_e0b30_len_b80.c File Reference - Paper Mario Documentation
code_e0b30_len_b80.c File Reference
Functions
void bgm_set_target_volume (s16 volume)
s32 bgm_get_map_default_variation (SongID songID)
void bgm_reset_sequence_players (void)
void bgm_reset_volume (void)
s32 bgm_update_music_settings ()
s32 _bgm_set_song (s32 playerIndex, SongID songID, s32 variation, s32 fadeOutTime, s16 volume)
s32 bgm_set_song (s32 playerIndex, SongID songID, s32 variation, s32 fadeOutTime, s16 volume)
s32 func_8014A964 (s32 playerIndex, SongID songID, s32 variation, s32 fadeInTime, s16 arg4, s16 arg5)
s32 func_8014AA54 (s32 playerIndex, s32 arg1, s16 arg2)
s32 func_8014AB0C (s32 playerIndex, s16 arg1)
s32 func_8014AB60 (s32 playerIndex, s16 arg1)
s32 func_8014ABB4 (s32 playerIndex, s16 arg1)
s32 bgm_init_music_players (void)
void bgm_quiet_max_volume (void)
void bgm_reset_max_volume (void)
void bgm_update_volume (void)
s32 func_8014AD40 ()
void bgm_pop_song (void)
void bgm_push_song (SongID songID, s32 variation)
void bgm_pop_battle_song (void)
void bgm_push_battle_song (void)
void bgm_set_battle_song (s32 arg0, s32 arg1)
void func_8014AFA0 (void)
Variables
MusicSettings D_8014F6F0
SongID gSongsUsingVariationFlag []
s16 D_8014F738 = 0
Function Documentation
bgm_set_target_volume()
void bgm_set_target_volume (s16 volume)
Definition at line 229 of file code_e0b30_len_b80.c.
Referenced by _bgm_set_song().
bgm_get_map_default_variation()
s32 bgm_get_map_default_variation (SongID songID)
If the given song ID is present in gSongsUsingVariationFlag, returns the current map's songVariation & 1 value. Otherwise, returns -1.
See also
gSongsUsingVariationFlag
Returns
-1: no override; 0: override to variation 0; 1 override to variation 1
Definition at line 33 of file code_e0b30_len_b80.c.
Referenced by _bgm_set_song(), and func_8014A964().
bgm_reset_sequence_players()
void bgm_reset_sequence_players (void)
Definition at line 50 of file code_e0b30_len_b80.c.
Referenced by load_engine_data().
bgm_reset_volume()
void bgm_reset_volume (void)
Definition at line 65 of file code_e0b30_len_b80.c.
Referenced by step_init_state().
bgm_update_music_settings()
s32 bgm_update_music_settings ()
Definition at line 70 of file code_e0b30_len_b80.c.
Referenced by step_game_loop().
_bgm_set_song()
s32 _bgm_set_song (s32 playerIndex, SongID songID, s32 variation, s32 fadeOutTime, s16 volume)
Definition at line 72 of file code_e0b30_len_b80.c.
Referenced by bgm_pop_battle_song(), bgm_pop_song(), and bgm_set_song().
bgm_set_song()
s32 bgm_set_song (s32 playerIndex, SongID songID, s32 variation, s32 fadeOutTime, s16 volume)
Definition at line 114 of file code_e0b30_len_b80.c.
Referenced by bgm_init_music_players(), bgm_push_battle_song(), bgm_push_song(), FadeOutMusic(), func_80035660(), and SetMusicTrack().
func_8014A964()
s32 func_8014A964 (s32 playerIndex, SongID songID, s32 variation, s32 fadeInTime, s16 arg4, s16 arg5)
Definition at line 122 of file code_e0b30_len_b80.c.
Referenced by FadeInMusic().
func_8014AA54()
s32 func_8014AA54 (s32 playerIndex, s32 arg1, s16 arg2)
Definition at line 154 of file code_e0b30_len_b80.c.
Referenced by func_802D5F28(), and UnkMusicFunc().
func_8014AB0C()
s32 func_8014AB0C (s32 playerIndex, s16 arg1)
Definition at line 181 of file code_e0b30_len_b80.c.
Referenced by func_802D5FA4().
func_8014AB60()
s32 func_8014AB60 (s32 playerIndex, s16 arg1)
Definition at line 192 of file code_e0b30_len_b80.c.
func_8014ABB4()
s32 func_8014ABB4 (s32 playerIndex, s16 arg1)
Definition at line 203 of file code_e0b30_len_b80.c.
bgm_init_music_players()
s32 bgm_init_music_players (void)
Definition at line 214 of file code_e0b30_len_b80.c.
Referenced by step_init_state().
bgm_quiet_max_volume()
void bgm_quiet_max_volume (void)
Definition at line 221 of file code_e0b30_len_b80.c.
Referenced by state_step_pause().
bgm_reset_max_volume()
void bgm_reset_max_volume (void)
Definition at line 225 of file code_e0b30_len_b80.c.
Referenced by state_step_unpause().
bgm_update_volume()
void bgm_update_volume (void)
Definition at line 235 of file code_e0b30_len_b80.c.
func_8014AD40()
s32 func_8014AD40 ()
Definition at line 265 of file code_e0b30_len_b80.c.
bgm_pop_song()
void bgm_pop_song (void)
Definition at line 267 of file code_e0b30_len_b80.c.
Referenced by func_802D5FD8().
bgm_push_song()
void bgm_push_song (SongID songID, s32 variation)
Definition at line 276 of file code_e0b30_len_b80.c.
Referenced by func_802D5FF8().
bgm_pop_battle_song()
void bgm_pop_battle_song (void)
Definition at line 288 of file code_e0b30_len_b80.c.
Referenced by func_802D6050().
bgm_push_battle_song()
void bgm_push_battle_song (void)
Definition at line 302 of file code_e0b30_len_b80.c.
Referenced by func_802D6070().
bgm_set_battle_song()
void bgm_set_battle_song (s32 arg0, s32 arg1)
Definition at line 315 of file code_e0b30_len_b80.c.
Referenced by func_802D6090().
func_8014AFA0()
void func_8014AFA0 (void)
Definition at line 322 of file code_e0b30_len_b80.c.
Variable Documentation
D_8014F6F0
MusicSettings D_8014F6F0
Definition at line 4 of file code_e0b30_len_b80.c.
Referenced by bgm_reset_sequence_players().
gSongsUsingVariationFlag
SongID gSongsUsingVariationFlag[]
Lists the songs that are forced to use the variation determined by map.songVariation & 1.
See also
bgm_get_map_default_variation
Definition at line 20 of file code_e0b30_len_b80.c.
Referenced by bgm_get_map_default_variation().
D_8014F738
s16 D_8014F738 = 0
Definition at line 24 of file code_e0b30_len_b80.c.
Referenced by bgm_update_volume().