src/code_43F0.c File Reference - Paper Mario Documentation
code_43F0.c File Reference
Macros
#define ROM_CHUNK_SIZE 0x2000
Functions
void sin_cos_rad (f32 rad, f32 *outSinTheta, f32 *outCosTheta)
void func_80029860 (s32 romStart, s32 vramDest, s32 length)
f32 length2D (f32 x, f32 y)
HeapNode * _heap_create (s32 *addr, u32 size)
s32 _heap_malloc ()
s32 _heap_malloc_tail ()
s32 _heap_free ()
s32 _heap_realloc ()
f32 cosine (s16 arg0)
s32 sign (s32 val)
s32 int_to_string ()
void mem_clear (s8 *data, s32 numBytes)
void transform_point (Matrix4f mtx, f32 inX, f32 inY, f32 inZ, f32 inS, f32 *outX, f32 *outY, f32 *outZ, f32 *outS)
void copy_matrix (Matrix4f *src, Matrix4f *dest)
s32 dma_copy (s32 romStart, s32 romEnd, void *vramDest)
s32 func_800297D4 (s32 romStart, s32 romEnd, void *vramDest)
s32 _advance_rng (void)
f32 func_80029934 (void)
s32 func_80029994 (s32 arg0)
s32 rand_int (s32 arg0)
f32 signF (f32 val)
s32 round (f32 arg0)
f32 clamp_angle (f32 theta)
f32 get_clamped_angle_diff (f32 a, f32 b)
f32 atan2 (f32 startX, f32 startZ, f32 endX, f32 endZ)
f32 get_player_normal_yaw (void)
f32 get_player_normal_pitch (void)
f32 dist2D (f32 ax, f32 ay, f32 bx, f32 by)
f32 dist3D (f32 ax, f32 ay, f32 az, f32 bx, f32 by, f32 bz)
void add_vec2D_polar (f32 *x, f32 *y, f32 r, f32 theta)
u16 _wrap_trig_lookup_value (f32 theta)
f32 sin_rad (f32 angle)
f32 cos_rad (f32 angle)
void sin_cos_deg (f32 rad, f32 *outSinTheta, f32 *outCosTheta)
f32 sin_deg (f32 angle)
f32 cos_deg (f32 angle)
f32 update_lerp (Easing easing, f32 start, f32 end, s32 elapsed, s32 duration)
void func_8002A904 (u8 arg0, u8 arg1, u8 arg2, u8 arg3, u16 arg4, u16 arg5, u16 arg6, u16 arg7)
s32 func_8002AAC4 ()
s32 func_8002AB5C ()
Variables
s32 D_80074270 = 0
f32 D_80074274 []
s8 D_800743E0 []
s32 gRandSeed = 1
f32 D_80074414 []
Gfx D_80074580 []
Macro Definition Documentation
ROM_CHUNK_SIZE
#define ROM_CHUNK_SIZE 0x2000
Definition at line 53 of file code_43F0.c.
Function Documentation
sin_cos_rad()
void sin_cos_rad (f32 rad, f32 * outSinTheta, f32 * outCosTheta)
Definition at line 353 of file code_43F0.c.
Referenced by add_vec2D_polar().
func_80029860()
void func_80029860 (s32 romStart, s32 vramDest, s32 length)
Definition at line 167 of file code_43F0.c.
Referenced by func_800297D4().
length2D()
f32 length2D (f32 x, f32 y)
Definition at line 55 of file code_43F0.c.
_heap_create()
HeapNode* _heap_create (s32 * addr, u32 size)
Definition at line 59 of file code_43F0.c.
Referenced by battle_heap_create(), collision_heap_create(), and general_heap_create().
_heap_malloc()
s32 _heap_malloc ()
Definition at line 74 of file code_43F0.c.
Referenced by collision_heap_malloc(), general_heap_malloc(), and heap_malloc().
_heap_malloc_tail()
s32 _heap_malloc_tail ()
Definition at line 76 of file code_43F0.c.
Referenced by general_heap_malloc_tail().
_heap_free()
s32 _heap_free ()
Definition at line 78 of file code_43F0.c.
Referenced by collision_heap_free(), general_heap_free(), and heap_free().
_heap_realloc()
s32 _heap_realloc ()
Definition at line 80 of file code_43F0.c.
cosine()
f32 cosine (s16 arg0)
Definition at line 82 of file code_43F0.c.
sign()
s32 sign (s32 val)
Definition at line 104 of file code_43F0.c.
Referenced by pause_interp_vertical_scroll(), and signF().
int_to_string()
s32 int_to_string ()
Definition at line 113 of file code_43F0.c.
mem_clear()
void mem_clear (s8 * data, s32 numBytes)
Definition at line 116 of file code_43F0.c.
Referenced by clear_player_status(), func_800DFC74(), and partner_reset_data().
transform_point()
void transform_point (Matrix4f mtx, f32 inX, f32 inY, f32 inZ, f32 inS, f32 * outX, f32 * outY, f32 * outZ, f32 * outS)
Definition at line 124 of file code_43F0.c.
copy_matrix()
void copy_matrix (Matrix4f * src, Matrix4f * dest)
Definition at line 131 of file code_43F0.c.
dma_copy()
s32 dma_copy (s32 romStart, s32 romEnd, void * vramDest)
Definition at line 135 of file code_43F0.c.
Referenced by func_80240000_BFD880(), func_802B2000(), func_802B203C(), func_802B2078(), func_802B20B4(), get_asset_offset(), load_area_specific_entity_data(), load_asset_by_name(), load_battle_section(), load_effect(), load_engine_data(), load_partner_npc(), load_world_script_api(), LoadMoveScript(), LoadStarPowerScript(), step_battle(), switch_order(), and use_consumable().
func_800297D4()
s32 func_800297D4 (s32 romStart, s32 romEnd, void * vramDest)
Definition at line 152 of file code_43F0.c.
_advance_rng()
s32 _advance_rng (void)
Definition at line 185 of file code_43F0.c.
Referenced by func_80029934(), and func_80029994().
func_80029934()
f32 func_80029934 (void)
Definition at line 193 of file code_43F0.c.
func_80029994()
s32 func_80029994 (s32 arg0)
Definition at line 204 of file code_43F0.c.
Referenced by rand_int().
rand_int()
s32 rand_int (s32 arg0)
Definition at line 221 of file code_43F0.c.
Referenced by func_800493EC(), func_802404D0_BDD680(), func_80260DD8(), func_802A10E4_743ED4(), func_802A123C_71D9AC(), func_802A123C_71E88C(), func_802A123C_7217DC(), func_802A123C_722D7C(), func_802A12E0_72AA30(), func_802A1354_71B4F4(), func_802A13E4_7316E4(), func_802A153C_79060C(), get_coin_drop_amount(), OnFleeBattleDrops(), RandInt(), step_game_loop(), UnkNpcAIFunc1(), UnkNpcAIFunc13(), UnkNpcAIFunc13_2(), UnkNpcAIFunc15(), and UnkNpcAIFunc22().
signF()
f32 signF (f32 val)
Definition at line 243 of file code_43F0.c.
round()
s32 round (f32 arg0)
Definition at line 258 of file code_43F0.c.
Referenced by func_802CA988().
clamp_angle()
f32 clamp_angle (f32 theta)
Definition at line 266 of file code_43F0.c.
Referenced by ClampAngleFloat(), ClampAngleInt(), enable_player_blur(), func_8004A3E8(), func_800E546C(), func_800EF4E0(), func_80218000_4CF1B0(), func_80238028_714D18(), func_80240000_BDD1B0(), func_802404D0_BDD680(), func_80283908(), func_802A1740_71ED90(), func_802E10F4(), func_802E3728(), func_802E5E50(), func_802E9050(), GetCurrentCameraYawClamped180(), GetNpcYaw(), input_to_move_vector(), InterpPlayerYaw(), SomeItemEntityFunc(), SomeXYZFuncTodoRename(), UnkNpcAIFunc1(), UnkNpcAIFunc13(), UnkNpcAIFunc13_2(), UnkNpcAIFunc22(), and UnkYawFunc().
get_clamped_angle_diff()
f32 get_clamped_angle_diff (f32 a, f32 b)
Definition at line 292 of file code_43F0.c.
Referenced by func_800EF4E0(), func_80240000_BDD1B0(), set_npc_yaw(), UnkNpcAIFunc13(), and UnkNpcAIFunc13_2().
atan2()
f32 atan2 (f32 startX, f32 startZ, f32 endX, f32 endZ)
Definition at line 303 of file code_43F0.c.
Referenced by func_8004A3E8(), func_80240000_BDD1B0(), func_80240034_7EAD44(), func_802404D0_BDD680(), func_80240694_BDD844(), func_80240A30_BDDBE0(), func_802E8ADC(), func_802E8BC0(), func_802E9050(), get_dpad_input_radial(), get_player_normal_pitch(), get_player_normal_yaw(), GetAngleBetweenNPCs(), GetAngleToNPC(), GetAngleToPlayer(), input_to_move_vector(), PlayerMoveTo(), set_script_owner_npc_anim(), UnkNpcAIFunc13(), UnkNpcAIFunc13_2(), UnkNpcAIFunc14(), UnkNpcAIFunc15(), UnkNpcAIFunc2(), UnkNpcAIFunc20(), UnkNpcAIFunc21(), and UnkNpcAIFunc9().
get_player_normal_yaw()
f32 get_player_normal_yaw (void)
Definition at line 305 of file code_43F0.c.
get_player_normal_pitch()
f32 get_player_normal_pitch (void)
Definition at line 309 of file code_43F0.c.
dist2D()
f32 dist2D (f32 ax, f32 ay, f32 bx, f32 by)
Definition at line 318 of file code_43F0.c.
Referenced by AwaitPlayerApproach(), AwaitPlayerLeave(), AwaitPlayerNearNpc(), func_800493EC(), func_800E0088(), func_80240694_BDD844(), func_80240A30_BDDBE0(), get_dpad_input_radial(), GetDist2D(), input_to_move_vector(), is_point_within_region(), IsPlayerWithin(), PlayerMoveTo(), and UnkMusicFunc().
dist3D()
f32 dist3D (f32 ax, f32 ay, f32 az, f32 bx, f32 by, f32 bz)
Definition at line 325 of file code_43F0.c.
Referenced by func_80238000_6F10E0(), and UnkMoveFunc1().
add_vec2D_polar()
void add_vec2D_polar (f32 * x, f32 * y, f32 r, f32 theta)
Definition at line 333 of file code_43F0.c.
Referenced by AddVectorPolar(), func_800493EC(), func_80283908(), SomeXYZFunc2(), and UnkYawFunc().
_wrap_trig_lookup_value()
u16 _wrap_trig_lookup_value (f32 theta)
Definition at line 342 of file code_43F0.c.
Referenced by cos_deg(), cos_rad(), sin_cos_deg(), sin_cos_rad(), sin_deg(), and sin_rad().
sin_rad()
f32 sin_rad (f32 angle)
Definition at line 360 of file code_43F0.c.
Referenced by func_80218000_4CF1B0(), func_80238028_714D18(), func_802A1270_727B80(), func_802A1518_78D668(), func_802E3728(), func_802E37E4(), npc_move_heading(), UnkAngleFunc2(), and UnkFloatFunc2().
cos_rad()
f32 cos_rad (f32 angle)
Definition at line 364 of file code_43F0.c.
Referenced by func_80240340_CE3A30(), npc_move_heading(), SomeItemEntityFunc(), UnkAngleFunc2(), and UnkFloatFunc().
sin_cos_deg()
void sin_cos_deg (f32 rad, f32 * outSinTheta, f32 * outCosTheta)
Definition at line 368 of file code_43F0.c.
sin_deg()
f32 sin_deg (f32 angle)
Definition at line 375 of file code_43F0.c.
Referenced by DemoJoystickRadial(), func_80240358_8C82E8(), SomeXYZFuncTodoRename(), and UnkCameraFunc().
cos_deg()
f32 cos_deg (f32 angle)
Definition at line 379 of file code_43F0.c.
Referenced by DemoJoystickRadial(), func_80240358_8C82E8(), SomeItemEntityFunc(), SomeXYZFuncTodoRename(), and UnkCameraFunc().
update_lerp()
f32 update_lerp (Easing easing, f32 start, f32 end, s32 elapsed, s32 duration)
Definition at line 383 of file code_43F0.c.
Referenced by UpdateLerp().
func_8002A904()
void func_8002A904 (u8 arg0, u8 arg1, u8 arg2, u8 arg3, u16 arg4, u16 arg5, u16 arg6, u16 arg7)
Definition at line 387 of file code_43F0.c.
func_8002AAC4()
s32 func_8002AAC4 ()
Definition at line 389 of file code_43F0.c.
func_8002AB5C()
s32 func_8002AB5C ()
Definition at line 413 of file code_43F0.c.
Referenced by state_drawUI_startup().
Variable Documentation
D_80074270
s32 D_80074270 = 0
Definition at line 3 of file code_43F0.c.
D_80074274
f32 D_80074274[]
Definition at line 5 of file code_43F0.c.
Referenced by cosine().
D_800743E0
s8 D_800743E0[]
Definition at line 17 of file code_43F0.c.
gRandSeed
s32 gRandSeed = 1
Definition at line 23 of file code_43F0.c.
Referenced by _advance_rng(), and boot_main().
D_80074414
f32 D_80074414[]
Definition at line 25 of file code_43F0.c.
D_80074580
Gfx D_80074580[]
Definition at line 37 of file code_43F0.c.