src/code_4DF30.c File Reference - Paper Mario Documentation
code_4DF30.c File Reference
Functions
s32 func_80072B30 ()
void func_80072BB0 (void)
void func_80072BCC (s32 arg0)
void load_battle_section (void)
s32 load_battle ()
void set_battle_stage (s32 arg0)
void func_80072CDC (s32 arg0)
void func_80072CEC (f32 arg0, f32 arg1, f32 arg2)
void func_80072CF4 (void)
s32 setup_demo_player ()
s32 load_demo_battle ()
Variables
s32 D_800DC060
Stage * D_800DC064
Function Documentation
func_80072B30()
s32 func_80072B30 ()
Definition at line 7 of file code_4DF30.c.
Referenced by func_80072BB0(), and step_init_state().
func_80072BB0()
void func_80072BB0 (void)
Definition at line 9 of file code_4DF30.c.
func_80072BCC()
void func_80072BCC (s32 arg0)
Definition at line 13 of file code_4DF30.c.
Referenced by func_80044238().
load_battle_section()
void load_battle_section (void)
Definition at line 19 of file code_4DF30.c.
Referenced by step_battle().
load_battle()
s32 load_battle ()
Definition at line 41 of file code_4DF30.c.
set_battle_stage()
void set_battle_stage (s32 arg0)
Definition at line 43 of file code_4DF30.c.
func_80072CDC()
void func_80072CDC (s32 arg0)
Definition at line 47 of file code_4DF30.c.
func_80072CEC()
void func_80072CEC (f32 arg0, f32 arg1, f32 arg2)
Definition at line 51 of file code_4DF30.c.
Referenced by func_80072CF4().
func_80072CF4()
void func_80072CF4 (void)
Definition at line 54 of file code_4DF30.c.
setup_demo_player()
s32 setup_demo_player ()
Definition at line 58 of file code_4DF30.c.
load_demo_battle()
s32 load_demo_battle ()
Definition at line 60 of file code_4DF30.c.
Referenced by LoadDemoBattle().
Variable Documentation
D_800DC060
s32 D_800DC060 extern
D_800DC064
Stage* D_800DC064 extern
Referenced by load_battle_section().