src/code_1AC760.c File Reference - Paper Mario Documentation
code_1AC760.c File Reference
Functions
void dispatch_event_partner (s8 lastEventType)
void dispatch_event_partner_continue_turn (s8 lastEventType)
s32 calc_partner_test_enemy ()
s32 calc_partner_damage_enemy ()
s32 dispatch_damage_event_partner ()
s32 dispatch_damage_event_partner_0 (s32 damageAmount, s32 event, s32 stopMotion)
s32 dispatch_damage_event_partner_1 (s32 damageAmount, s32 event, s32 stopMotion)
ApiStatus MakeOwnerTargetIndex (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8027FC90 (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetActorLevel (ScriptInstance *script, s32 isInitialCall)
s32 PartnerDamageEnemy ()
s32 PartnerAfflictEnemy ()
s32 PartnerPowerBounceEnemy ()
s32 PartnerTestEnemy ()
ApiStatus func_8028070C (ScriptInstance *script, s32 isInitialCall)
ApiStatus DeletePartner (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802807D0 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_80280818 (ScriptInstance *script, s32 isInitialCall)
Seems to be the same functionality as YieldTurn in code_1A5830.c.
Function Documentation
dispatch_event_partner()
void dispatch_event_partner (s8 lastEventType)
Definition at line 4 of file code_1AC760.c.
Referenced by dispatch_event_general(), func_802A123C_72223C(), func_802A12EC_715B3C(), func_802A12EC_724FCC(), func_802A12EC_72E81C(), func_802A12EC_7333BC(), and func_802A1378_725058().
dispatch_event_partner_continue_turn()
void dispatch_event_partner_continue_turn (s8 lastEventType)
Definition at line 27 of file code_1AC760.c.
calc_partner_test_enemy()
s32 calc_partner_test_enemy ()
Definition at line 45 of file code_1AC760.c.
calc_partner_damage_enemy()
s32 calc_partner_damage_enemy ()
Definition at line 47 of file code_1AC760.c.
Referenced by func_8027FC90().
dispatch_damage_event_partner()
s32 dispatch_damage_event_partner ()
Definition at line 49 of file code_1AC760.c.
Referenced by dispatch_damage_event_partner_0(), and dispatch_damage_event_partner_1().
dispatch_damage_event_partner_0()
s32 dispatch_damage_event_partner_0 (s32 damageAmount, s32 event, s32 stopMotion)
Definition at line 51 of file code_1AC760.c.
Referenced by func_8028070C().
dispatch_damage_event_partner_1()
s32 dispatch_damage_event_partner_1 (s32 damageAmount, s32 event, s32 stopMotion)
Definition at line 55 of file code_1AC760.c.
MakeOwnerTargetIndex()
ApiStatus MakeOwnerTargetIndex (ScriptInstance * script, s32 isInitialCall)
Definition at line 59 of file code_1AC760.c.
func_8027FC90()
ApiStatus func_8027FC90 (ScriptInstance * script, s32 isInitialCall)
Definition at line 91 of file code_1AC760.c.
GetActorLevel()
ApiStatus GetActorLevel (ScriptInstance * script, s32 isInitialCall)
Definition at line 115 of file code_1AC760.c.
PartnerDamageEnemy()
s32 PartnerDamageEnemy ()
Definition at line 130 of file code_1AC760.c.
PartnerAfflictEnemy()
s32 PartnerAfflictEnemy ()
Definition at line 132 of file code_1AC760.c.
PartnerPowerBounceEnemy()
s32 PartnerPowerBounceEnemy ()
Definition at line 134 of file code_1AC760.c.
PartnerTestEnemy()
s32 PartnerTestEnemy ()
Definition at line 136 of file code_1AC760.c.
func_8028070C()
ApiStatus func_8028070C (ScriptInstance * script, s32 isInitialCall)
Definition at line 138 of file code_1AC760.c.
DeletePartner()
ApiStatus DeletePartner (ScriptInstance * script, s32 isInitialCall)
Definition at line 155 of file code_1AC760.c.
func_802807D0()
ApiStatus func_802807D0 (ScriptInstance * script, s32 isInitialCall)
Definition at line 162 of file code_1AC760.c.
func_80280818()
ApiStatus func_80280818 (ScriptInstance * script, s32 isInitialCall)
Seems to be the same functionality as YieldTurn in code_1A5830.c.
Definition at line 181 of file code_1AC760.c.