src/code_341d0_len_20d0.c File Reference - Paper Mario Documentation
code_341d0_len_20d0.c File Reference
Functions
s32 func_80058DD0 ()
s32 func_80058E84 ()
s32 func_80058F88 ()
s32 func_80059008 ()
s32 func_8005904C ()
s32 func_80059310 ()
s32 func_800598A0 ()
s32 func_80059AB8 ()
s32 func_80059BD4 ()
void func_80059C80 (void)
s32 func_80059C88 ()
s32 func_80059C9C ()
void func_80059D48 (void)
s32 func_80059D50 ()
s32 render_effects ()
s32 func_80059F94 ()
s32 func_8005A2BC ()
s32 remove_effect ()
s32 remove_all_effects ()
s32 play_effect ()
void load_map_script_lib (void)
s32 load_map_by_IDs ()
s32 get_current_map_config ()
s32 get_current_map_header ()
s32 get_map_IDs_by_name ()
void * load_asset_by_name (char *name, s32 *decompressedSize)
s32 get_asset_offset ()
Function Documentation
func_80058DD0()
s32 func_80058DD0 ()
Definition at line 3 of file code_341d0_len_20d0.c.
func_80058E84()
s32 func_80058E84 ()
Definition at line 5 of file code_341d0_len_20d0.c.
func_80058F88()
s32 func_80058F88 ()
Definition at line 7 of file code_341d0_len_20d0.c.
func_80059008()
s32 func_80059008 ()
Definition at line 9 of file code_341d0_len_20d0.c.
func_8005904C()
s32 func_8005904C ()
Definition at line 11 of file code_341d0_len_20d0.c.
func_80059310()
s32 func_80059310 ()
Definition at line 13 of file code_341d0_len_20d0.c.
func_800598A0()
s32 func_800598A0 ()
Definition at line 15 of file code_341d0_len_20d0.c.
func_80059AB8()
s32 func_80059AB8 ()
Definition at line 17 of file code_341d0_len_20d0.c.
func_80059BD4()
s32 func_80059BD4 ()
Definition at line 19 of file code_341d0_len_20d0.c.
func_80059C80()
void func_80059C80 (void)
Definition at line 21 of file code_341d0_len_20d0.c.
func_80059C88()
s32 func_80059C88 ()
Definition at line 24 of file code_341d0_len_20d0.c.
func_80059C9C()
s32 func_80059C9C ()
Definition at line 26 of file code_341d0_len_20d0.c.
Referenced by step_init_state().
func_80059D48()
void func_80059D48 (void)
Definition at line 28 of file code_341d0_len_20d0.c.
func_80059D50()
s32 func_80059D50 ()
Definition at line 31 of file code_341d0_len_20d0.c.
Referenced by step_world().
render_effects()
s32 render_effects ()
Definition at line 33 of file code_341d0_len_20d0.c.
func_80059F94()
s32 func_80059F94 ()
Definition at line 35 of file code_341d0_len_20d0.c.
func_8005A2BC()
s32 func_8005A2BC ()
Definition at line 37 of file code_341d0_len_20d0.c.
remove_effect()
s32 remove_effect ()
Definition at line 39 of file code_341d0_len_20d0.c.
Referenced by remove_player_buffs(), and RemoveEffect().
remove_all_effects()
s32 remove_all_effects ()
Definition at line 41 of file code_341d0_len_20d0.c.
play_effect()
s32 play_effect ()
Definition at line 43 of file code_341d0_len_20d0.c.
load_map_script_lib()
void load_map_script_lib (void)
Definition at line 45 of file code_341d0_len_20d0.c.
load_map_by_IDs()
s32 load_map_by_IDs ()
Definition at line 49 of file code_341d0_len_20d0.c.
get_current_map_config()
s32 get_current_map_config ()
Definition at line 51 of file code_341d0_len_20d0.c.
get_current_map_header()
s32 get_current_map_header ()
Definition at line 53 of file code_341d0_len_20d0.c.
get_map_IDs_by_name()
s32 get_map_IDs_by_name ()
Definition at line 55 of file code_341d0_len_20d0.c.
load_asset_by_name()
void* load_asset_by_name (char * name, s32 * decompressedSize)
Definition at line 57 of file code_341d0_len_20d0.c.
Referenced by load_map_bg().
get_asset_offset()
s32 get_asset_offset ()
Definition at line 59 of file code_341d0_len_20d0.c.