src/code_23680.c File Reference - Paper Mario Documentation
code_23680.c File Reference
Macros
#define NAMESPACE base
Functions
s32 spawn_drops ()
s32 get_coin_drop_amount (Enemy *enemy)
s32 func_80048E34 ()
s32 func_80048F0C (void)
s32 is_point_within_region (s32 shape, f32 pointX, f32 pointY, f32 centerX, f32 centerY, f32 sizeX, f32 sizeZ)
s32 func_800490B4 (EnemyTerritoryThing *arg0, Enemy *arg1, f32 arg2, s32 arg3, s32 arg4)
s32 func_800493EC (Enemy *enemy, s32 arg1, f32 arg2, f32 arg3)
void func_800494C0 (Npc *npc, s32 arg1, s32 arg2)
void func_80049550 (ScriptInstance *script, s32 arg1)
s32 func_800495A0 ()
s32 func_800496B8 ()
s32 func_80049C04 ()
void func_80049E3C (ScriptInstance *script)
void func_80049ECC (ScriptInstance *script)
s32 func_80049F7C ()
s32 func_8004A124 ()
void func_8004A3E8 (ScriptInstance *script, s32 arg1)
s32 DoBasicAI (ScriptInstance *script, s32 isInitialCall)
Macro Definition Documentation
NAMESPACE
#define NAMESPACE base
Definition at line 167 of file code_23680.c.
Function Documentation
spawn_drops()
s32 spawn_drops ()
Definition at line 4 of file code_23680.c.
Referenced by OnDefeatEnemy().
get_coin_drop_amount()
s32 get_coin_drop_amount (Enemy * enemy)
Definition at line 8 of file code_23680.c.
func_80048E34()
s32 func_80048E34 ()
Definition at line 68 of file code_23680.c.
func_80048F0C()
s32 func_80048F0C (void)
Definition at line 70 of file code_23680.c.
is_point_within_region()
s32 is_point_within_region (s32 shape, f32 pointX, f32 pointY, f32 centerX, f32 centerY, f32 sizeX, f32 sizeZ)
Definition at line 92 of file code_23680.c.
Referenced by func_80240834_BDD9E4().
func_800490B4()
s32 func_800490B4 (EnemyTerritoryThing * arg0, Enemy * arg1, f32 arg2, s32 arg3, s32 arg4)
Definition at line 109 of file code_23680.c.
Referenced by func_802401D4_BDD384(), func_802404D0_BDD680(), func_80240A30_BDDBE0(), and UnkNpcAIFunc11().
func_800493EC()
s32 func_800493EC (Enemy * enemy, s32 arg1, f32 arg2, f32 arg3)
Definition at line 111 of file code_23680.c.
Referenced by func_80240000_BDD1B0().
func_800494C0()
void func_800494C0 (Npc * npc, s32 arg1, s32 arg2)
Definition at line 139 of file code_23680.c.
Referenced by func_80045838(), func_80049E3C(), func_802401D4_BDD384(), and UnkNpcAIFunc15().
func_80049550()
void func_80049550 (ScriptInstance * script, s32 arg1)
Definition at line 154 of file code_23680.c.
func_800495A0()
s32 func_800495A0 ()
Definition at line 163 of file code_23680.c.
func_800496B8()
s32 func_800496B8 ()
Definition at line 165 of file code_23680.c.
func_80049C04()
s32 func_80049C04 ()
Definition at line 170 of file code_23680.c.
func_80049E3C()
void func_80049E3C (ScriptInstance * script)
Definition at line 172 of file code_23680.c.
func_80049ECC()
void func_80049ECC (ScriptInstance * script)
Definition at line 185 of file code_23680.c.
func_80049F7C()
s32 func_80049F7C ()
Definition at line 206 of file code_23680.c.
Referenced by func_80240C90_BDDE40(), and UnkNpcAIFunc15().
func_8004A124()
s32 func_8004A124 ()
Definition at line 208 of file code_23680.c.
Referenced by func_80240C90_BDDE40().
func_8004A3E8()
void func_8004A3E8 (ScriptInstance * script, s32 arg1)
Definition at line 210 of file code_23680.c.
DoBasicAI()
s32 DoBasicAI (ScriptInstance * script, s32 isInitialCall)
Definition at line 221 of file code_23680.c.
Referenced by N().