src/os/code_3c850_len_f0.c File Reference - Paper Mario Documentation
code_3c850_len_f0.c File Reference
Functions
s32 __osPiCreateAccessQueue ()
s32 __osPiGetAccess ()
s32 __osPiRelAccess ()
Variables
u32 __osPiAccessQueueEnabled = 0
Function Documentation
__osPiCreateAccessQueue()
s32 __osPiCreateAccessQueue ()
Definition at line 5 of file code_3c850_len_f0.c.
__osPiGetAccess()
s32 __osPiGetAccess ()
Definition at line 7 of file code_3c850_len_f0.c.
Referenced by osEPiReadIo(), and osEPiWriteIo().
__osPiRelAccess()
s32 __osPiRelAccess ()
Definition at line 9 of file code_3c850_len_f0.c.
Referenced by osEPiReadIo(), and osEPiWriteIo().
Variable Documentation
__osPiAccessQueueEnabled
u32 __osPiAccessQueueEnabled = 0
Definition at line 3 of file code_3c850_len_f0.c.