src/code_ddaf0_len_c50.c File Reference - Paper Mario Documentation
code_ddaf0_len_c50.c File Reference
Functions
void clear_windows (void)
s32 update_windows ()
s32 basic_window_update ()
s32 basic_hidden_window_update ()
s32 main_menu_window_update ()
s32 render_windows ()
s32 render_window_root ()
s32 set_window_properties ()
s32 update_window_hierarchy ()
void replace_window_update (s32 panelIndex, s8 arg1, s32 arg2)
void set_window_update (s32 panelIndex, s32 arg1)
s32 set_windows_visible ()
s32 setup_pause_menu_tab ()
Variables
s32 D_8014F150 []
s32 D_8014F250 []
s32 D_8014F298 [] = { 0x32506469, 0x64000000, }
s8 D_8014F2A0 [] = { 0x01, 0x01, 0x01, 0x01, }
s8 D_8014F2A4 [] = { 0x00, 0x00, 0x00, 0x00, }
s32 D_8014F2A8 [] = { 0x69644D39, 0x281B1008, 0x03000000, }
s8 D_8014F2B4 [] = { 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01 }
s8 D_8014F2BD = 0
s32 D_8014F2C0 [] = { 0x003F0809, 0x162B2C3F, 0x00000000, 0x00000000, }
Function Documentation
clear_windows()
void clear_windows (void)
Definition at line 33 of file code_ddaf0_len_c50.c.
Referenced by load_engine_data(), and step_init_state().
update_windows()
s32 update_windows ()
Definition at line 42 of file code_ddaf0_len_c50.c.
Referenced by step_game_loop().
basic_window_update()
s32 basic_window_update (void)
Definition at line 44 of file code_ddaf0_len_c50.c.
Referenced by show_coin_counter().
basic_hidden_window_update()
s32 basic_hidden_window_update (void)
Definition at line 46 of file code_ddaf0_len_c50.c.
Referenced by update_coin_counter().
main_menu_window_update()
s32 main_menu_window_update ()
Definition at line 48 of file code_ddaf0_len_c50.c.
render_windows()
s32 render_windows ()
Definition at line 50 of file code_ddaf0_len_c50.c.
render_window_root()
s32 render_window_root ()
Definition at line 52 of file code_ddaf0_len_c50.c.
set_window_properties()
s32 set_window_properties ()
Definition at line 54 of file code_ddaf0_len_c50.c.
Referenced by show_coin_counter().
update_window_hierarchy()
s32 update_window_hierarchy ()
Definition at line 56 of file code_ddaf0_len_c50.c.
replace_window_update()
void replace_window_update (s32 panelIndex, s8 arg1, s32 arg2)
Definition at line 58 of file code_ddaf0_len_c50.c.
set_window_update()
void set_window_update (s32 panelIndex, s32 arg1)
Definition at line 68 of file code_ddaf0_len_c50.c.
Referenced by func_802A2910(), func_802A2AB8(), func_802A2C58(), func_802A472C(), func_802A4A10(), show_coin_counter(), and update_coin_counter().
set_windows_visible()
s32 set_windows_visible ()
Definition at line 81 of file code_ddaf0_len_c50.c.
Referenced by begin_state_pause_menu().
setup_pause_menu_tab()
s32 setup_pause_menu_tab ()
Definition at line 83 of file code_ddaf0_len_c50.c.
Variable Documentation
D_8014F150
s32 D_8014F150[]
Definition at line 3 of file code_ddaf0_len_c50.c.
D_8014F250
s32 D_8014F250[]
Definition at line 13 of file code_ddaf0_len_c50.c.
D_8014F298
s32 D_8014F298[] = { 0x32506469, 0x64000000, }
Definition at line 18 of file code_ddaf0_len_c50.c.
D_8014F2A0
s8 D_8014F2A0[] = { 0x01, 0x01, 0x01, 0x01, }
Definition at line 20 of file code_ddaf0_len_c50.c.
D_8014F2A4
s8 D_8014F2A4[] = { 0x00, 0x00, 0x00, 0x00, }
Definition at line 22 of file code_ddaf0_len_c50.c.
D_8014F2A8
s32 D_8014F2A8[] = { 0x69644D39, 0x281B1008, 0x03000000, }
Definition at line 24 of file code_ddaf0_len_c50.c.
D_8014F2B4
s8 D_8014F2B4[] = { 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01 }
Definition at line 26 of file code_ddaf0_len_c50.c.
D_8014F2BD
s8 D_8014F2BD = 0
Definition at line 28 of file code_ddaf0_len_c50.c.
D_8014F2C0
s32 D_8014F2C0[] = { 0x003F0809, 0x162B2C3F, 0x00000000, 0x00000000, }
Definition at line 30 of file code_ddaf0_len_c50.c.