src/code_2BF90.c File Reference - Paper Mario Documentation
code_2BF90.c File Reference
Functions
s32 func_80050B90 ()
s32 func_80050C30 (u32 arg0)
void func_80050C54 (s32 arg0, s8 arg1)
s32 func_80050C64 ()
s32 func_80050CA0 ()
void func_80050D50 (UnkAl1E4 *arg0)
s32 func_80050E18 ()
s32 func_80050E84 ()
s32 func_80050EF0 ()
s32 func_80050F64 ()
s32 func_80050FD0 ()
s32 func_80051050 ()
s32 func_800510A4 ()
void func_800511BC (UnkAl834 *arg0)
void func_80051334 (UnkAl834 *arg0, UnkAl1E4 *arg1)
void func_80051434 (UnkAl834 *arg0, UnkAl1E4 *arg1)
s32 func_800521D0 ()
void func_800521E8 (UnkAl834 *arg0, UnkAl1E4 *arg1)
void func_800522A8 (UnkAl834 *arg0, UnkAl1E4 *arg1)
void func_8005232C (UnkAl834 *arg0, UnkAl1E4 *arg1)
Function Documentation
func_80050B90()
s32 func_80050B90 ()
Definition at line 3 of file code_2BF90.c.
Referenced by func_80052E5C().
func_80050C30()
s32 func_80050C30 (u32 arg0)
Definition at line 5 of file code_2BF90.c.
Referenced by func_80055464(), func_800554A4(), func_800554E8(), func_8005553C(), func_80055590(), func_800555E4(), func_80055618(), func_8005566C(), func_800556D0(), and func_80055718().
func_80050C54()
void func_80050C54 (s32 arg0, s8 arg1)
Definition at line 13 of file code_2BF90.c.
Referenced by func_80055618().
func_80050C64()
s32 func_80050C64 ()
Definition at line 17 of file code_2BF90.c.
Referenced by func_800556D0(), and func_80055718().
func_80050CA0()
s32 func_80050CA0 ()
Definition at line 19 of file code_2BF90.c.
Referenced by func_80055464().
func_80050D50()
void func_80050D50 (UnkAl1E4 * arg0)
Definition at line 21 of file code_2BF90.c.
Referenced by func_800511BC().
func_80050E18()
s32 func_80050E18 ()
Definition at line 23 of file code_2BF90.c.
Referenced by func_8005553C().
func_80050E84()
s32 func_80050E84 ()
Definition at line 25 of file code_2BF90.c.
Referenced by func_80055590().
func_80050EF0()
s32 func_80050EF0 ()
Definition at line 27 of file code_2BF90.c.
Referenced by func_800554A4().
func_80050F64()
s32 func_80050F64 ()
Definition at line 29 of file code_2BF90.c.
Referenced by func_800554E8().
func_80050FD0()
s32 func_80050FD0 ()
Definition at line 31 of file code_2BF90.c.
Referenced by func_8005566C().
func_80051050()
s32 func_80051050 ()
Definition at line 33 of file code_2BF90.c.
Referenced by func_800555E4().
func_800510A4()
s32 func_800510A4 ()
Definition at line 35 of file code_2BF90.c.
func_800511BC()
void func_800511BC (UnkAl834 * arg0)
Definition at line 39 of file code_2BF90.c.
Referenced by func_800533D0().
func_80051334()
void func_80051334 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 92 of file code_2BF90.c.
Referenced by func_800511BC().
func_80051434()
void func_80051434 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 94 of file code_2BF90.c.
Referenced by func_800511BC().
func_800521D0()
s32 func_800521D0 ()
Definition at line 96 of file code_2BF90.c.
func_800521E8()
void func_800521E8 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 98 of file code_2BF90.c.
Referenced by func_800511BC().
func_800522A8()
void func_800522A8 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 100 of file code_2BF90.c.
Referenced by func_800511BC().
func_8005232C()
void func_8005232C (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 102 of file code_2BF90.c.
Referenced by func_800511BC().