src/code_190B20.h File Reference - Paper Mario Documentation
code_190B20.h File Reference
Functions
void player_create_target_list (Actor *actor)
void enemy_create_target_list (Actor *actor)
void set_actor_yaw (s32 actorId, s32 yaw)
void set_part_yaw (s32 actorID, s32 partIndex, s32 value)
ActorPart * get_actor_part (Actor *actor, s32 partIndex)
void add_part_decoration (ActorPart *part, s32 decorationIndex, DecorationId decorationType)
void add_actor_decoration (Actor *actor, s32 decorationIndex, DecorationId decorationType)
void remove_part_decoration (ActorPart *part, s32 decorationIndex)
void remove_actor_decoration (Actor *actor, s32 decorationIndex)
s32 heroes_is_ability_active (Actor *actor, Ability ability)
void create_part_shadow (s32 actorId, s32 partIndex)
void remove_part_shadow (s32 actorId, s32 partIndex)
void create_part_shadow_by_ref (s32 arg0, ActorPart *part)
Function Documentation
player_create_target_list()
void player_create_target_list (Actor * actor)
Definition at line 5 of file code_190B20.c.
Referenced by count_targets(), and PlayerCreateTargetList().
enemy_create_target_list()
void enemy_create_target_list (Actor * actor)
Definition at line 9 of file code_190B20.c.
Referenced by EnemyCreateTargetList().
set_actor_yaw()
void set_actor_yaw (s32 actorId, s32 yaw)
Definition at line 49 of file code_190B20.c.
set_part_yaw()
void set_part_yaw (s32 actorID, s32 partIndex, s32 value)
Definition at line 53 of file code_190B20.c.
get_actor_part()
ActorPart* get_actor_part (Actor * actor, s32 partIndex)
Definition at line 69 of file code_190B20.c.
add_part_decoration()
void add_part_decoration (ActorPart * part, s32 decorationIndex, DecorationId decorationType)
Definition at line 290 of file code_190B20.c.
Referenced by add_actor_decoration().
add_actor_decoration()
void add_actor_decoration (Actor * actor, s32 decorationIndex, DecorationId decorationType)
Definition at line 305 of file code_190B20.c.
remove_part_decoration()
void remove_part_decoration (ActorPart * part, s32 decorationIndex)
Definition at line 314 of file code_190B20.c.
Referenced by remove_actor_decoration().
remove_actor_decoration()
void remove_actor_decoration (Actor * actor, s32 decorationIndex)
Definition at line 318 of file code_190B20.c.
heroes_is_ability_active()
s32 heroes_is_ability_active (Actor * actor, Ability ability)
Definition at line 327 of file code_190B20.c.
create_part_shadow()
void create_part_shadow (s32 actorId, s32 partIndex)
Definition at line 345 of file code_190B20.c.
remove_part_shadow()
void remove_part_shadow (s32 actorId, s32 partIndex)
Definition at line 353 of file code_190B20.c.
create_part_shadow_by_ref()
void create_part_shadow_by_ref (s32 arg0, ActorPart * part)
Definition at line 360 of file code_190B20.c.