src/code_DF950.c File Reference - Paper Mario Documentation
code_DF950.c File Reference
Functions
s32 func_80149250 ()
void use_default_door_sounds (void)
s32 func_80149618 ()
s32 func_80149670 ()
s32 func_80149734 ()
void func_801497FC (s32 arg0)
s32 func_80149828 (void)
s32 func_80149838 ()
s32 func_801498C4 ()
s32 func_80149908 ()
s32 func_80149974 ()
s32 func_801499EC (s32 soundID, s32 arg1, f32 arg2, f32 arg3, f32 arg4)
s32 func_80149A6C ()
s32 _play_sound ()
s32 func_80149BE4 ()
s32 stop_sound ()
void play_sound (s32 soundID)
void play_sound_at_player (s32 soundID, s32 arg1)
void play_sound_at_npc (s32 soundID, s32 arg1, s32 npcID)
s32 play_sound_at_position (s32 soundID, s32 value2, f32 posX, f32 posY, f32 posZ)
s32 func_80149E04 ()
s32 func_80149F58 ()
s32 func_8014A1B4 ()
Variables
s32 D_8014F2D0 []
s32 D_8014F48C [] = { 0x00000336, 0x00000316 }
s32 D_8014F494 [] = { 0x00000337, 0x00000317 }
s32 D_8014F49C [] = { 0x00000338, 0x00000318 }
s32 D_8014F4A4 [] = { 0x00000339, 0x00000319 }
s32 D_8014F4AC [] = { 0x0000033A, 0x0000031A }
s32 D_8014F4B4 [] = { 0x0000033B, 0x0000031B }
s32 D_8014F4BC [] = { 0x0000033C, 0x0000031C }
s32 D_8014F4C4 [] = { 0x0000033D, 0x0000031D }
s32 D_8014F4CC [] = { 0x0000033E, 0x0000031E }
s32 D_8014F4D4 [] = { 0x0000033F, 0x0000031F }
s32 D_8014F4DC [] = { 0x00000340, 0x00000340 }
s32 D_8014F4E4 [] = { 0x000002F4, 0x000002F5 }
s32 D_8014F4EC [] = { 0x0000032F, 0x00000330 }
s32 D_8014F4F4 [] = { 0x00000334, 0x00000335 }
s32 D_8014F4FC [] = { 0x000002F1, 0x000002F2 }
s32 D_8014F504 [] = { 0x000000C1, 0x000000C2 }
s32 D_8014F50C [] = { 0x000000C3, 0x000000C4 }
s32 D_8014F514 [] = { 0x000001CB, 0x000001CD }
s32 D_8014F51C [] = { 0x000001CC, 0x000001CE }
s32 D_8014F524 [] = { 0x000002A6, 0x000002A7 }
s32 D_8014F52C [] = { 0x0000020C, 0x0000020D, 0x0000020E }
s32 D_8014F538 [] = { 0x00000259, 0x0000025A }
s32 D_8014F540 [] = { 0x0000025C, 0x0000025D }
s32 D_8014F548 [] = { 0x00000331, 0x00000332, 0x00000333 }
s32 D_8014F554 [] = { 0x00002078, 0x00002079 }
s32 D_8014F55C [] = { 0x00000179, 0x0000017A }
s32 D_8014F564 [] = { 0x000001FB, 0x000001FC }
s32 D_8014F56C [] = { 0x0000203A, 0x0000203B }
s32 D_8014F574 [] = { 0x0000022E, 0x0000022F }
s32 D_8014F57C [] = { 0x0000202A, 0x0000202B }
s32 D_8014F584 [] = { 0x00002041, 0x00002042 }
s32 D_8014F58C [] = { 0x00002043, 0x00002044 }
s32 D_8014F594 [] = { 0x00002078, 0x00002079 }
s32 D_8014F59C [] = { 0x000003B6, 0x000003B7 }
s32 D_8014F5A4 []
s32 D_8014F6B4 []
s32 D_80159AD4
Function Documentation
func_80149250()
s32 func_80149250 ()
Definition at line 68 of file code_DF950.c.
use_default_door_sounds()
void use_default_door_sounds (void)
Definition at line 70 of file code_DF950.c.
func_80149618()
s32 func_80149618 ()
Definition at line 75 of file code_DF950.c.
Referenced by load_engine_data(), and step_init_state().
func_80149670()
s32 func_80149670 ()
Definition at line 77 of file code_DF950.c.
func_80149734()
s32 func_80149734 ()
Definition at line 79 of file code_DF950.c.
func_801497FC()
void func_801497FC (s32 arg0)
Definition at line 81 of file code_DF950.c.
func_80149828()
s32 func_80149828 (void)
Definition at line 86 of file code_DF950.c.
func_80149838()
s32 func_80149838 ()
Definition at line 90 of file code_DF950.c.
func_801498C4()
s32 func_801498C4 ()
Definition at line 92 of file code_DF950.c.
func_80149908()
s32 func_80149908 ()
Definition at line 94 of file code_DF950.c.
func_80149974()
s32 func_80149974 ()
Definition at line 96 of file code_DF950.c.
func_801499EC()
s32 func_801499EC (s32 soundID, s32 arg1, f32 arg2, f32 arg3, f32 arg4)
Definition at line 98 of file code_DF950.c.
Referenced by func_80240060_BFA100().
func_80149A6C()
s32 func_80149A6C ()
Definition at line 100 of file code_DF950.c.
Referenced by func_802D62E4().
_play_sound()
s32 _play_sound ()
Definition at line 102 of file code_DF950.c.
Referenced by func_802D617C(), and play_sound().
func_80149BE4()
s32 func_80149BE4 ()
Definition at line 104 of file code_DF950.c.
stop_sound()
s32 stop_sound ()
Definition at line 106 of file code_DF950.c.
Referenced by set_action_state(), StopLoopingSoundAtActor(), and StopSound().
play_sound()
void play_sound (s32 soundID)
Definition at line 108 of file code_DF950.c.
Referenced by check_input_status_menu(), coin_counter_draw_content(), FadeInMerlee(), func_800E6904(), func_80238000_6FAD10(), func_80238A20_6F1B00(), func_802E12F8(), func_802E8858(), inflict_partner_ko(), OnDefeatEnemy(), partner_use_ability(), player_enter_blue_pipe(), PlaySound(), and remove_player_buffs().
play_sound_at_player()
void play_sound_at_player (s32 soundID, s32 arg1)
Definition at line 112 of file code_DF950.c.
Referenced by func_800E5098(), and PlaySoundAtPlayer().
play_sound_at_npc()
void play_sound_at_npc (s32 soundID, s32 arg1, s32 npcID)
Definition at line 118 of file code_DF950.c.
play_sound_at_position()
s32 play_sound_at_position (s32 soundID, s32 value2, f32 posX, f32 posY, f32 posZ)
Definition at line 127 of file code_DF950.c.
Referenced by calc_item_check_hit(), func_800494C0(), func_80240BD8_8ACB68(), func_802D7520(), func_802D75D8(), func_802E2EB0(), func_802E3BA4(), play_sound_at_npc(), play_sound_at_player(), PlayLoopingSoundAtActor(), PlaySoundAt(), PlaySoundAtActor(), PlaySoundAtCollider(), PlaySoundAtF(), PlaySoundAtModel(), PlaySoundAtNpc(), and PlaySoundAtPart().
func_80149E04()
s32 func_80149E04 ()
Definition at line 129 of file code_DF950.c.
func_80149F58()
s32 func_80149F58 ()
Definition at line 131 of file code_DF950.c.
func_8014A1B4()
s32 func_8014A1B4 ()
Definition at line 133 of file code_DF950.c.
Variable Documentation
D_8014F2D0
s32 D_8014F2D0[]
Definition at line 3 of file code_DF950.c.
D_8014F48C
s32 D_8014F48C[] = { 0x00000336, 0x00000316 }
Definition at line 18 of file code_DF950.c.
D_8014F494
s32 D_8014F494[] = { 0x00000337, 0x00000317 }
Definition at line 19 of file code_DF950.c.
D_8014F49C
s32 D_8014F49C[] = { 0x00000338, 0x00000318 }
Definition at line 20 of file code_DF950.c.
D_8014F4A4
s32 D_8014F4A4[] = { 0x00000339, 0x00000319 }
Definition at line 21 of file code_DF950.c.
D_8014F4AC
s32 D_8014F4AC[] = { 0x0000033A, 0x0000031A }
Definition at line 22 of file code_DF950.c.
D_8014F4B4
s32 D_8014F4B4[] = { 0x0000033B, 0x0000031B }
Definition at line 23 of file code_DF950.c.
D_8014F4BC
s32 D_8014F4BC[] = { 0x0000033C, 0x0000031C }
Definition at line 24 of file code_DF950.c.
D_8014F4C4
s32 D_8014F4C4[] = { 0x0000033D, 0x0000031D }
Definition at line 25 of file code_DF950.c.
D_8014F4CC
s32 D_8014F4CC[] = { 0x0000033E, 0x0000031E }
Definition at line 26 of file code_DF950.c.
D_8014F4D4
s32 D_8014F4D4[] = { 0x0000033F, 0x0000031F }
Definition at line 27 of file code_DF950.c.
D_8014F4DC
s32 D_8014F4DC[] = { 0x00000340, 0x00000340 }
Definition at line 28 of file code_DF950.c.
D_8014F4E4
s32 D_8014F4E4[] = { 0x000002F4, 0x000002F5 }
Definition at line 29 of file code_DF950.c.
D_8014F4EC
s32 D_8014F4EC[] = { 0x0000032F, 0x00000330 }
Definition at line 30 of file code_DF950.c.
D_8014F4F4
s32 D_8014F4F4[] = { 0x00000334, 0x00000335 }
Definition at line 31 of file code_DF950.c.
D_8014F4FC
s32 D_8014F4FC[] = { 0x000002F1, 0x000002F2 }
Definition at line 32 of file code_DF950.c.
D_8014F504
s32 D_8014F504[] = { 0x000000C1, 0x000000C2 }
Definition at line 33 of file code_DF950.c.
D_8014F50C
s32 D_8014F50C[] = { 0x000000C3, 0x000000C4 }
Definition at line 34 of file code_DF950.c.
D_8014F514
s32 D_8014F514[] = { 0x000001CB, 0x000001CD }
Definition at line 35 of file code_DF950.c.
D_8014F51C
s32 D_8014F51C[] = { 0x000001CC, 0x000001CE }
Definition at line 36 of file code_DF950.c.
D_8014F524
s32 D_8014F524[] = { 0x000002A6, 0x000002A7 }
Definition at line 37 of file code_DF950.c.
D_8014F52C
s32 D_8014F52C[] = { 0x0000020C, 0x0000020D, 0x0000020E }
Definition at line 38 of file code_DF950.c.
D_8014F538
s32 D_8014F538[] = { 0x00000259, 0x0000025A }
Definition at line 39 of file code_DF950.c.
D_8014F540
s32 D_8014F540[] = { 0x0000025C, 0x0000025D }
Definition at line 40 of file code_DF950.c.
D_8014F548
s32 D_8014F548[] = { 0x00000331, 0x00000332, 0x00000333 }
Definition at line 41 of file code_DF950.c.
D_8014F554
s32 D_8014F554[] = { 0x00002078, 0x00002079 }
Definition at line 42 of file code_DF950.c.
D_8014F55C
s32 D_8014F55C[] = { 0x00000179, 0x0000017A }
Definition at line 43 of file code_DF950.c.
D_8014F564
s32 D_8014F564[] = { 0x000001FB, 0x000001FC }
Definition at line 44 of file code_DF950.c.
D_8014F56C
s32 D_8014F56C[] = { 0x0000203A, 0x0000203B }
Definition at line 45 of file code_DF950.c.
D_8014F574
s32 D_8014F574[] = { 0x0000022E, 0x0000022F }
Definition at line 46 of file code_DF950.c.
D_8014F57C
s32 D_8014F57C[] = { 0x0000202A, 0x0000202B }
Definition at line 47 of file code_DF950.c.
D_8014F584
s32 D_8014F584[] = { 0x00002041, 0x00002042 }
Definition at line 48 of file code_DF950.c.
D_8014F58C
s32 D_8014F58C[] = { 0x00002043, 0x00002044 }
Definition at line 49 of file code_DF950.c.
D_8014F594
s32 D_8014F594[] = { 0x00002078, 0x00002079 }
Definition at line 50 of file code_DF950.c.
D_8014F59C
s32 D_8014F59C[] = { 0x000003B6, 0x000003B7 }
Definition at line 51 of file code_DF950.c.
D_8014F5A4
s32 D_8014F5A4[]
Definition at line 53 of file code_DF950.c.
D_8014F6B4
s32 D_8014F6B4[]
Definition at line 63 of file code_DF950.c.
D_80159AD4
s32 D_80159AD4 extern
Referenced by func_801497FC(), and func_80149828().