src/code_2e230_len_2190.c File Reference - Paper Mario Documentation
code_2e230_len_2190.c File Reference
Functions
void func_80052E30 (u8 index)
void snd_load_audio_data (s32 frequency)
void snd_reset_instrument (Instrument *instrument)
void func_80053370 (UnkAlC *arg0)
void func_800533A8 (InstrumentCFG *arg0)
void snd_update_sequence_players (void)
void func_800535C0 (void)
void func_80053654 (UnkAl19E0 *arg0)
void func_80053888 (UnkAl48 *arg0, s32 arg1)
void func_800538C4 (UnkAl48 *arg0, s32 arg1)
s32 func_800538F8 ()
void snd_initialize_fade (Fade *fade, s32 time, s32 startValue, s16 endValue)
void func_80053A18 (UnkAl1 *arg0)
void func_80053A28 (UnkAl1 *arg0)
void func_80053A98 (u8 arg0, u16 arg1, s32 arg2)
void func_80053AC8 (UnkAl1 *arg0)
void func_80053AEC (UnkAl1 *arg0, s16 arg1)
void func_80053B04 (UnkAl1 *arg0, u32 arg1, s16 arg2)
void func_80053BA8 (UnkAl1 *arg0)
s32 func_80053BE8 (UnkAl19E0 *arg0, s32 arg1, s32 arg2, s32 *arg3)
void snd_get_sequence_player_and_track (u32 playerIndex, s32 **outCurrentTrackData, BGMPlayer **outPlayer)
void snd_get_sequence_player (u32 playerIndex, BGMPlayer **outPlayer)
s32 snd_load_song_files ()
s32 func_80053E58 ()
BGMPlayer * func_80053F64 (s32 arg0)
s32 func_80053F80 ()
BGMPlayer * func_80054248 (u8 arg0)
void snd_load_INIT (UnkAl19E0 *arg0, s32 arg1, ALHeap *arg2)
s32 snd_fetch_SBN_file (u16 arg0, s32 arg1, s32 *arg2)
void snd_load_PER (UnkAl19E0 *arg0, s32 *arg1)
void snd_load_PRG (UnkAl19E0 *arg0, s32 *arg1)
s32 snd_load_BGM ()
Instruments * snd_get_BK_instruments (s32 bankGroup, u32 bankIndex)
s32 snd_load_BK_to_bank ()
void snd_swizzle_BK_instruments (s32 bkFileOffset, SoundBank *bank, Instruments instruments, s32 instrumentCount, u8 arg4)
void snd_swizzle_BK_instruments (s32 bkFileOffset, SoundBank *bank, Instruments instruments, u32 instrumentCount, u8 arg4)
s32 func_80054AA0 ()
s32 snd_load_BK (s32 arg0, s32 arg1)
s32 func_80054C84 ()
void func_80054CE0 (s32 arg0, s32 arg1)
s32 func_80054D74 (s32 arg0, s32 arg1)
s32 func_80054DA8 ()
void snd_read_rom (s32 arg0, s32 *arg1, s32 arg2)
s32 snd_memset ()
void snd_bcopy (s8 *src, s8 *dest, s32 size)
void snd_copy_words (s32 *src, s32 *dst, s32 num)
Function Documentation
func_80052E30()
void func_80052E30 (u8 index)
Definition at line 4 of file code_2e230_len_2190.c.
snd_load_audio_data()
void snd_load_audio_data (s32 frequency)
Definition at line 11 of file code_2e230_len_2190.c.
snd_reset_instrument()
void snd_reset_instrument (Instrument * instrument)
Definition at line 143 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
func_80053370()
void func_80053370 (UnkAlC * arg0)
Definition at line 165 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
func_800533A8()
void func_800533A8 (InstrumentCFG * arg0)
Definition at line 177 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
snd_update_sequence_players()
void snd_update_sequence_players (void)
Definition at line 187 of file code_2e230_len_2190.c.
func_800535C0()
void func_800535C0 (void)
Definition at line 258 of file code_2e230_len_2190.c.
func_80053654()
void func_80053654 (UnkAl19E0 * arg0)
Definition at line 278 of file code_2e230_len_2190.c.
Referenced by snd_update_sequence_players().
func_80053888()
void func_80053888 (UnkAl48 * arg0, s32 arg1)
Definition at line 352 of file code_2e230_len_2190.c.
func_800538C4()
void func_800538C4 (UnkAl48 * arg0, s32 arg1)
Definition at line 361 of file code_2e230_len_2190.c.
func_800538F8()
s32 func_800538F8 ()
Definition at line 368 of file code_2e230_len_2190.c.
snd_initialize_fade()
void snd_initialize_fade (Fade * fade, s32 time, s32 startValue, s16 endValue)
Definition at line 370 of file code_2e230_len_2190.c.
Referenced by func_8004B440().
func_80053A18()
void func_80053A18 (UnkAl1 * arg0)
Definition at line 385 of file code_2e230_len_2190.c.
Referenced by func_8004DAA8().
func_80053A28()
void func_80053A28 (UnkAl1 * arg0)
Definition at line 391 of file code_2e230_len_2190.c.
Referenced by snd_update_sequence_players().
func_80053A98()
void func_80053A98 (u8 arg0, u16 arg1, s32 arg2)
Definition at line 406 of file code_2e230_len_2190.c.
Referenced by func_8004B440(), func_8004E444(), and snd_update_sequence_players().
func_80053AC8()
void func_80053AC8 (UnkAl1 * arg0)
Definition at line 410 of file code_2e230_len_2190.c.
func_80053AEC()
void func_80053AEC (UnkAl1 * arg0, s16 arg1)
Definition at line 418 of file code_2e230_len_2190.c.
Referenced by func_8004E158().
func_80053B04()
void func_80053B04 (UnkAl1 * arg0, u32 arg1, s16 arg2)
Definition at line 425 of file code_2e230_len_2190.c.
func_80053BA8()
void func_80053BA8 (UnkAl1 * arg0)
Definition at line 442 of file code_2e230_len_2190.c.
Referenced by snd_update_sequence_players().
func_80053BE8()
s32 func_80053BE8 (UnkAl19E0 * arg0, s32 arg1, s32 arg2, s32 * arg3)
Definition at line 453 of file code_2e230_len_2190.c.
Referenced by snd_BGMCmd_E8_TrackOverridePatch().
snd_get_sequence_player_and_track()
void snd_get_sequence_player_and_track (u32 playerIndex, s32 ** outCurrentTrackData, BGMPlayer ** outPlayer)
Definition at line 455 of file code_2e230_len_2190.c.
snd_get_sequence_player()
void snd_get_sequence_player (u32 playerIndex, BGMPlayer ** outPlayer)
Definition at line 477 of file code_2e230_len_2190.c.
snd_load_song_files()
s32 snd_load_song_files ()
Definition at line 493 of file code_2e230_len_2190.c.
func_80053E58()
s32 func_80053E58 ()
Definition at line 495 of file code_2e230_len_2190.c.
func_80053F64()
BGMPlayer* func_80053F64 (s32 arg0)
Definition at line 497 of file code_2e230_len_2190.c.
func_80053F80()
s32 func_80053F80 ()
Definition at line 504 of file code_2e230_len_2190.c.
Referenced by func_80055448().
func_80054248()
BGMPlayer* func_80054248 (u8 arg0)
Definition at line 506 of file code_2e230_len_2190.c.
snd_load_INIT()
void snd_load_INIT (UnkAl19E0 * arg0, s32 arg1, ALHeap * arg2)
Definition at line 519 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
snd_fetch_SBN_file()
s32 snd_fetch_SBN_file (u16 arg0, s32 arg1, s32 * arg2)
Definition at line 521 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
snd_load_PER()
void snd_load_PER (UnkAl19E0 * arg0, s32 * arg1)
Definition at line 523 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
snd_load_PRG()
void snd_load_PRG (UnkAl19E0 * arg0, s32 * arg1)
Definition at line 525 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
snd_load_BGM()
s32 snd_load_BGM ()
Definition at line 527 of file code_2e230_len_2190.c.
snd_get_BK_instruments()
Instruments* snd_get_BK_instruments (s32 bankGroup, u32 bankIndex)
Definition at line 529 of file code_2e230_len_2190.c.
snd_load_BK_to_bank()
s32 snd_load_BK_to_bank ()
Definition at line 560 of file code_2e230_len_2190.c.
Referenced by snd_load_BK().
snd_swizzle_BK_instruments() [1/2]
void snd_swizzle_BK_instruments (s32 bkFileOffset, SoundBank * bank, Instruments instruments, s32 instrumentCount, u8 arg4)
snd_swizzle_BK_instruments() [2/2]
void snd_swizzle_BK_instruments (s32 bkFileOffset, SoundBank * bank, Instruments instruments, u32 instrumentCount, u8 arg4)
Definition at line 565 of file code_2e230_len_2190.c.
func_80054AA0()
s32 func_80054AA0 ()
Definition at line 602 of file code_2e230_len_2190.c.
snd_load_BK()
s32 snd_load_BK (s32 arg0, s32 arg1)
Definition at line 604 of file code_2e230_len_2190.c.
func_80054C84()
s32 func_80054C84 ()
Definition at line 609 of file code_2e230_len_2190.c.
func_80054CE0()
void func_80054CE0 (s32 arg0, s32 arg1)
Definition at line 611 of file code_2e230_len_2190.c.
Referenced by func_800561A4(), and func_800561C4().
func_80054D74()
s32 func_80054D74 (s32 arg0, s32 arg1)
Definition at line 613 of file code_2e230_len_2190.c.
Referenced by func_800561E4().
func_80054DA8()
s32 func_80054DA8 ()
Definition at line 620 of file code_2e230_len_2190.c.
Referenced by func_8005615C(), and func_80056180().
snd_read_rom()
void snd_read_rom (s32 arg0, s32 * arg1, s32 arg2)
Definition at line 622 of file code_2e230_len_2190.c.
Referenced by snd_load_audio_data().
snd_memset()
s32 snd_memset ()
Definition at line 624 of file code_2e230_len_2190.c.
snd_bcopy()
void snd_bcopy (s8 * src, s8 * dest, s32 size)
Definition at line 626 of file code_2e230_len_2190.c.
snd_copy_words()
void snd_copy_words (s32 * src, s32 * dst, s32 num)
Definition at line 634 of file code_2e230_len_2190.c.