src/battle/item/dried_shroom/dried_shroom.h File Reference - Paper Mario Documentation
dried_shroom.h File Reference
Macros
#define NAMESPACE battle_item_dried_shroom
Functions
ApiStatus func_802D7520 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D75D8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A123C_71CF1C (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A12FC_71CFDC (ScriptInstance *script, s32 isInitialCall)
Script N (UseItemWithEffect)
Script N (PlayerGoHome)
Script N (EatItem)
Macro Definition Documentation
NAMESPACE
#define NAMESPACE battle_item_dried_shroom
Definition at line 8 of file dried_shroom.h.
Function Documentation
func_802D7520()
ApiStatus func_802D7520 (ScriptInstance * script, s32 isInitialCall)
Definition at line 7 of file code_FBE10.c.
Referenced by N().
func_802D75D8()
ApiStatus func_802D75D8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 18 of file code_FBE10.c.
Referenced by N().
func_802A123C_71CF1C()
ApiStatus N() func_802A123C_71CF1C (ScriptInstance * script, s32 isInitialCall)
Definition at line 57 of file lib.c.
Referenced by N().
func_802A12FC_71CFDC()
ApiStatus N() func_802A12FC_71CFDC (ScriptInstance * script, s32 isInitialCall)
Definition at line 69 of file lib.c.
Referenced by N().
N() [1/3]
Script N (UseItemWithEffect)
N() [2/3]
Script N (PlayerGoHome)
N() [3/3]
Script N (EatItem)