src/battle/item/food/food.h File Reference - Paper Mario Documentation
food.h File Reference
Macros
#define NAMESPACE battle_item_food
Functions
ApiStatus func_802D3F74 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D378C (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D7520 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D75D8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A123C_73330C (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A12EC_7333BC (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A15A0_733670 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1378_733448 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1438_733508 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() AddHP (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() AddFP (ScriptInstance *script, s32 isInitialCall)
Script N (UseItemWithEffect)
Script N (PlayerGoHome)
Script N (UseItem)
Script N (EatItem)
Script N (DrinkItem)
Macro Definition Documentation
NAMESPACE
#define NAMESPACE battle_item_food
Definition at line 8 of file food.h.
Function Documentation
func_802D3F74()
ApiStatus func_802D3F74 (ScriptInstance * script, s32 isInitialCall)
Referenced by N().
func_802D378C()
ApiStatus func_802D378C (ScriptInstance * script, s32 isInitialCall)
Referenced by N().
func_802D7520()
ApiStatus func_802D7520 (ScriptInstance * script, s32 isInitialCall)
Definition at line 7 of file code_FBE10.c.
func_802D75D8()
ApiStatus func_802D75D8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 18 of file code_FBE10.c.
func_802A123C_73330C()
ApiStatus N() func_802A123C_73330C (ScriptInstance * script, s32 isInitialCall)
Definition at line 57 of file lib.c.
Referenced by N().
func_802A12EC_7333BC()
ApiStatus N() func_802A12EC_7333BC (ScriptInstance * script, s32 isInitialCall)
Definition at line 71 of file lib.c.
Referenced by N().
func_802A15A0_733670()
ApiStatus N() func_802A15A0_733670 (ScriptInstance * script, s32 isInitialCall)
Definition at line 123 of file lib.c.
Referenced by N().
func_802A1378_733448()
ApiStatus N() func_802A1378_733448 (ScriptInstance * script, s32 isInitialCall)
Definition at line 95 of file lib.c.
Referenced by N().
func_802A1438_733508()
ApiStatus N() func_802A1438_733508 (ScriptInstance * script, s32 isInitialCall)
Definition at line 107 of file lib.c.
Referenced by N().
AddHP()
ApiStatus N() AddHP (ScriptInstance * script, s32 isInitialCall)
Definition at line 3 of file AddHP.inc.c.
Referenced by N().
AddFP()
ApiStatus N() AddFP (ScriptInstance * script, s32 isInitialCall)
Definition at line 106 of file lib.c.
N() [1/5]
Script N (UseItemWithEffect)
N() [2/5]
Script N (PlayerGoHome)
N() [3/5]
Script N (UseItem)
N() [4/5]
Script N (EatItem)
N() [5/5]
Script N (DrinkItem)