src/jp/main_3FE70.c File Reference - Paper Mario Documentation
main_3FE70.c File Reference
Functions
s32 _Printf ()
s32 func_80064FF0 ()
s32 func_800654C0 ()
s32 func_80065518 ()
Function Documentation
_Printf()
s32 _Printf ()
Definition at line 3 of file main_3FE70.c.
Referenced by func_80025CC0(), func_80025CFC(), and func_80025D38().
func_80064FF0()
s32 func_80064FF0 ()
Definition at line 5 of file main_3FE70.c.
func_800654C0()
s32 func_800654C0 ()
Definition at line 7 of file main_3FE70.c.
func_80065518()
s32 func_80065518 ()
Definition at line 9 of file main_3FE70.c.