include/map.h File Reference - Paper Mario Documentation
map.h File Reference
Data Structures
struct MapConfig
Fields other than main, entryList, entryCount, background, and tattle are initialised when the map loads.
struct Map
struct Area
struct NpcAISettings
struct NpcSettings
struct ItemDrop
struct StatDrop
Describes heart/flower drop chances after defeating an Npc in the overworld.
struct StaticNpc
struct Enemy
struct NpcGroupList
Macros
#define M(sym) NAMESPACE(MAP_NAME, sym)
#define ENTRY_COUNT(entryList) (sizeof(entryList) / sizeof(Vec4f))
#define MAP_ID_MAX_LEN 7
"xxx_yyy" excluding null terminator.
#define NO_DROPS { F16(100), F16(0), 0, F16(0) }
#define STANDARD_HEART_DROPS(attempts)
#define GENEROUS_HEART_DROPS(attempts)
#define GENEROUS_WHEN_LOW_HEART_DROPS(attempts)
#define STANDARD_FLOWER_DROPS(attempts)
#define GENEROUS_WHEN_LOW_FLOWER_DROPS(attempts)
#define REDUCED_FLOWER_DROPS(attempts)
#define ANIMATION(sprite, palette, anim) ((sprite << 16) + (palette << 8) + anim)
#define OVERRIDE_MOVEMENT_SPEED(speed) (speed * 32767)
#define NO_OVERRIDE_MOVEMENT_SPEED OVERRIDE_MOVEMENT_SPEED(-1)
#define NPC_GROUP(npcs, formationID) { sizeof(npcs) / sizeof(StaticNpc), &npcs, formationID }
#define NPC_GROUP_LIST_END() { 0, 0, 0 }
Typedefs
typedef Vec4f EntryList[]
typedef s32 MapInit(void)
Functions
Enemy * get_enemy (NpcId npcId)
Variables
Area gAreas [29]
Zero-terminated.
SongID gSongsUsingVariationFlag [6]
Macro Definition Documentation
M
#define M (sym) NAMESPACE(MAP_NAME, sym)
Definition at line 10 of file map.h.
ENTRY_COUNT
#define ENTRY_COUNT (entryList) (sizeof(entryList) / sizeof(Vec4f))
Definition at line 12 of file map.h.
MAP_ID_MAX_LEN
#define MAP_ID_MAX_LEN 7
"xxx_yyy" excluding null terminator.
Definition at line 38 of file map.h.
NO_DROPS
#define NO_DROPS { F16(100), F16(0), 0, F16(0) }
Definition at line 116 of file map.h.
STANDARD_HEART_DROPS
#define STANDARD_HEART_DROPS (attempts)
Definition at line 118 of file map.h.
GENEROUS_HEART_DROPS
#define GENEROUS_HEART_DROPS (attempts)
Definition at line 126 of file map.h.
GENEROUS_WHEN_LOW_HEART_DROPS
#define GENEROUS_WHEN_LOW_HEART_DROPS (attempts)
Definition at line 134 of file map.h.
STANDARD_FLOWER_DROPS
#define STANDARD_FLOWER_DROPS (attempts)
Definition at line 142 of file map.h.
GENEROUS_WHEN_LOW_FLOWER_DROPS
#define GENEROUS_WHEN_LOW_FLOWER_DROPS (attempts)
Definition at line 150 of file map.h.
REDUCED_FLOWER_DROPS
#define REDUCED_FLOWER_DROPS (attempts)
Definition at line 158 of file map.h.
ANIMATION
#define ANIMATION (sprite, palette, anim) ((sprite << 16) + (palette << 8) + anim)
Definition at line 166 of file map.h.
OVERRIDE_MOVEMENT_SPEED
#define OVERRIDE_MOVEMENT_SPEED (speed) (speed * 32767)
Definition at line 168 of file map.h.
NO_OVERRIDE_MOVEMENT_SPEED
#define NO_OVERRIDE_MOVEMENT_SPEED OVERRIDE_MOVEMENT_SPEED(-1)
Definition at line 169 of file map.h.
NPC_GROUP
#define NPC_GROUP (npcs, formationID) { sizeof(npcs) / sizeof(StaticNpc), &npcs, formationID }
Definition at line 245 of file map.h.
NPC_GROUP_LIST_END
#define NPC_GROUP_LIST_END () { 0, 0, 0 }
Definition at line 246 of file map.h.
Typedef Documentation
EntryList
typedef Vec4f EntryList[]
Definition at line 14 of file map.h.
MapInit
typedef s32 MapInit(void)
Definition at line 36 of file map.h.
Function Documentation
get_enemy()
Enemy* get_enemy (NpcId npcId)
Definition at line 236 of file code_13870_len_6980.c.
Referenced by BindNpcAux(), BindNpcDefeat(), BindNpcHit(), BindNpcIdle(), BindNpcInteract(), EnableNpcAI(), EnableNpcAux(), GetNpcVar(), RestartNpcAI(), RestartNpcAux(), SetEnemyFlagBits(), SetNpcVar(), and SetTattleString().
Variable Documentation
gAreas
Area gAreas[29]
Zero-terminated.
Definition at line 251 of file map.h.
gSongsUsingVariationFlag
SongID gSongsUsingVariationFlag[6] extern
Lists the songs that are forced to use the variation determined by map.songVariation & 1.
See also
get_song_variation_override_for_cur_map
Referenced by get_song_variation_override_for_cur_map().