src/os/nuContMgr.c File Reference - Paper Mario Documentation
nuContMgr.c File Reference
Functions
s32 contRetrace ()
s32 contReadData ()
s32 contReadNW ()
s32 contQuery ()
u8 nuContMgrInit ()
void nuContMgrRemove ()
void nuContDataClose ()
void nuContDataOpen ()
void nuContDataLock ()
void nuContDataUnLock ()
Variables
u32 D_80093D20 = 0
void(* D_80093D24 [4])(void)
s32 D_80093D34 = 0
NUCallBackList nuContCallBack
Function Documentation
contRetrace()
s32 contRetrace ()
Definition at line 35 of file nuContMgr.c.
contReadData()
s32 contReadData ()
Definition at line 37 of file nuContMgr.c.
contReadNW()
s32 contReadNW ()
Definition at line 39 of file nuContMgr.c.
contQuery()
s32 contQuery ()
Definition at line 41 of file nuContMgr.c.
nuContMgrInit()
u8 nuContMgrInit ()
Definition at line 27 of file nuContMgr.c.
Referenced by nuContInit().
nuContMgrRemove()
void nuContMgrRemove ()
Definition at line 29 of file nuContMgr.c.
nuContDataClose()
void nuContDataClose ()
Definition at line 31 of file nuContMgr.c.
Referenced by nuContDataGet().
nuContDataOpen()
void nuContDataOpen ()
Definition at line 33 of file nuContMgr.c.
Referenced by nuContDataGet().
nuContDataLock()
void nuContDataLock ()
Definition at line 43 of file nuContMgr.c.
nuContDataUnLock()
void nuContDataUnLock ()
Definition at line 45 of file nuContMgr.c.
Variable Documentation
D_80093D20
u32 D_80093D20 = 0
Definition at line 9 of file nuContMgr.c.
D_80093D24
void(* D_80093D24[4])(void) (void)
Definition at line 11 of file nuContMgr.c.
D_80093D34
s32 D_80093D34 = 0
Definition at line 18 of file nuContMgr.c.
nuContCallBack
NUCallBackList nuContCallBack
Definition at line 20 of file nuContMgr.c.