src/world/partners.c File Reference - Paper Mario Documentation
partners.c File Reference
Functions
s32 world_partner_can_use_ability_default (Npc *partner)
s32 world_partner_can_player_pause_default (Npc *partner)
NpcId create_basic_npc (NpcBlueprint *blueprint)
s32 use_consumable (s32 arg0)
void remove_consumable (void)
s32 func_800EA4B0 ()
s32 func_800EA52C ()
s32 is_current_partner_flying (void)
void func_800EA5B8 (s32 *arg0)
void load_partner_npc (void)
void func_800EA6A8 (void)
s32 _use_partner_ability ()
void func_800EB168 (s32 arg0)
void func_800EB200 (s32 arg0)
void func_800EB2A4 (s32 arg0)
s32 partner_use_ability (void)
s32 partner_player_can_pause (void)
s32 partner_can_use_ability (void)
s32 partner_reset_data ()
void partner_initialize_data (void)
s32 partner_test_enemy_collision (s32 arg0)
Bytecode * partner_get_ride_script (void)
void partner_handle_before_battle (void)
void partner_handle_after_battle (void)
void partner_kill_ability_script (void)
void partner_suspend_ability_script (void)
void partner_resume_ability_script (void)
void enable_partner_walking (Npc *partner, s32 val)
void func_800EBA3C (Npc *partner)
void func_800EBB40 (Npc *partner)
s32 func_800EBC74 ()
void enable_partner_flying (Npc *partner, s32 val)
void update_player_move_history (Npc *partner)
void func_800ED5D0 (Npc *partner)
s32 func_800ED9F8 ()
s32 func_800EE994 (Npc *arg0)
s32 func_800EE9B8 ()
s32 func_800EECC4 (Npc *arg0)
s32 func_800EECE8 ()
void func_800EF300 (void)
void func_800EF314 (void)
void enable_partner_ai (void)
void set_parter_tether_distance (f32 arg0)
void reset_parter_tether_distance (void)
void func_800EF3C0 (s32 arg0, s32 arg1)
void func_800EF3D4 (s16 arg0)
void func_800EF3E4 (void)
void func_800EF414 (s32 arg0, s32 arg1)
void func_800EF43C (void)
void clear_partner_move_history (Npc *partner)
s32 func_800EF4E0 ()
void func_800EF600 (void)
void func_800EF628 (void)
s32 func_800EF640 ()
s32 func_800EF82C ()
Variables
s32 D_800F7F00 []
s32 D_800F7F40 []
s32 D_800F7F80 []
s32 * D_800F7FA8 = &D_80108068
s32 D_800F7FAC = 0x80108090
s32 D_800F7FB0 [] = { 0x80108298, 0x801082E8, 0x801082C0, 0x80108310, 0x80108338, 0x80108360, 0x80108388 }
s32 D_800F7FCC [] = { (s32)&D_801083D8, 0x80108428, 0x80108400, 0x80108450, 0x80108478, 0x801084A0, 0x801084C8 }
s32 D_800F7FE8 = -1
s32 D_800F7FEC = 1
s32 D_800F7FF0 = 2
s32 D_800F7FF4 = 4
s32 D_800F7FF8 = 5
s32 D_800F7FFC = 7
s32 D_800F8000 [] = { 8, 0, 0, 0 }
s32 D_800F8010 [] = { &code_code_3251D0_ROM_START, &code_code_3251D0_ROM_END, (s32)&D_802C05CC, 0x00000000 }
s32 D_800F8020 = 0
s32 D_800F8024 = 0
s32 D_800F8028 = 0
s32 D_800F802C = 0
f32 D_800F8030 = 0.0f
s8 D_800F8034 [] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }
s16 D_800F803A = 0
WorldPartner wPartners [12]
f32 D_800F833C = 0
f32 D_800F8340 = 0
f32 D_800F8344 = 0
s32 D_802C0000
f32 D_8010CFC0
s16 D_8010CFC8
s16 D_8010CFCA
s16 D_8010CFCE
Function Documentation
world_partner_can_use_ability_default()
s32 world_partner_can_use_ability_default (Npc * partner)
Definition at line 280 of file partners.c.
world_partner_can_player_pause_default()
s32 world_partner_can_player_pause_default (Npc * partner)
Definition at line 284 of file partners.c.
create_basic_npc()
NpcId create_basic_npc (NpcBlueprint * blueprint)
Referenced by load_partner_npc().
use_consumable()
s32 use_consumable (s32 arg0)
Definition at line 258 of file partners.c.
remove_consumable()
void remove_consumable (void)
Definition at line 273 of file partners.c.
Referenced by func_802BD4E8().
func_800EA4B0()
s32 func_800EA4B0 ()
Definition at line 278 of file partners.c.
func_800EA52C()
s32 func_800EA52C ()
Definition at line 288 of file partners.c.
is_current_partner_flying()
s32 is_current_partner_flying (void)
Definition at line 290 of file partners.c.
Referenced by PartnerIsFlying(), and TeleportPartnerToPlayer().
func_800EA5B8()
void func_800EA5B8 (s32 * arg0)
Definition at line 294 of file partners.c.
load_partner_npc()
void load_partner_npc (void)
Definition at line 298 of file partners.c.
func_800EA6A8()
void func_800EA6A8 (void)
Definition at line 338 of file partners.c.
_use_partner_ability()
s32 _use_partner_ability ()
Definition at line 342 of file partners.c.
Referenced by partner_use_ability().
func_800EB168()
void func_800EB168 (s32 arg0)
Definition at line 344 of file partners.c.
Referenced by Call800EB168(), func_80240000_8C7F90(), func_80245440_805CC0(), and GetPartnerCall800EB168().
func_800EB200()
void func_800EB200 (s32 arg0)
Definition at line 364 of file partners.c.
func_800EB2A4()
void func_800EB2A4 (s32 arg0)
Definition at line 387 of file partners.c.
Referenced by func_80240000_8C7F90().
partner_use_ability()
s32 partner_use_ability (void)
Definition at line 402 of file partners.c.
partner_player_can_pause()
s32 partner_player_can_pause (void)
Definition at line 423 of file partners.c.
Referenced by func_800E6904().
partner_can_use_ability()
s32 partner_can_use_ability (void)
Definition at line 433 of file partners.c.
Referenced by PartnerCanUseAbility().
partner_reset_data()
s32 partner_reset_data ()
Definition at line 440 of file partners.c.
partner_initialize_data()
void partner_initialize_data (void)
Definition at line 442 of file partners.c.
Referenced by step_init_state().
partner_test_enemy_collision()
s32 partner_test_enemy_collision (s32 arg0)
Definition at line 461 of file partners.c.
partner_get_ride_script()
Bytecode* partner_get_ride_script (void)
Definition at line 468 of file partners.c.
Referenced by func_80283810().
partner_handle_before_battle()
void partner_handle_before_battle (void)
Definition at line 477 of file partners.c.
partner_handle_after_battle()
void partner_handle_after_battle (void)
Definition at line 491 of file partners.c.
partner_kill_ability_script()
void partner_kill_ability_script (void)
Definition at line 521 of file partners.c.
partner_suspend_ability_script()
void partner_suspend_ability_script (void)
Definition at line 530 of file partners.c.
Referenced by PartnerSuspendAbilityScript().
partner_resume_ability_script()
void partner_resume_ability_script (void)
Definition at line 540 of file partners.c.
Referenced by PartnerResumeAbilityScript().
enable_partner_walking()
void enable_partner_walking (Npc * partner, s32 val)
Definition at line 550 of file partners.c.
Referenced by enable_partner_ai(), and GoombariaUpdate().
func_800EBA3C()
void func_800EBA3C (Npc * partner)
Definition at line 552 of file partners.c.
Referenced by GoombariaUpdate().
func_800EBB40()
void func_800EBB40 (Npc * partner)
Definition at line 554 of file partners.c.
Referenced by GoombariaUpdate().
func_800EBC74()
s32 func_800EBC74 ()
Definition at line 556 of file partners.c.
enable_partner_flying()
void enable_partner_flying (Npc * partner, s32 val)
Definition at line 558 of file partners.c.
Referenced by enable_partner_ai(), and TwinkUpdate().
update_player_move_history()
void update_player_move_history (Npc * partner)
Definition at line 560 of file partners.c.
Referenced by TwinkUpdate().
func_800ED5D0()
void func_800ED5D0 (Npc * partner)
Definition at line 562 of file partners.c.
Referenced by TwinkUpdate().
func_800ED9F8()
s32 func_800ED9F8 ()
Definition at line 564 of file partners.c.
func_800EE994()
s32 func_800EE994 (Npc * arg0)
Definition at line 571 of file partners.c.
Referenced by func_802BDB84(), func_802BE4E8_319238(), func_802BE8D4_31AE44(), GoombariaPutAway(), GoompaPutAway(), and TwinkPutAway().
func_800EE9B8()
s32 func_800EE9B8 ()
Definition at line 578 of file partners.c.
Referenced by func_802BDB84(), func_802BE4E8_319238(), func_802BE8D4_31AE44(), GoombariaPutAway(), GoompaPutAway(), and TwinkPutAway().
func_800EECC4()
s32 func_800EECC4 (Npc * arg0)
Definition at line 580 of file partners.c.
Referenced by func_802BD148_3196B8(), func_802BD300_318050(), GoombariaTakeOut(), GoompaTakeOut(), and TwinkTakeOut().
func_800EECE8()
s32 func_800EECE8 ()
Definition at line 587 of file partners.c.
Referenced by func_802BD148_3196B8(), func_802BD300_318050(), GoombariaTakeOut(), GoompaTakeOut(), and TwinkTakeOut().
func_800EF300()
void func_800EF300 (void)
Definition at line 589 of file partners.c.
Referenced by DisablePartnerAI().
func_800EF314()
void func_800EF314 (void)
Definition at line 593 of file partners.c.
Referenced by DisablePartnerAI().
enable_partner_ai()
void enable_partner_ai (void)
Definition at line 597 of file partners.c.
Referenced by EnablePartnerAI(), and func_80283908().
set_parter_tether_distance()
void set_parter_tether_distance (f32 arg0)
Definition at line 610 of file partners.c.
Referenced by func_80245504_805D84(), func_80281C20(), and func_80283B88().
reset_parter_tether_distance()
void reset_parter_tether_distance (void)
Definition at line 614 of file partners.c.
Referenced by func_8024552C_805DAC(), func_80281C84(), func_80283BB0(), and func_802B79C8_E20AD8().
func_800EF3C0()
void func_800EF3C0 (s32 arg0, s32 arg1)
Definition at line 618 of file partners.c.
Referenced by func_800EF414().
func_800EF3D4()
void func_800EF3D4 (s16 arg0)
Definition at line 623 of file partners.c.
Referenced by func_802B79C8_E20AD8(), func_802CF56C(), func_802D2C14(), and update_encounters_conversation().
func_800EF3E4()
void func_800EF3E4 (void)
Definition at line 627 of file partners.c.
Referenced by func_80281C84(), and func_802CF56C().
func_800EF414()
void func_800EF414 (s32 arg0, s32 arg1)
Definition at line 634 of file partners.c.
Referenced by func_80281C20().
func_800EF43C()
void func_800EF43C (void)
Definition at line 639 of file partners.c.
Referenced by func_802CF54C().
clear_partner_move_history()
void clear_partner_move_history (Npc * partner)
Definition at line 645 of file partners.c.
Referenced by ClearPartnerMoveHistory(), enable_partner_ai(), func_80240000_8C7F90(), TeleportPartnerToPlayer(), and world_goombario_pre_battle().
func_800EF4E0()
s32 func_800EF4E0 ()
Definition at line 647 of file partners.c.
func_800EF600()
void func_800EF600 (void)
Definition at line 649 of file partners.c.
Referenced by DisablePlayerInput(), func_802D6954(), and update_encounters_conversation().
func_800EF628()
void func_800EF628 (void)
Definition at line 658 of file partners.c.
Referenced by DisablePlayerInput().
func_800EF640()
s32 func_800EF640 ()
Definition at line 664 of file partners.c.
func_800EF82C()
s32 func_800EF82C ()
Definition at line 666 of file partners.c.
Variable Documentation
D_800F7F00
s32 D_800F7F00[]
Definition at line 37 of file partners.c.
D_800F7F40
s32 D_800F7F40[]
Definition at line 40 of file partners.c.
D_800F7F80
s32 D_800F7F80[]
Definition at line 43 of file partners.c.
D_800F7FA8
s32* D_800F7FA8 = &D_80108068
Definition at line 46 of file partners.c.
D_800F7FAC
s32 D_800F7FAC = 0x80108090
Definition at line 47 of file partners.c.
D_800F7FB0
s32 D_800F7FB0[] = { 0x80108298, 0x801082E8, 0x801082C0, 0x80108310, 0x80108338, 0x80108360, 0x80108388 }
Definition at line 48 of file partners.c.
D_800F7FCC
s32 D_800F7FCC[] = { (s32)&D_801083D8, 0x80108428, 0x80108400, 0x80108450, 0x80108478, 0x801084A0, 0x801084C8 }
Definition at line 49 of file partners.c.
D_800F7FE8
s32 D_800F7FE8 = -1
Definition at line 51 of file partners.c.
D_800F7FEC
s32 D_800F7FEC = 1
Definition at line 52 of file partners.c.
D_800F7FF0
s32 D_800F7FF0 = 2
Definition at line 53 of file partners.c.
D_800F7FF4
s32 D_800F7FF4 = 4
Definition at line 54 of file partners.c.
D_800F7FF8
s32 D_800F7FF8 = 5
Definition at line 55 of file partners.c.
D_800F7FFC
s32 D_800F7FFC = 7
Definition at line 56 of file partners.c.
D_800F8000
s32 D_800F8000[] = { 8, 0, 0, 0 }
Definition at line 57 of file partners.c.
D_800F8010
s32 D_800F8010[] = { &code_code_3251D0_ROM_START, &code_code_3251D0_ROM_END, (s32)&D_802C05CC, 0x00000000 }
Definition at line 58 of file partners.c.
Referenced by use_consumable().
D_800F8020
s32 D_800F8020 = 0
Definition at line 59 of file partners.c.
D_800F8024
s32 D_800F8024 = 0
Definition at line 60 of file partners.c.
Referenced by func_800EF3C0().
D_800F8028
s32 D_800F8028 = 0
Definition at line 61 of file partners.c.
Referenced by func_800EF3C0().
D_800F802C
s32 D_800F802C = 0
Definition at line 62 of file partners.c.
Referenced by func_800EF3E4().
D_800F8030
f32 D_800F8030 = 0.0f
Definition at line 63 of file partners.c.
D_800F8034
s8 D_800F8034[] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }
Definition at line 64 of file partners.c.
D_800F803A
s16 D_800F803A = 0
Definition at line 65 of file partners.c.
wPartners
WorldPartner wPartners[12]
Definition at line 67 of file partners.c.
Referenced by load_partner_npc().
D_800F833C
f32 D_800F833C = 0
Definition at line 248 of file partners.c.
Referenced by func_800EB168(), func_800EB200(), and partner_initialize_data().
D_800F8340
f32 D_800F8340 = 0
Definition at line 249 of file partners.c.
Referenced by func_800EB168(), func_800EB200(), and partner_initialize_data().
D_800F8344
f32 D_800F8344 = 0
Definition at line 250 of file partners.c.
Referenced by func_800EB168(), func_800EB200(), and partner_initialize_data().
D_802C0000
s32 D_802C0000 extern
Referenced by use_consumable().
D_8010CFC0
f32 D_8010CFC0 extern
Referenced by reset_parter_tether_distance(), and set_parter_tether_distance().
D_8010CFC8
s16 D_8010CFC8 extern
Referenced by enable_partner_ai(), func_800EE994(), func_800EECC4(), func_800EF300(), func_800EF314(), func_800EF3E4(), func_800EF414(), and func_800EF43C().
D_8010CFCA
s16 D_8010CFCA extern
Referenced by func_800EF3D4(), func_800EF3E4(), and func_800EF43C().
D_8010CFCE
s16 D_8010CFCE extern
Referenced by func_800EF3E4(), and func_800EF43C().