src/pause_items.c File Reference - Paper Mario Documentation
pause_items.c File Reference
Data Structures
struct struct8024F5C0
Functions
s32 pause_items_comparator (s16 *a, s16 *b)
s32 pause_items_get_pos_x (s32 page, s32 itemIndex)
s32 pause_items_get_pos_y (s32 page, s32 itemIndex)
s32 pause_items_get_column (s32 page, s32 itemIdx)
s32 pause_items_get_row (s32 page, s32 itemIdx)
s32 pause_items_is_visible (s32 y)
s32 pause_items_scroll_offset_y (s32 beforeY)
s32 pause_items_scroll_offset_x (s32 beforeX)
s32 pause_items_draw_contents ()
void pause_items_load_items (s32 invItems)
void pause_items_init (s8 *arg0)
s32 pause_items_handle_input ()
void pause_items_update (void)
void pause_items_cleanup (void)
Variables
struct struct8024F5C0 * D_8024F5C0 [1]
s32 D_8024F570 []
u32 D_802705C4
Function Documentation
pause_items_comparator()
s32 pause_items_comparator (s16 * a, s16 * b)
Definition at line 12 of file pause_items.c.
Referenced by pause_items_load_items().
pause_items_get_pos_x()
s32 pause_items_get_pos_x (s32 page, s32 itemIndex)
Definition at line 20 of file pause_items.c.
pause_items_get_pos_y()
s32 pause_items_get_pos_y (s32 page, s32 itemIndex)
Definition at line 24 of file pause_items.c.
Referenced by pause_items_load_items(), and pause_items_update().
pause_items_get_column()
s32 pause_items_get_column (s32 page, s32 itemIdx)
Definition at line 28 of file pause_items.c.
pause_items_get_row()
s32 pause_items_get_row (s32 page, s32 itemIdx)
Definition at line 32 of file pause_items.c.
pause_items_is_visible()
s32 pause_items_is_visible (s32 y)
Definition at line 36 of file pause_items.c.
pause_items_scroll_offset_y()
s32 pause_items_scroll_offset_y (s32 beforeY)
Definition at line 43 of file pause_items.c.
pause_items_scroll_offset_x()
s32 pause_items_scroll_offset_x (s32 beforeX)
Definition at line 47 of file pause_items.c.
pause_items_draw_contents()
s32 pause_items_draw_contents ()
Definition at line 51 of file pause_items.c.
pause_items_load_items()
void pause_items_load_items (s32 invItems)
Definition at line 56 of file pause_items.c.
Referenced by pause_items_init().
pause_items_init()
void pause_items_init (s8 * arg0)
Definition at line 141 of file pause_items.c.
pause_items_handle_input()
s32 pause_items_handle_input ()
Definition at line 164 of file pause_items.c.
pause_items_update()
void pause_items_update (void)
Definition at line 166 of file pause_items.c.
pause_items_cleanup()
void pause_items_cleanup (void)
Definition at line 191 of file pause_items.c.
Variable Documentation
D_8024F5C0
struct struct8024F5C0* D_8024F5C0[1] extern
Referenced by pause_items_init().
D_8024F570
s32 D_8024F570[] extern
Referenced by pause_items_init().
D_802705C4
u32 D_802705C4 extern
Referenced by pause_items_load_items().