src/battle/item/pow_block/pow_block.h File Reference - Paper Mario Documentation
pow_block.h File Reference
Macros
#define NAMESPACE battle_item_pow_block
Functions
ApiStatus func_80273444 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_80269EAC (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1318_718B68 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A123C_718A8C (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A12E4_718B34 (ScriptInstance *script, s32 isInitialCall)
Script N (UseItemWithEffect)
Script N (PlayerGoHome)
Macro Definition Documentation
NAMESPACE
#define NAMESPACE battle_item_pow_block
Definition at line 8 of file pow_block.h.
Function Documentation
func_80273444()
ApiStatus func_80273444 (ScriptInstance * script, s32 isInitialCall)
func_80269EAC()
ApiStatus func_80269EAC (ScriptInstance * script, s32 isInitialCall)
Definition at line 119 of file code_197F40.c.
func_802A1318_718B68()
ApiStatus N() func_802A1318_718B68 (ScriptInstance * script, s32 isInitialCall)
Definition at line 85 of file lib.c.
Referenced by N().
func_802A123C_718A8C()
ApiStatus N() func_802A123C_718A8C (ScriptInstance * script, s32 isInitialCall)
Definition at line 57 of file lib.c.
Referenced by N().
func_802A12E4_718B34()
ApiStatus N() func_802A12E4_718B34 (ScriptInstance * script, s32 isInitialCall)
Definition at line 77 of file lib.c.
Referenced by N().
N() [1/2]
Script N (UseItemWithEffect)
N() [2/2]
Script N (PlayerGoHome)