src/battle/item/shooting_star/lib.c File Reference - Paper Mario Documentation
lib.c File Reference
Functions
ApiStatus N() GiveRefund (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() GiveRefundCleanup (ScriptInstance *script, s32 isInitialCall)
void func_8006FE30 (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7)
ApiStatus N() func_802A123C_71D9AC (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1388_71DAF8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1444_71DBB4 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A14D4_71DC44 (ScriptInstance *script, s32 isInitialCall)
Script N (UseItemWithEffect)
Script N (UseItem)
Script N (PlayerGoHome)
Script N (EatItem)
Script N (DrinkItem)
Variables
s32 D_80108A64
static MenuIcon * D_802A1EE0
Function Documentation
GiveRefund()
ApiStatus N() GiveRefund (ScriptInstance * script, s32 isInitialCall)
Definition at line 6 of file lib.c.
GiveRefundCleanup()
ApiStatus N() GiveRefundCleanup (ScriptInstance * script, s32 isInitialCall)
Definition at line 45 of file lib.c.
func_8006FE30()
void func_8006FE30 (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7)
Definition at line 36 of file code_4ac90_len_3910.c.
Referenced by func_802A123C_71D9AC().
func_802A123C_71D9AC()
ApiStatus N() func_802A123C_71D9AC (ScriptInstance * script, s32 isInitialCall)
Definition at line 61 of file lib.c.
Referenced by N().
func_802A1388_71DAF8()
ApiStatus N() func_802A1388_71DAF8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 106 of file lib.c.
Referenced by N().
func_802A1444_71DBB4()
ApiStatus N() func_802A1444_71DBB4 (ScriptInstance * script, s32 isInitialCall)
Definition at line 117 of file lib.c.
Referenced by N().
func_802A14D4_71DC44()
ApiStatus N() func_802A14D4_71DC44 (ScriptInstance * script, s32 isInitialCall)
Definition at line 133 of file lib.c.
Referenced by N().
N() [1/5]
Script N (UseItemWithEffect)
N() [2/5]
Script N (UseItem)
N() [3/5]
Script N (PlayerGoHome)
N() [4/5]
Script N (EatItem)
N() [5/5]
Script N (DrinkItem)
Variable Documentation
D_80108A64
s32 D_80108A64 extern
Definition at line 3 of file lib.c.
D_802A1EE0
MenuIcon* D_802A1EE0 static
Definition at line 4 of file lib.c.
Referenced by GiveRefund(), and GiveRefundCleanup().