src/battle/item/sleepy_sheep/lib.c File Reference - Paper Mario Documentation
lib.c File Reference
Functions
ApiStatus N() GiveRefund (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() GiveRefundCleanup (ScriptInstance *script, s32 isInitialCall)
s32 N (D_802A3E88_7214D8)[]
f32 N (D_802A3F00_721550)[]
s32 N (D_802A3F28_721578)[]
void fx_walk_large (s32, f32, f32, f32, s32)
void func_802D4364 (s32, s32, s32, s32)
void func_802D43AC (s32, f32, f32, f32)
void func_802D43F4 (s32)
ApiStatus func_802A123C_71E88C (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1740_71ED90 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1848_71EE98 (ScriptInstance *script, s32 isInitialCall)
Script N (UseItemWithEffect)
Script N (UseItem)
Script N (PlayerGoHome)
Script N (EatItem)
Script N (DrinkItem)
Variables
s32 D_80108A64
static MenuIcon * D_802A3F50
Vec3f D_802A3F88
s32 * D_802A3F58
Function Documentation
GiveRefund()
ApiStatus N() GiveRefund (ScriptInstance * script, s32 isInitialCall)
Definition at line 6 of file lib.c.
GiveRefundCleanup()
ApiStatus N() GiveRefundCleanup (ScriptInstance * script, s32 isInitialCall)
Definition at line 45 of file lib.c.
N() [1/8]
s32 N (D_802A3E88_7214D8)
N() [2/8]
f32 N (D_802A3F00_721550)
N() [3/8]
s32 N (D_802A3F28_721578)
fx_walk_large()
void fx_walk_large (s32 , f32 , f32 , f32 , s32)
Referenced by func_802A123C_71E88C().
func_802D4364()
void func_802D4364 (s32 , s32 , s32 , s32)
Referenced by func_802A123C_71E88C().
func_802D43AC()
void func_802D43AC (s32 index, f32 arg1, f32 arg2, f32 arg3)
Definition at line 580 of file code_F5750.c.
Referenced by func_802A123C_71E88C().
func_802D43F4()
void func_802D43F4 (s32)
Referenced by func_802A123C_71E88C().
func_802A123C_71E88C()
ApiStatus func_802A123C_71E88C (ScriptInstance * script, s32 isInitialCall)
Definition at line 92 of file lib.c.
Referenced by N().
func_802A1740_71ED90()
ApiStatus N() func_802A1740_71ED90 (ScriptInstance * script, s32 isInitialCall)
Definition at line 212 of file lib.c.
Referenced by N().
func_802A1848_71EE98()
ApiStatus N() func_802A1848_71EE98 (ScriptInstance * script, s32 isInitialCall)
Definition at line 242 of file lib.c.
Referenced by N().
N() [4/8]
Script N (UseItemWithEffect)
N() [5/8]
Script N (UseItem)
N() [6/8]
Script N (PlayerGoHome)
N() [7/8]
Script N (EatItem)
N() [8/8]
Script N (DrinkItem)
Variable Documentation
D_80108A64
s32 D_80108A64 extern
Definition at line 3 of file lib.c.
D_802A3F50
MenuIcon* D_802A3F50 static
Definition at line 4 of file lib.c.
Referenced by GiveRefund(), and GiveRefundCleanup().
D_802A3F88
Vec3f D_802A3F88 extern
Referenced by func_802A123C_71E88C().
D_802A3F58
s32* D_802A3F58 extern
Referenced by func_802A123C_71E88C().