src/battle/item/strange_cake/strange_cake.h File Reference - Paper Mario Documentation
strange_cake.h File Reference
Macros
#define NAMESPACE battle_item_strange_cake
Functions
ApiStatus func_802D75D8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D7520 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1A8C_731D8C (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A18D8_731BD8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() AddFP (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A13E4_7316E4 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1AD8_731DD8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1B14_731E14 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1B68_731E68 (ScriptInstance *script, s32 isInitialCall)
Script N (UseItemWithEffect)
Script N (PlayerGoHome)
Script N (EatItem)
Script N (script7)
Script N (script8)
Script N (script9)
Macro Definition Documentation
NAMESPACE
#define NAMESPACE battle_item_strange_cake
Definition at line 8 of file strange_cake.h.
Function Documentation
func_802D75D8()
ApiStatus func_802D75D8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 18 of file code_FBE10.c.
func_802D7520()
ApiStatus func_802D7520 (ScriptInstance * script, s32 isInitialCall)
Definition at line 7 of file code_FBE10.c.
func_802A1A8C_731D8C()
ApiStatus N() func_802A1A8C_731D8C (ScriptInstance * script, s32 isInitialCall)
Definition at line 296 of file lib.c.
Referenced by N().
func_802A18D8_731BD8()
ApiStatus N() func_802A18D8_731BD8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 267 of file lib.c.
Referenced by N().
AddFP()
ApiStatus N() AddFP (ScriptInstance * script, s32 isInitialCall)
Definition at line 106 of file lib.c.
func_802A13E4_7316E4()
ApiStatus N() func_802A13E4_7316E4 (ScriptInstance * script, s32 isInitialCall)
Definition at line 114 of file lib.c.
Referenced by N().
func_802A1AD8_731DD8()
ApiStatus N() func_802A1AD8_731DD8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 310 of file lib.c.
Referenced by N().
func_802A1B14_731E14()
ApiStatus N() func_802A1B14_731E14 (ScriptInstance * script, s32 isInitialCall)
Definition at line 320 of file lib.c.
Referenced by N().
func_802A1B68_731E68()
ApiStatus N() func_802A1B68_731E68 (ScriptInstance * script, s32 isInitialCall)
Definition at line 332 of file lib.c.
Referenced by N().
N() [1/6]
Script N (UseItemWithEffect)
N() [2/6]
Script N (PlayerGoHome)
N() [3/6]
Script N (EatItem)
N() [4/6]
Script N (script7)
N() [5/6]
Script N (script8)
N() [6/6]
Script N (script9)