src/battle/item/strange_cake/lib.c File Reference - Paper Mario Documentation
lib.c File Reference
Functions
ApiStatus N() GiveRefund (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() GiveRefundCleanup (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A123C_73153C (ScriptInstance *script, s32 isInitialCall)
s32 N (D_802A2848_732B48)[]
s32 N (D_802A2858_732B58)[]
ApiStatus N() func_802A13E4_7316E4 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1818_731B18 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A18D8_731BD8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1A40_731D40 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1A8C_731D8C (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1AD8_731DD8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1B14_731E14 (ScriptInstance *script, s32 isInitialCall)
ApiStatus N() func_802A1B68_731E68 (ScriptInstance *script, s32 isInitialCall)
Script N (UseItemWithEffect)
Script N (UseItem)
Script N (PlayerGoHome)
Script N (EatItem)
Script N (DrinkItem)
Variables
s32 D_80108A64
static MenuIcon * D_802A2DD0
s32 D_802A25E4
MenuIcon * D_802A2DF4
s32 D_802A2DD8
s32 D_802A2DEC
s32 D_802A2DF0
s32 D_802A2DF8
s32 D_802A2DFC
s32 D_802A2E00
MenuIcon ** D_802A25C8
Function Documentation
GiveRefund()
ApiStatus N() GiveRefund (ScriptInstance * script, s32 isInitialCall)
Definition at line 6 of file lib.c.
GiveRefundCleanup()
ApiStatus N() GiveRefundCleanup (ScriptInstance * script, s32 isInitialCall)
Definition at line 45 of file lib.c.
func_802A123C_73153C()
ApiStatus N() func_802A123C_73153C (ScriptInstance * script, s32 isInitialCall)
Definition at line 63 of file lib.c.
Referenced by func_802A13E4_7316E4().
N() [1/7]
s32 N (D_802A2848_732B48)
N() [2/7]
s32 N (D_802A2858_732B58)
func_802A13E4_7316E4()
ApiStatus N() func_802A13E4_7316E4 (ScriptInstance * script, s32 isInitialCall)
Definition at line 114 of file lib.c.
Referenced by N().
func_802A1818_731B18()
ApiStatus N() func_802A1818_731B18 (ScriptInstance * script, s32 isInitialCall)
Definition at line 256 of file lib.c.
func_802A18D8_731BD8()
ApiStatus N() func_802A18D8_731BD8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 267 of file lib.c.
Referenced by N().
func_802A1A40_731D40()
ApiStatus N() func_802A1A40_731D40 (ScriptInstance * script, s32 isInitialCall)
Definition at line 282 of file lib.c.
func_802A1A8C_731D8C()
ApiStatus N() func_802A1A8C_731D8C (ScriptInstance * script, s32 isInitialCall)
Definition at line 296 of file lib.c.
Referenced by N().
func_802A1AD8_731DD8()
ApiStatus N() func_802A1AD8_731DD8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 310 of file lib.c.
Referenced by N().
func_802A1B14_731E14()
ApiStatus N() func_802A1B14_731E14 (ScriptInstance * script, s32 isInitialCall)
Definition at line 320 of file lib.c.
Referenced by N().
func_802A1B68_731E68()
ApiStatus N() func_802A1B68_731E68 (ScriptInstance * script, s32 isInitialCall)
Definition at line 332 of file lib.c.
Referenced by N().
N() [3/7]
Script N (UseItemWithEffect)
N() [4/7]
Script N (UseItem)
N() [5/7]
Script N (PlayerGoHome)
N() [6/7]
Script N (EatItem)
N() [7/7]
Script N (DrinkItem)
Variable Documentation
D_80108A64
s32 D_80108A64 extern
Definition at line 3 of file lib.c.
D_802A2DD0
MenuIcon* D_802A2DD0 static
Definition at line 4 of file lib.c.
Referenced by GiveRefund(), and GiveRefundCleanup().
D_802A25E4
s32 D_802A25E4 extern
D_802A2DF4
s32 D_802A2DF4 extern
Definition at line 99 of file lib.c.
Referenced by func_802A123C_73153C(), and func_802A13E4_7316E4().
D_802A2DD8
s32 * D_802A2DD8 extern
Definition at line 103 of file lib.c.
Referenced by func_802A123C_73153C(), and func_802A13E4_7316E4().
D_802A2DEC
s32 D_802A2DEC extern
Referenced by func_802A13E4_7316E4().
D_802A2DF0
s32 D_802A2DF0 extern
Referenced by func_802A13E4_7316E4().
D_802A2DF8
s32 D_802A2DF8 extern
Referenced by func_802A13E4_7316E4().
D_802A2DFC
s32 D_802A2DFC extern
Referenced by func_802A13E4_7316E4().
D_802A2E00
s32 D_802A2E00 extern
Referenced by func_802A13E4_7316E4().
D_802A25C8
MenuIcon** D_802A25C8 extern