GameMode Struct Reference - Paper Mario Documentation
GameMode Struct Reference
Data Fields
u16 flags
void(* init)(void)
void(* step)(struct GameMode *)
void(* unk_0C)(void)
void(* render)(void)
void(* renderAux)(void)
Detailed Description
Definition at line 303 of file code_a5dd0_len_114e0.c.
Field Documentation
flags
u16 GameMode::flags
Definition at line 304 of file code_a5dd0_len_114e0.c.
Referenced by func_80112D84(), func_80112DD4(), func_80112DFC(), func_80112E24(), func_80112E4C(), set_game_mode_slot(), set_next_game_mode(), and step_current_game_mode().
init
void(* GameMode::init) (void)
Definition at line 305 of file code_a5dd0_len_114e0.c.
Referenced by set_game_mode_slot(), and set_next_game_mode().
step
void(* GameMode::step) (struct GameMode *)
Definition at line 306 of file code_a5dd0_len_114e0.c.
Referenced by set_game_mode_slot(), set_next_game_mode(), and step_current_game_mode().
unk_0C
void(* GameMode::unk_0C) (void)
Definition at line 307 of file code_a5dd0_len_114e0.c.
Referenced by set_game_mode_slot(), and set_next_game_mode().
render
void(* GameMode::render) (void)
Definition at line 308 of file code_a5dd0_len_114e0.c.
Referenced by set_game_mode_slot(), and set_next_game_mode().
renderAux
void(* GameMode::renderAux) (void)
See also
func_80112FC4
Definition at line 309 of file code_a5dd0_len_114e0.c.
Referenced by func_80112D84(), set_game_mode_slot(), and set_next_game_mode().
The documentation for this struct was generated from the following file:
src/code_a5dd0_len_114e0.c