src/world/world.c File Reference - Paper Mario Documentation
world.c File Reference
Data Structures
struct AssetHeader
Macros
#define ASSET_TABLE_ROM_START 0x1E40000
#define ASSET_TABLE_HEADER_SIZE 0x20
#define ASSET_TABLE_FIRST_ENTRY (ASSET_TABLE_ROM_START + ASSET_TABLE_HEADER_SIZE)
#define AREA(area, jp_name) { ARRAY_COUNT(area##_maps), area##_maps, "area_" #area, jp_name }
#define MAP(map)
#define MAP_UNSPLIT(map, configVRAM)
Functions
void load_world_script_api (void)
void load_map_by_IDs (s16 areaID, s16 mapID, s16 loadType)
s32 get_current_map_config ()
MapConfig * get_current_map_header ()
s32 get_map_IDs_by_name (const char *mapName, s16 *areaID, s16 *mapID)
void * load_asset_by_name (char *assetName, s32 *decompressedSize)
s32 get_asset_offset (char *assetName, s32 *compressedSize)
Variables
s32 D_8008FF60 [] = { 0, 1, 2, 3 }
const s32 D_800989A0 []
MapConfig D_800A41E8
s32 D_800A41E0
s32 D_800D9668
s16 D_8008FF70 []
f32 D_8008FFB8 []
Map mac_maps []
Toad Town.
Map tik_maps []
Toad Town Tunnels.
Map kgr_maps []
Inside the Whale.
Map kmr_maps []
Goomba Region.
Map iwa_maps []
Mt. Rugged.
Map dro_maps []
Dry Dry Outpost.
Map sbk_maps []
Dry Dry Desert.
Map isk_maps []
Dry Dry Ruins.
Map trd_maps []
Koopa Bros. Fortress.
Map nok_maps []
Koopa Region.
Map hos_maps []
Star Region.
Map kpa_maps []
Bowser's Castle.
Map osr_maps []
Peach's Castle Grounds.
Map kkj_maps []
Map jan_maps []
Jade Jungle.
Map mim_maps []
Forever Forest.
Map obk_maps []
Boo's Mansion.
Map arn_maps []
Gusty Gulch.
Map dgb_maps []
Tubba Blubba's Castle.
Map kzn_maps []
Mt. Lavalava.
Map flo_maps []
Flower Fields.
Map sam_maps []
Shiver Region.
Map pra_maps []
Crystal Palace.
Map omo_maps []
Shy Guy's Toy Box.
Map tst_maps []
Debug.
Map end_maps []
Credits.
Map mgm_maps []
Toad Town Playroom.
Map gv_maps []
Game Over.
Area gAreas []
const f32 world_rodata_alignment = 0.0f
Macro Definition Documentation
ASSET_TABLE_ROM_START
#define ASSET_TABLE_ROM_START 0x1E40000
Definition at line 5 of file world.c.
ASSET_TABLE_HEADER_SIZE
#define ASSET_TABLE_HEADER_SIZE 0x20
Definition at line 6 of file world.c.
ASSET_TABLE_FIRST_ENTRY
#define ASSET_TABLE_FIRST_ENTRY (ASSET_TABLE_ROM_START + ASSET_TABLE_HEADER_SIZE)
Definition at line 7 of file world.c.
AREA
#define AREA (area, jp_name) { ARRAY_COUNT(area##_maps), area##_maps, "area_" #area, jp_name }
Definition at line 272 of file world.c.
MAP
#define MAP (map)
Definition at line 274 of file world.c.
MAP_UNSPLIT
#define MAP_UNSPLIT (map, configVRAM)
Definition at line 282 of file world.c.
Function Documentation
load_world_script_api()
void load_world_script_api (void)
Definition at line 36 of file world.c.
Referenced by load_map_by_IDs(), and state_step_unpause().
load_map_by_IDs()
void load_map_by_IDs (s16 areaID, s16 mapID, s16 loadType)
Definition at line 40 of file world.c.
get_current_map_config()
s32 get_current_map_config ()
Definition at line 201 of file world.c.
get_current_map_header()
MapConfig* get_current_map_header (void)
Definition at line 205 of file world.c.
Referenced by func_802E8BC0(), GetEntryPos(), and state_step_unpause().
get_map_IDs_by_name()
s32 get_map_IDs_by_name (const char * mapName, s16 * areaID, s16 * mapID)
Definition at line 211 of file world.c.
load_asset_by_name()
void* load_asset_by_name (char * assetName, s32 * decompressedSize)
Definition at line 233 of file world.c.
Referenced by load_map_bg(), load_map_by_IDs(), and state_step_unpause().
get_asset_offset()
s32 get_asset_offset (char * assetName, s32 * compressedSize)
Definition at line 253 of file world.c.
Referenced by load_map_by_IDs().
Variable Documentation
D_8008FF60
s32 D_8008FF60[] = { 0, 1, 2, 3 }
Definition at line 9 of file world.c.
Referenced by load_map_by_IDs().
D_800989A0
const s32 D_800989A0[]
Definition at line 12 of file world.c.
D_800A41E8
MapConfig D_800A41E8 extern
Referenced by get_current_map_header(), and load_map_by_IDs().
D_800A41E0
s32 D_800A41E0 extern
Referenced by get_current_map_config(), and load_map_by_IDs().
D_800D9668
s32 D_800D9668 extern
Referenced by load_map_by_IDs().
D_8008FF70
s16 D_8008FF70[]
Definition at line 291 of file world.c.
D_8008FFB8
f32 D_8008FFB8[]
Definition at line 294 of file world.c.
mac_maps
Map mac_maps[]
Toad Town.
Definition at line 299 of file world.c.
tik_maps
Map tik_maps[]
Toad Town Tunnels.
Definition at line 311 of file world.c.
kgr_maps
Map kgr_maps[]
Inside the Whale.
Definition at line 337 of file world.c.
kmr_maps
Map kmr_maps[]
Goomba Region.
Definition at line 344 of file world.c.
iwa_maps
Map iwa_maps[]
Mt. Rugged.
Definition at line 365 of file world.c.
dro_maps
Map dro_maps[]
Dry Dry Outpost.
Definition at line 376 of file world.c.
sbk_maps
Map sbk_maps[]
Dry Dry Desert.
Definition at line 382 of file world.c.
isk_maps
Map isk_maps[]
Dry Dry Ruins.
Definition at line 436 of file world.c.
trd_maps
Map trd_maps[]
Koopa Bros. Fortress.
Definition at line 457 of file world.c.
nok_maps
Map nok_maps[]
Koopa Region.
Definition at line 472 of file world.c.
hos_maps
Map hos_maps[]
Star Region.
Definition at line 485 of file world.c.
kpa_maps
Map kpa_maps[]
Bowser's Castle.
Definition at line 498 of file world.c.
osr_maps
Map osr_maps[]
Peach's Castle Grounds.
Definition at line 552 of file world.c.
kkj_maps
Map kkj_maps[]
Peach's Castle
Bug:
There are two entries for kkj_26; the latter is unreachable.
Definition at line 562 of file world.c.
jan_maps
Map jan_maps[]
Jade Jungle.
Definition at line 591 of file world.c.
mim_maps
Map mim_maps[]
Forever Forest.
Definition at line 617 of file world.c.
obk_maps
Map obk_maps[]
Boo's Mansion.
Definition at line 633 of file world.c.
arn_maps
Map arn_maps[]
Gusty Gulch.
Definition at line 646 of file world.c.
dgb_maps
Map dgb_maps[]
Tubba Blubba's Castle.
Definition at line 661 of file world.c.
kzn_maps
Map kzn_maps[]
Mt. Lavalava.
Definition at line 684 of file world.c.
flo_maps
Map flo_maps[]
Flower Fields.
Definition at line 705 of file world.c.
sam_maps
Map sam_maps[]
Shiver Region.
Definition at line 729 of file world.c.
pra_maps
Map pra_maps[]
Crystal Palace.
Definition at line 745 of file world.c.
omo_maps
Map omo_maps[]
Shy Guy's Toy Box.
Definition at line 781 of file world.c.
tst_maps
Map tst_maps[]
Debug.
Definition at line 802 of file world.c.
end_maps
Map end_maps[]
Credits.
Definition at line 815 of file world.c.
mgm_maps
Map mgm_maps[]
Toad Town Playroom.
Definition at line 821 of file world.c.
gv_maps
Map gv_maps[]
Game Over.
Definition at line 829 of file world.c.
gAreas
Area gAreas[]
Definition at line 833 of file world.c.
Referenced by bgm_get_map_default_variation(), get_map_IDs_by_name(), load_map_by_IDs(), and state_step_unpause().
world_rodata_alignment
const f32 world_rodata_alignment = 0.0f
Definition at line 865 of file world.c.